// backend/services/examBank/ba102.bank.js
// Ngân hàng câu hỏi chuẩn hóa: BA102 — Quản Trị Học Đại Cương (Principles of Management)
// Tổng cộng: 120 câu hỏi (3 Đề gốc x 40 câu hỏi)
'use strict';

function q(id, content, difficulty, answers, correctIdx, clo = 'CLO1') {
  return {
    id,
    course_code: 'BA102',
    content,
    difficulty,
    default_mark: 0.25,
    clo,
    answers: answers.map((text, idx) => ({
      id: `${id}_A${idx + 1}`,
      letter: ['A', 'B', 'C', 'D'][idx],
      content: text,
      is_correct: idx === correctIdx,
      fraction: idx === correctIdx ? 1.0 : 0.0
    }))
  };
}

// ĐỀ GỐC 1 (40 câu): Bản chất quản trị, Cấp bậc, Kỹ năng, Vai trò quản trị, Lịch sử các trường phái quản trị & Môi trường quản trị
const root1 = [
  // Nhận biết (10 câu)
  q('BA102_Q001', 'Quản trị được định nghĩa một cách tổng quát là quá trình:', 'EASY', ['Ra lệnh cho cấp dưới làm việc', 'Hoạch định, tổ chức, lãnh đạo và kiểm tra các nguồn lực nhằm đạt được mục tiêu của tổ chức một cách hiệu quả và hiệu năng', 'Tính toán sổ sách kế toán', 'Sản xuất ra sản phẩm hữu hình'], 1, 'CLO1'),
  q('BA102_Q002', 'Bốn chức năng cơ bản của quá trình quản trị (thường viết tắt là POLC) gồm những chức năng nào?', 'EASY', ['Kế toán, Tài chính, Nhân sự, Bán hàng', 'Hoạch định (Planning), Tổ chức (Organizing), Lãnh đạo (Leading), Kiểm tra (Controlling)', 'Sản xuất, Tiếp thị, Vận hành, Mua hàng', 'Tuyển dụng, Đào tạo, Đánh giá, Trả lương'], 1, 'CLO1'),
  q('BA102_Q003', 'Khái niệm "Hiệu năng" (Effectiveness) trong quản trị gắn liền với mệnh đề nào?', 'EASY', ['Làm việc với chi phí thấp nhất', '"Làm đúng việc" (Doing the right things) - đạt được các mục tiêu đã đề ra của tổ chức', 'Rút ngắn thời gian họp', 'Sử dụng ít lao động nhất'], 1, 'CLO1'),
  q('BA102_Q004', 'Khái niệm "Hiệu quả" (Efficiency) trong quản trị nhấn mạnh vào điều gì?', 'EASY', ['Tăng giá bán sản phẩm', '"Làm việc đúng cách" (Doing things right) - tối thiểu hóa chi phí nguồn lực đầu vào để đạt được kết quả đầu ra mong muốn', 'Làm việc theo cảm tính', 'Chi tiêu tối đa ngân sách'], 1, 'CLO1'),
  q('BA102_Q005', 'Theo Robert Katz, ba kỹ năng cơ bản của nhà quản trị bao gồm:', 'EASY', ['Kỹ năng tin học, ngoại ngữ, lái xe', 'Kỹ năng kỹ thuật (chuyên môn), kỹ năng nhân sự (con người), kỹ năng tư duy (khái niệm)', 'Kỹ năng thuyết trình, bán hàng, đàm phán', 'Kỹ năng ghi chép, kế toán, pháp lý'], 1, 'CLO1'),
  q('BA102_Q006', 'Đối với nhà quản trị cấp cao (Top Managers, như Tổng giám đốc CEO), kỹ năng nào đóng vai trò quan trọng nhất?', 'EASY', ['Kỹ năng kỹ thuật chuyên môn', 'Kỹ năng tư duy (Conceptual skills) - hoạch định tầm nhìn và chiến lược dài hạn', 'Kỹ năng thao tác máy móc', 'Kỹ năng trực tiếp bán hàng'], 1, 'CLO1'),
  q('BA102_Q007', 'Ai được coi là "Cha đẻ của thuyết quản trị khoa học" (Scientific Management)?', 'EASY', ['Henri Fayol', 'Frederick Winslow Taylor', 'Max Weber', 'Elton Mayo'], 1, 'CLO1'),
  q('BA102_Q008', 'Henri Fayol là đại diện tiêu biểu của trường phái quản trị nào với 14 nguyên tắc quản trị kinh điển?', 'EASY', ['Trường phái quản trị hành chính / tổng quát (Administrative Management)', 'Trường phái quản trị hành vi', 'Trường phái định lượng', 'Trường phái hệ thống'], 0, 'CLO1'),
  q('BA102_Q009', 'Max Weber nổi tiếng với lý thuyết quản trị nào nhấn mạnh vào cơ cấu quyền lực hợp pháp và tính quy chuẩn?', 'EASY', ['Quản trị tác nghiệp', 'Thuyết quản trị quan liêu bàn giấy (Bureaucracy)', 'Tâm lý học hành vi', 'Quản trị hỗn độn'], 1, 'CLO1'),
  q('BA102_Q010', 'Các thí nghiệm tại nhà máy Hawthorne (Hawthorne Studies) do Elton Mayo thực hiện đã mở đầu cho trường phái quản trị nào?', 'EASY', ['Quản trị cổ điển', 'Trường phái các mối quan hệ con người / tâm lý xã hội (Human Relations Movement)', 'Trường phái toán học', 'Trường phái TQM'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA102_Q011', 'Theo Henry Mintzberg, 10 vai trò của nhà quản trị được chia thành 3 nhóm lớn nào?', 'MEDIUM', ['Quản lý tiền, quản lý người, quản lý hàng', 'Nhóm vai trò quan hệ con người (Interpersonal), nhóm vai trò thông tin (Informational), nhóm vai trò ra quyết định (Decisional)', 'Nhóm vai trò lập kế hoạch, giám sát, báo cáo', 'Nhóm vai trò pháp lý, kinh doanh, đối ngoại'], 1, 'CLO2'),
  q('BA102_Q012', 'Khi một nhà quản trị đóng vai trò "Người giải quyết xáo trộn / xung đột" (Disturbance Handler), vai trò này thuộc nhóm nào theo Mintzberg?', 'MEDIUM', ['Nhóm vai trò thông tin', 'Nhóm vai trò ra quyết định (Decisional roles)', 'Nhóm vai trò quan hệ con người', 'Nhóm vai trò kỹ thuật'], 1, 'CLO2'),
  q('BA102_Q013', 'Mô hình phân tích PESTEL dùng để nghiên cứu môi trường nào của doanh nghiệp?', 'MEDIUM', ['Môi trường nội bộ công ty', 'Môi trường vĩ mô (Chính trị, Kinh tế, Xã hội, Công nghệ, Môi trường tự nhiên, Pháp lý)', 'Môi trường ngành trực tiếp', 'Môi trường văn hóa gia đình'], 1, 'CLO2'),
  q('BA102_Q014', 'Mô hình 5 lực lượng cạnh tranh (Five Forces) của Michael Porter dùng để phân tích môi trường nào?', 'MEDIUM', ['Môi trường kinh tế vĩ mô toàn cầu', 'Môi trường ngành / vi mô (Đối thủ hiện tại, Khách hàng, Nhà cung cấp, Đối thủ tiềm ẩn, Sản phẩm thay thế)', 'Môi trường văn hóa tổ chức', 'Hệ thống công nghệ thông tin'], 1, 'CLO2'),
  q('BA102_Q015', 'Trường phái quản trị theo tình huống (Contingency Approach) khẳng định chân lý quản trị nào?', 'MEDIUM', ['Có một phương pháp quản trị duy nhất đúng áp dụng cho mọi doanh nghiệp', '"Tất cả phụ thuộc vào hoàn cảnh" - Không có phương pháp vạn năng, phương pháp quản trị phù hợp tùy thuộc vào từng tình huống cụ thể', 'Chỉ áp dụng các công thức toán học', 'Bỏ qua các nguyên tắc quản trị'], 1, 'CLO2'),
  q('BA102_Q016', 'Cách tiếp cận hệ thống (Systems Approach) xem xét tổ chức doanh nghiệp như thế nào?', 'MEDIUM', ['Một cỗ máy cơ học tách biệt', 'Một hệ thống mở (Open System) bao gồm các bộ phận có mối quan hệ tương tác hữu cơ với nhau và liên tục trao đổi nguồn lực với môi trường bên ngoài', 'Một tập hợp các cá nhân làm việc độc lập', 'Một bản đồ kế toán'], 1, 'CLO2'),
  q('BA102_Q017', 'Văn hóa tổ chức (Organizational Culture) được hiểu là:', 'MEDIUM', ['Các buổi liên hoan văn nghệ hàng năm', 'Hệ thống các giá trị, chuẩn mực, niềm tin và thói quen được các thành viên trong tổ chức cùng chia sẻ và định hướng hành vi của họ', 'Quy định nội quy lao động bằng văn bản', 'Màu sắc đồng phục công ty'], 1, 'CLO2'),
  q('BA102_Q018', 'Nguyên tắc "Thống nhất chỉ huy" (Unity of Command) của Henri Fayol quy định rằng:', 'MEDIUM', ['Giám đốc quyết định mọi việc', 'Mỗi nhân viên chỉ nên nhận mệnh lệnh và báo cáo trực tiếp cho duy nhất một cấp trên trực tiếp', 'Các phòng ban phải có quyền lực ngang nhau', 'Không được ủy quyền'], 1, 'CLO2'),
  q('BA102_Q019', 'Đạo đức kinh doanh và Trách nhiệm xã hội của doanh nghiệp (CSR - Corporate Social Responsibility) đòi hỏi doanh nghiệp phải:', 'MEDIUM', ['Chỉ tối đa hóa lợi nhuận cho cổ đông bất chấp mọi phương thức', 'Không chỉ tạo ra lợi nhuận hợp pháp mà còn phải có trách nhiệm đạo đức, bảo vệ môi trường và đóng góp tích cực cho sự phát triển của cộng đồng xã hội', 'Đóng cửa các nhà máy gây ồn', 'Tặng toàn bộ sản phẩm miễn phí'], 1, 'CLO2'),
  q('BA102_Q020', 'Nhà quản trị cấp cơ sở (First-line Managers / Giám sát viên / Tổ trưởng) cần thành thạo nhất kỹ năng nào?', 'MEDIUM', ['Kỹ năng tư duy chiến lược', 'Kỹ năng chuyên môn / kỹ thuật (Technical skills) để hướng dẫn, giám sát trực tiếp thao tác công việc của công nhân', 'Kỹ năng đàm phán hợp đồng triệu đô', 'Kỹ năng phân tích tài chính vĩ mô'], 1, 'CLO2'),
  q('BA102_Q021', 'Môi trường tác nghiệp (Môi trường vi mô) khác với Môi trường vĩ mô ở điểm cốt lõi nào?', 'MEDIUM', ['Không có sự khác nhau', 'Môi trường tác nghiệp ảnh hưởng trực tiếp và có tính tương tác qua lại 2 chiều với doanh nghiệp, trong khi môi trường vĩ mô tác động một chiều trên diện rộng', 'Môi trường tác nghiệp chỉ tồn tại ở nước ngoài', 'Môi trường vĩ mô dễ kiểm soát hơn'], 1, 'CLO2'),
  q('BA102_Q022', 'Rào cản gia nhập ngành (Barriers to Entry) cao trong một ngành sản xuất sẽ mang lại hệ quả gì?', 'MEDIUM', ['Làm giảm lợi nhuận của các hãng đang có', 'Bảo vệ các doanh nghiệp hiện tại khỏi sự cạnh tranh của các đối thủ tiềm ẩn mới, giúp duy trì mức lợi nhuận cao', 'Thu hút thêm hàng ngàn doanh nghiệp mới', 'Làm giảm giá bán sản phẩm'], 1, 'CLO2'),
  q('BA102_Q023', 'Quyền lực đàm phán của nhà cung cấp (Bargaining Power of Suppliers) sẽ tăng cao khi nào?', 'MEDIUM', ['Có rất nhiều nhà cung cấp nhỏ lẻ trên thị trường', 'Sản phẩm đầu vào có tính độc quyền, khan hiếm hoặc chi phí chuyển đổi nhà cung cấp (Switching Costs) của doanh nghiệp quá cao', 'Doanh nghiệp mua hàng với số lượng khổng lồ', 'Hàng hóa đầu vào là phổ thông'], 1, 'CLO2'),
  q('BA102_Q024', 'Quyền lực đàm phán của người mua / khách hàng sẽ tăng lên khi nào?', 'MEDIUM', ['Khách hàng mua với khối lượng lớn, sản phẩm chuẩn hóa ít khác biệt và chi phí chuyển đổi sang nhãn hiệu khác thấp', 'Chỉ có duy nhất một người bán', 'Sản phẩm không có hàng thay thế', 'Khách hàng không có thông tin về giá'], 0, 'CLO2'),
  q('BA102_Q025', 'Kết luận then chốt từ các thí nghiệm Hawthorne của Elton Mayo là gì?', 'MEDIUM', ['Tiền bạc là yếu tố duy nhất thúc đẩy người lao động', 'Năng suất lao động không chỉ phụ thuộc vào điều kiện vật chất kỹ thuật mà còn chịu ảnh hưởng sâu sắc bởi các yếu tố tâm lý xã hội và sự quan tâm của cấp trên', 'Ánh sáng càng chói thì làm việc càng nhanh', 'Cần loại bỏ mọi nhóm không chính thức'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA102_Q026', 'Khi áp dụng mô hình PESTEL, việc Chính phủ ban hành Luật Bảo vệ Dữ liệu Cá nhân và siết chặt quy định an toàn mạng thuộc về yếu tố nào?', 'HARD', ['Yếu tố kinh tế (Economic)', 'Yếu tố Pháp lý (Legal) và Công nghệ (Technological)', 'Yếu tố tự nhiên (Environmental)', 'Yếu tố văn hóa xã hội'], 1, 'CLO3'),
  q('BA102_Q027', 'Một nhà máy sản xuất thép xả chất thải chưa qua xử lý ra sông nhằm tiết kiệm chi phí xử lý. Hành vi này thể hiện cách tiếp cận trách nhiệm xã hội nào?', 'HARD', ['Cách tiếp cận đón đầu (Proactive)', 'Cách tiếp cận cản trở / chống đối (Obstructionist stance) - vi phạm pháp luật và thiếu đạo đức kinh doanh', 'Cách tiếp cận hòa giải (Accommodative)', 'Cách tiếp cận phòng thủ (Defensive)'], 1, 'CLO3'),
  q('BA102_Q028', 'Khi phân tích một công ty xe ôm truyền thống trước sự xuất hiện của Grab và Be, loại áp lực cạnh tranh trực tiếp mạnh nhất theo mô hình Porter là:', 'HARD', ['Quyền lực nhà cung cấp xăng dầu', 'Đe dọa từ sản phẩm/dịch vụ thay thế ứng dụng công nghệ và sự gia nhập của đối thủ mới với mô hình kinh tế nền tảng số', 'Quyền lực của cơ quan thuế', 'Cạnh tranh nội bộ người lái xe'], 1, 'CLO3'),
  q('BA102_Q029', 'Trong bối cảnh dịch bệnh bất ngờ bùng phát, một Tổng giám đốc quyết định chuyển đổi toàn bộ mô hình làm việc từ trực tiếp sang làm việc từ xa (Remote Work). Nhà quản trị này đang thể hiện nổi bật kỹ năng nào?', 'HARD', ['Kỹ năng sửa chữa máy tính', 'Kỹ năng tư duy thích ứng chiến lược và giải quyết tình huống khủng hoảng', 'Kỹ năng kiểm tra sổ sách', 'Kỹ năng thuyết phục khách hàng'], 1, 'CLO3'),
  q('BA102_Q030', 'Một trưởng phòng Marketing tự ý quyết định chính sách chiết khấu 30% cho khách hàng VIP mà không cần xin ý kiến Giám đốc, đúng với quy chế phân quyền đã ban hành. Đây là minh chứng của nguyên tắc quản trị nào?', 'HARD', ['Mất kiểm soát tổ chức', 'Nguyên tắc ủy quyền và trao quyền (Empowerment / Delegation of Authority)', 'Vi phạm kỷ luật lao động', 'Thiếu trách nhiệm giải trình'], 1, 'CLO3'),
  q('BA102_Q031', 'Hiện tượng "Groupthink" (Tư duy tập thể) trong văn hóa tổ chức gây ra rủi ro nguy hiểm nào cho quá trình ra quyết định?', 'HARD', ['Mọi người tranh cãi không dứt', 'Các thành viên trong nhóm ngại nêu ý kiến phản biện vì sợ phá vỡ sự đồng thuận, dẫn đến việc thông qua các quyết định sai lầm một cách mù quáng', 'Tăng thời gian họp nhóm', 'Làm lộ bí mật kinh doanh'], 1, 'CLO3'),
  q('BA102_Q032', 'Khi một công ty bán lẻ truyền thống nhận thấy xu hướng người tiêu dùng chuyển sang mua sắm trên TikTok Shop và Shopee, công ty đang đứng trước yếu tố môi trường nào?', 'HARD', ['Biến động tỷ giá hối đoái', 'Sự biến đổi đồng thời của môi trường Công nghệ (Thương mại điện tử) và Xã hội (Thói quen tiêu dùng số)', 'Sự thay đổi của luật doanh nghiệp', 'Thời tiết thay đổi'], 1, 'CLO3'),
  q('BA102_Q033', 'Việc Tesla công khai miễn phí các bằng sáng chế xe điện nhằm thúc đẩy cả ngành công nghiệp phát triển trạm sạc là chiến lược quản trị môi trường theo hướng:', 'HARD', ['Bị động chấp nhận', 'Chủ động định hình lại cấu trúc ngành và xây dựng hệ sinh thái liên minh chiến lược (Proactive Ecosystem Shaping)', 'Chống đối chính phủ', 'Rút lui khỏi ngành'], 1, 'CLO3'),
  q('BA102_Q034', 'Một quản đốc xưởng may áp dụng phương pháp nghiên cứu thời gian và chuyển động (Time and Motion Study) để chuẩn hóa từng thao tác của công nhân nhằm tăng năng suất. Quản đốc này đang vận dụng tư tưởng của ai?', 'HARD', ['Elton Mayo', 'Frederick Winslow Taylor và vợ chồng Frank & Lillian Gilbreth', 'Peter Drucker', 'Henri Fayol'], 1, 'CLO3'),
  q('BA102_Q035', 'Khi một nhà quản lý thường xuyên mời các chuyên gia bên ngoài và khách hàng tham gia góp ý xây dựng quy trình phục vụ mới, nhà quản lý đang áp dụng cách tiếp cận:', 'HARD', ['Mô hình hệ thống đóng', 'Mô hình hệ thống mở (Open System) và đổi mới mở (Open Innovation)', 'Mô hình mệnh lệnh quan liêu', 'Trường phái quản trị bàn giấy'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA102_Q036', 'Khái niệm "Tổ chức học tập" (Learning Organization) do Peter Senge đề xuất trong tác phẩm "Kỷ luật thứ năm" nhấn mạnh vào năng lực nào?', 'EXPERT', ['Bắt buộc nhân viên đi học cao học', 'Khả năng liên tục thích ứng, thay đổi mô hình tư duy (Mental models), chia sẻ tầm nhìn và cùng học tập để thích nghi vượt trội với môi trường biến động', 'Đọc nhiều sách nhất', 'Mua nhiều phần mềm học tập'], 1, 'CLO4'),
  q('BA102_Q037', 'Lý thuyết Vị thế nguồn lực (Resource-Based View - RBV) của Barney khẳng định lợi thế cạnh tranh bền vững của doanh nghiệp bắt nguồn từ các nguồn lực thỏa mãn tiêu chuẩn VRIO, gồm:', 'EXPERT', ['Vốn, Rủi ro, Lãi suất, Cơ hội', 'Value (Có giá trị), Rarity (Hiếm), Inimitability (Khó sao chép), Organization (Tổ chức khai thác tốt)', 'Vision, Reality, Idea, Operation', 'Vĩ mô, Rõ ràng, Ít ỏi, Ổn định'], 1, 'CLO4'),
  q('BA102_Q038', 'Mô hình Năng lực động (Dynamic Capabilities) của David Teece giải thích khả năng doanh nghiệp duy trì vị thế dẫn đầu trong môi trường biến động nhanh nhờ vào 3 năng lực:', 'EXPERT', ['Lập kế hoạch, kiểm toán, báo cáo', 'Cảm nhận cơ hội (Sensing), Nắm bắt cơ hội (Seizing) và Chuyển đổi tái cấu trúc (Transforming / Reconfiguring)', 'Cắt giảm nhân sự, hạ giá, vay vốn', 'Đăng ký bản quyền, quảng cáo, tiếp thị'], 1, 'CLO4'),
  q('BA102_Q039', 'Mô hình Quản trị Đa văn hóa của Geert Hofstede sử dụng các chiều kích nào để phân tích sự khác biệt văn hóa giữa các quốc gia khi quản lý công ty đa quốc gia?', 'EXPERT', ['Chỉ dựa vào tôn giáo', 'Khoảng cách quyền lực (PDI), Chủ nghĩa cá nhân vs Tập thể (IDV), Né tránh sự không chắc chắn (UAI), Nam tính vs Nữ tính (MAS), Định hướng dài hạn', 'Khí hậu và ngôn ngữ', 'GDP bình quân đầu người'], 1, 'CLO4'),
  q('BA102_Q040', 'Phương thức quản trị MBO (Management by Objectives - Quản trị theo mục tiêu) do Peter Drucker khởi xướng có đặc trưng cốt lõi nào?', 'EXPERT', ['Cấp trên tự đề ra mục tiêu và áp đặt xuống cấp dưới', 'Mục tiêu được xây dựng dựa trên sự bàn bạc, thống nhất chung giữa cấp trên và cấp dưới, cấp dưới được tự chủ thực hiện và tự đánh giá kết quả đạt được', 'Chỉ quan tâm tới quá trình không cần kết quả', 'Loại bỏ hoàn toàn chức năng kiểm tra'], 1, 'CLO4')
];

// ĐỀ GỐC 2 (40 câu): Chức năng Hoạch định, Ra quyết định quản trị & Chức năng Tổ chức
const root2 = [
  // Nhận biết (10 câu)
  q('BA102_Q041', 'Chức năng Hoạch định (Planning) trong quản trị nhằm trả lời câu hỏi cốt lõi nào?', 'EASY', ['Ai sẽ làm việc này?', 'Tổ chức muốn đi tới đâu và làm thế nào để đi tới đó?', 'Chi phí hết bao nhiêu tiền?', 'Tại sao công việc bị chậm?'], 1, 'CLO1'),
  q('BA102_Q042', 'Nguyên tắc thiết lập mục tiêu SMART đòi hỏi mục tiêu phải thỏa mãn 5 tiêu chí nào?', 'EASY', ['Thông minh, Nhanh nhẹn, Chính xác, Thực tế, Tiết kiệm', 'Specific (Cụ thể), Measurable (Đo lường được), Achievable (Khả thi), Relevant (Thích hợp), Time-bound (Có thời hạn)', 'Simple, Money, Action, Right, True', 'Chiến lược, Tiếp thị, Quản trị, Rủi ro, Thời gian'], 1, 'CLO1'),
  q('BA102_Q043', 'Ma trận SWOT là công cụ phân tích chiến lược kết hợp giữa các yếu tố nào?', 'EASY', ['Doanh thu và Chi phí', 'Strengths (Điểm mạnh), Weaknesses (Điểm yếu) bên trong với Opportunities (Cơ hội), Threats (Thách thức) bên ngoài', 'Lao động và Máy móc', 'Kế hoạch và Thực hiện'], 1, 'CLO1'),
  q('BA102_Q044', 'Theo Michael Porter, ba chiến lược cạnh tranh tổng quát (Generic Strategies) ở cấp đơn vị kinh doanh gồm:', 'EASY', ['Chiến lược ngắn hạn, trung hạn, dài hạn', 'Chiến lược dẫn đầu về chi phí thấp (Cost Leadership), Chiến lược khác biệt hóa (Differentiation), Chiến lược tập trung (Focus)', 'Chiến lược nội địa, xuất khẩu, toàn cầu', 'Chiến lược giá cao, giá rẻ, khuyến mãi'], 1, 'CLO1'),
  q('BA102_Q045', 'Ma trận BCG (Boston Consulting Group) phân loại các đơn vị kinh doanh chiến lược (SBU) dựa trên 2 trục nào?', 'EASY', ['Lợi nhuận và Doanh thu', 'Tốc độ tăng trưởng của thị trường (Market Growth Rate) và Thị phần tương đối (Relative Market Share)', 'Số lượng nhân viên và Tuổi đời công ty', 'Chi phí cố định và Chi phí biến đổi'], 1, 'CLO1'),
  q('BA102_Q046', 'Trong ma trận BCG, ô "Ngôi sao" (Stars) đại diện cho các đơn vị kinh doanh có đặc điểm gì?', 'EASY', ['Thị phần thấp, tăng trưởng chậm', 'Thị phần tương đối cao trong một thị trường có tốc độ tăng trưởng cao', 'Thị phần cao trong thị trường bão hòa', 'Thị phần thấp và thua lỗ'], 1, 'CLO1'),
  q('BA102_Q047', 'Chức năng Tổ chức (Organizing) bao gồm các hoạt động chính nào?', 'EASY', ['Lập kế hoạch doanh số', 'Xác định các công việc cần làm, phân công ai làm việc gì, phân chia nhóm công việc thành các phòng ban và thiết lập cơ chế phối hợp, quyền hạn', 'Động viên nhân viên làm việc thêm giờ', 'Kiểm tra tài khoản ngân hàng'], 1, 'CLO1'),
  q('BA102_Q048', 'Khái niệm "Tầm hạn quản trị" (Span of Control) biểu thị điều gì?', 'EASY', ['Khoảng cách địa lý giữa các chi nhánh', 'Số lượng nhân viên cấp dưới trực tiếp báo cáo và chịu sự giám sát hiệu quả của một nhà quản trị', 'Thời gian làm việc của một giám đốc', 'Quy mô vốn của công ty'], 1, 'CLO1'),
  q('BA102_Q049', 'Cơ cấu tổ chức kiểu Ma trận (Matrix Structure) có đặc điểm nổi bật nào?', 'EASY', ['Không có phòng ban', 'Nhân viên báo cáo đồng thời cho hai người quản lý trực tiếp: Người quản lý chức năng và Người quản lý dự án / sản phẩm', 'Chỉ có 1 cấp quản lý duy nhất', 'Hoàn toàn phi tập trung'], 1, 'CLO1'),
  q('BA102_Q050', 'Khái niệm "Ủy quyền" (Delegation) trong quản trị được hiểu là quá trình:', 'EASY', ['Đùn đẩy trách nhiệm cho cấp dưới', 'Cấp trên giao phó quyền hạn và trách nhiệm thực hiện một phần công việc cụ thể cho cấp dưới kèm theo quyền sử dụng nguồn lực cần thiết', 'Tước bỏ quyền hạn của nhân viên', 'Thuê ngoài dịch vụ'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA102_Q051', 'Trong ma trận BCG, các đơn vị kinh doanh ở ô "Bò sữa" (Cash Cows) nên được quản lý theo chiến lược nào?', 'MEDIUM', ['Đầu tư mở rộng mạnh mẽ', 'Khai thác tối đa dòng tiền mặt dồi dào thu được để tái đầu tư sang các ô Ngôi sao hoặc Dấu hỏi', 'Bán tháo ngay lập tức', 'Tăng giá bán gấp đôi'], 1, 'CLO2'),
  q('BA102_Q052', 'Ô "Dấu hỏi" (Question Marks) trong ma trận BCG đòi hỏi nhà quản trị phải đưa ra quyết định chiến lược nào?', 'MEDIUM', ['Bỏ mặc không theo dõi', 'Cân nhắc kỹ lưỡng: Hoặc đầu tư nguồn lực lớn để biến thành Ngôi sao, hoặc thoái vốn loại bỏ nếu tiềm năng không rõ ràng', 'Giữ nguyên không thay đổi', 'Biến ngay thành Bò sữa'], 1, 'CLO2'),
  q('BA102_Q053', 'Quy trình ra quyết định quản trị hợp lý bao gồm các bước theo trình tự chuẩn nào?', 'MEDIUM', ['Chọn phương án -> Làm thử -> Đánh giá', 'Xác định vấn đề -> Xác định các tiêu chí quyết định -> Phân bổ trọng số -> Xây dựng các phương án -> Đánh giá các phương án -> Lựa chọn phương án tối ưu -> Thực hiện và Đánh giá hiệu quả', 'Họp bàn -> Biểu quyết -> Thực hiện', 'Lấy ý kiến đám đông'], 1, 'CLO2'),
  q('BA102_Q054', 'Mô hình ra quyết định duy lý có giới hạn (Bounded Rationality của Herbert Simon) chỉ ra rằng nhà quản trị thường đưa ra quyết định ở mức độ nào?', 'MEDIUM', ['Quyết định tối ưu tuyệt đối 100%', 'Quyết định "đạt yêu cầu / thỏa đáng" (Satisficing) do bị giới hạn về thông tin, thời gian và năng lực xử lý nhận thức', 'Quyết định hoàn toàn ngẫu nhiên', 'Luôn luôn sai lầm'], 1, 'CLO2'),
  q('BA102_Q055', 'Ưu điểm lớn nhất của Cơ cấu tổ chức theo Chức năng (Functional Structure) là gì?', 'MEDIUM', ['Dễ phối hợp giữa các dự án', 'Chuyên môn hóa cao, tiết kiệm chi phí nhờ tính kinh tế quy mô trong từng phòng ban chức năng (Tài chính, Marketing, R&D)', 'Phản ứng nhanh với thay đổi thị trường địa phương', 'Không có xung đột giữa các phòng'], 1, 'CLO2'),
  q('BA102_Q056', 'Nhược điểm lớn nhất của Cơ cấu tổ chức theo Chức năng là:', 'MEDIUM', ['Tốn quá nhiều chi phí quản lý', 'Dễ sinh ra hiện tượng "cục bộ địa phương" (Silo effect), thiếu sự phối hợp ăn ý giữa các phòng ban chức năng và khó quy trách nhiệm kết quả cuối cùng', 'Nhân viên không có chuyên môn', 'Không có phân cấp'], 1, 'CLO2'),
  q('BA102_Q057', 'Cơ cấu tổ chức theo Sản phẩm hoặc Địa lý (Divisional Structure) phù hợp nhất với loại doanh nghiệp nào?', 'MEDIUM', ['Doanh nghiệp khởi nghiệp 3 người', 'Doanh nghiệp quy mô lớn, sản xuất kinh doanh đa dạng hóa nhiều dòng sản phẩm hoặc hoạt động trên nhiều vùng địa lý khác biệt', 'Doanh nghiệp chỉ sản xuất 1 loại ốc vít', 'Cơ quan nhà nước thuần túy'], 1, 'CLO2'),
  q('BA102_Q058', 'Cơ cấu tổ chức "Nằm ngang / Phẳng" (Flat Structure) với tầm hạn quản trị rộng có đặc điểm gì?', 'MEDIUM', ['Có rất nhiều cấp quản lý trung gian', 'Ít tầng nấc trung gian, thông tin truyền đạt nhanh, chi phí quản lý giảm và trao quyền nhiều hơn cho nhân viên', 'Kiểm soát rất chặt chẽ từng nhân viên', 'Nhân viên không được tự chủ'], 1, 'CLO2'),
  q('BA102_Q059', 'Tập quyền (Centralization) khác với Phân quyền (Decentralization) ở điểm mấu chốt nào?', 'MEDIUM', ['Tập quyền cho phép nhân viên tự quyết', 'Tập quyền là quyền hạn ra quyết định tập trung chủ yếu ở cấp quản trị cao nhất; Phân quyền là quyền ra quyết định được san sẻ xuống các cấp quản trị thấp hơn', 'Tập quyền tốn ít nhân lực hơn', 'Phân quyền chỉ áp dụng cho quân đội'], 1, 'CLO2'),
  q('BA102_Q060', 'Nguyên tắc "Tương xứng giữa Quyền hạn và Trách nhiệm" (Parity of Authority and Responsibility) đòi hỏi:', 'MEDIUM', ['Quyền hạn phải lớn hơn nhiều trách nhiệm', 'Nhà quản trị khi giao trách nhiệm thực hiện công việc cho cấp dưới thì bắt buộc phải trao cho họ quyền hạn tương ứng đủ để hoàn thành trách nhiệm đó', 'Trách nhiệm luôn thuộc về cấp dưới', 'Không cần trao quyền hạn'], 1, 'CLO2'),
  q('BA102_Q061', 'Kế hoạch tác nghiệp (Operational Planning) khác Kế hoạch chiến lược (Strategic Planning) ở điểm nào?', 'MEDIUM', ['Kế hoạch tác nghiệp do Hội đồng quản trị lập', 'Kế hoạch tác nghiệp mang tính ngắn hạn (dưới 1 năm), chi tiết hóa việc thực hiện mục tiêu tại các bộ phận cụ thể; Kế hoạch chiến lược mang tính dài hạn (3-5 năm) cho toàn bộ tổ chức', 'Kế hoạch tác nghiệp không có mục tiêu', 'Kế hoạch chiến lược do tổ trưởng lập'], 1, 'CLO2'),
  q('BA102_Q062', 'Chiến lược Đại dương xanh (Blue Ocean Strategy) hướng doanh nghiệp tới điều gì?', 'MEDIUM', ['Cạnh tranh khốc liệt bằng cách hạ giá trong thị trường hiện tại (Đại dương đỏ)', 'Tạo ra một không gian thị trường hoàn toàn mới chưa có đối thủ cạnh tranh, vô hiệu hóa cạnh tranh bằng việc vừa tạo ra sự khác biệt vừa tiết kiệm chi phí', 'Đầu tư vào đánh bắt hải sản', 'Bán lại công ty'], 1, 'CLO2'),
  q('BA102_Q063', 'Trong phân tích SWOT, chiến lược S-O (Strengths - Opportunities) là chiến lược:', 'MEDIUM', ['Khắc phục điểm yếu để đón đầu cơ hội', 'Tận dụng tối đa các điểm mạnh nội bộ để nắm bắt các cơ hội lớn từ môi trường bên ngoài', 'Sử dụng điểm mạnh để phòng thủ thách thức', 'Thu hẹp quy mô hoạt động'], 1, 'CLO2'),
  q('BA102_Q064', 'Hiện tượng "Leo thang cam kết" (Escalation of Commitment) trong ra quyết định là lỗi tâm lý nào?', 'MEDIUM', ['Nhận thức vấn đề quá nhanh', 'Tiếp tục rót thêm nguồn lực và thời gian vào một quyết định sai lầm rõ ràng chỉ vì trước đó đã đầu tư quá nhiều công sức/tiền bạc (bẫy chi phí chìm)', 'Đổi ý liên tục', 'Ủy quyền quá mức'], 1, 'CLO2'),
  q('BA102_Q065', 'Kỹ thuật Động não (Brainstorming) khi ra quyết định nhóm có nguyên tắc vàng nào?', 'MEDIUM', ['Chỉ trích ngay các ý tưởng phi thực tế', 'Nghiêm cấm mọi sự chỉ trích, phán xét ý tưởng trong giai đoạn đầu nhằm khuyến khích tối đa số lượng ý tưởng mới lạ, độc đáo', 'Chỉ người trưởng nhóm được nói', 'Bỏ phiếu ngay từ phút đầu'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA102_Q066', 'Công ty Apple duy trì mức giá bán iPhone rất cao nhưng người dùng vẫn sẵn sàng xếp hàng mua nhờ thiết kế đẳng cấp, hệ điều hành iOS mượt mà và hệ sinh thái khép kín. Apple đang áp dụng chiến lược nào?', 'HARD', ['Chiến lược dẫn đầu về chi phí', 'Chiến lược Khác biệt hóa (Differentiation Strategy)', 'Chiến lược giá rẻ', 'Chiến lược cắt giảm chi phí'], 1, 'CLO3'),
  q('BA102_Q067', 'Tập đoàn Vingroup thành lập các công ty con phụ trách từng mảng: Vinhomes (Bất động sản), Vinmec (Y tế), VinUni (Giáo dục), VinFast (Xe điện). Đây là ví dụ của mô hình tổ chức nào?', 'HARD', ['Cơ cấu trực tuyến thuần túy', 'Cơ cấu tổ chức theo Đơn vị kinh doanh chiến lược / Phân nhánh sản phẩm (Divisional / SBU Structure)', 'Cơ cấu ma trận lỏng lẻo', 'Cơ cấu giản đơn'], 1, 'CLO3'),
  q('BA102_Q068', 'Một công ty sản xuất đồ nội thất phát hiện một dây chuyền làm việc có 1 quản đốc giám sát tới 60 công nhân trực tiếp có tay nghề thấp và công việc phức tạp, dẫn tới hàng lỗi liên tục. Giải pháp tái cơ cấu là:', 'HARD', ['Tăng lương cho quản đốc', 'Thu hẹp tầm hạn quản trị (Narrow the span of control) bằng cách bổ sung thêm các tổ trưởng quản lý nhóm nhỏ 10-15 người để kiểm soát chất lượng chặt chẽ hơn', 'Mở rộng tầm hạn lên 100 người', 'Bãi bỏ chức vụ quản đốc'], 1, 'CLO3'),
  q('BA102_Q069', 'Khi một công ty triển khai dự án ERP phức tạp, ban lãnh đạo yêu cầu một chuyên viên IT vừa nhận chỉ đạo chuyên môn từ Trưởng phòng IT vừa chịu sự phân công công việc hàng ngày của Giám đốc dự án ERP. Đây là ứng dụng của:', 'HARD', ['Cơ cấu chức năng cứng', 'Cơ cấu Ma trận (Matrix Organization Structure)', 'Cơ cấu hình tháp', 'Cơ cấu mạng lưới ảo'], 1, 'CLO3'),
  q('BA102_Q070', 'Một doanh nghiệp vận chuyển hành khách muốn ứng phó với tình hình giá nhiên liệu xăng dầu biến động bất thường trong tương lai. Kỹ thuật hoạch định phù hợp nhất là:', 'HARD', ['Kế hoạch duy nhất cố định', 'Hoạch định theo kịch bản (Scenario Planning: Kịch bản giá dầu thấp, trung bình, khủng hoảng tăng vọt) kèm phương án hành động tương ứng', 'Ngừng mua xăng', 'Chỉ lập kế hoạch theo ngày'], 1, 'CLO3'),
  q('BA102_Q071', 'Khi một công ty bán lẻ áp dụng chính sách cho phép nhân viên thu ngân tự quyết định hoàn tiền hoặc đổi trả hàng cho khách dưới 500.000 đồng mà không cần chữ ký của Cửa hàng trưởng. Đây là minh chứng của:', 'HARD', ['Mất kiểm soát ngân quỹ', 'Trao quyền (Empowerment) cho nhân viên tuyến đầu để nâng cao chất lượng dịch vụ khách hàng tức thì', 'Thiếu quy trình kế toán', 'Gian lận tài chính'], 1, 'CLO3'),
  q('BA102_Q072', 'Một nhà sản xuất bánh kẹo sở hữu một nhãn hàng kẹo truyền thống có thị phần rất cao nhưng thị trường kẹo này hầu như không còn tăng trưởng (tăng trưởng < 1%). Theo BCG, nhãn hàng này là:', 'HARD', ['Ngôi sao (Star)', 'Bò sữa (Cash Cow) - cần tối ưu hóa chi phí sản xuất và thu tiền mặt phục vụ phát triển sản phẩm mới', 'Dấu hỏi (Question Mark)', 'Con chó (Dog) cần đóng cửa ngay'], 1, 'CLO3'),
  q('BA102_Q073', 'Để ra quyết định lựa chọn địa điểm mở nhà máy sản xuất linh kiện, Hội đồng quản trị sử dụng phương pháp Bảng ma trận quyết định có trọng số (Weighted Decision Matrix). Bước tính điểm cốt lõi là:', 'HARD', ['Lấy tổng chi phí', 'Nhân điểm đánh giá của từng địa điểm với trọng số tầm quan trọng của từng tiêu chí rồi cộng tổng điểm để so sánh', 'Bốc thăm ngẫu nhiên', 'Chọn địa điểm của người có chức to nhất'], 1, 'CLO3'),
  q('BA102_Q074', 'Trong ma trận SWOT, khi công ty nhận diện có Điểm yếu nội bộ (W) nhưng thị trường lại có Thách thức lớn (T), chiến lược W-T phù hợp nhất là:', 'HARD', ['Tấn công mở rộng thị trường', 'Chiến lược phòng thủ, giảm thiểu rủi ro, tái cấu trúc hoặc thu hẹp hoạt động kinh doanh để tồn tại', 'Vay nợ tối đa để đầu tư', 'Tăng giá bán sản phẩm'], 1, 'CLO3'),
  q('BA102_Q075', 'Một doanh nghiệp chuyển từ cơ cấu nhiều tầng nấc (Tall Structure) sang cơ cấu phẳng (Flat Structure) bằng cách cắt giảm các cấp quản lý trung gian. Lợi ích trực tiếp đạt được là:', 'HARD', ['Tăng thời gian phê duyệt', 'Cắt giảm đáng kể chi phí tiền lương quản lý và rút ngắn độ trễ truyền đạt thông tin từ cấp cao xuống nhân viên thừa hành', 'Nhân viên không phải làm việc', 'Quyền lực tập trung hơn'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA102_Q076', 'Cấu trúc Tổ chức Mạng lưới ảo (Virtual / Network Organization) được nhiều tập đoàn công nghệ (như Nike, Apple) áp dụng thành công dựa trên nguyên lý cốt lõi nào?', 'EXPERT', ['Tự làm từ A đến Z mọi khâu', 'Tập trung nguồn lực tinh hoa vào các năng lực cốt lõi (Core Competencies như Thiết kế, R&D, Thương hiệu) và thuê ngoài (Outsourcing) toàn bộ các hoạt động thứ cấp như gia công sản xuất, logistics', 'Không cần nhân viên kế toán', 'Không có pháp nhân'], 1, 'CLO4'),
  q('BA102_Q077', 'Phương pháp Delphi trong kỹ thuật ra quyết định nhóm và dự báo chiến lược có đặc điểm nổi bật là:', 'EXPERT', ['Tranh luận trực tiếp mặt đối mặt', 'Thu thập ý kiến độc lập của các chuyên gia ẩn danh qua nhiều vòng bảng hỏi kèm báo cáo phản hồi tổng hợp, tránh được tác động áp đảo của các nhân vật quyền lực', 'Bỏ phiếu kín 1 vòng duy nhất', 'Dùng máy tính tự sinh quyết định'], 1, 'CLO4'),
  q('BA102_Q078', 'Mô hình 7S của McKinsey đánh giá sự gắn kết toàn diện trong tổ chức gồm 7 yếu tố nào?', 'EXPERT', ['Strategy, Structure, Systems, Shared Values, Style, Staff, Skills', 'Speed, Sale, Social, Standard, Safety, Space, Supply', 'Software, Server, Security, Storage, Switch, Screen, Script', '7 phòng ban trong công ty'], 0, 'CLO4'),
  q('BA102_Q079', 'Học thuyết Quản trị nghịch đảo (Ambidextrous Organization - Tổ chức thuận cả hai tay) đòi hỏi doanh nghiệp phải cân bằng được giữa hai nhiệm vụ:', 'EXPERT', ['Bán hàng và thu hồi nợ', 'Khai thác tối đa hiệu quả các hoạt động kinh doanh hiện tại (Exploitation) ĐỒNG THỜI khám phá, thử nghiệm các cơ hội đổi mới sáng tạo tương lai (Exploration)', 'Chi tiêu nội địa và quốc tế', 'Chăm sóc khách quen và khách lạ'], 1, 'CLO4'),
  q('BA102_Q080', 'Mô hình Vòng lặp OODA (Observe - Orient - Decide - Act) trong việc ra quyết định chiến lược tốc độ cao nhấn mạnh vào yếu tố cạnh tranh nào?', 'EXPERT', ['Tiết kiệm chi phí', 'Tốc độ quay vòng chu kỳ ra quyết định và hành động nhanh hơn đối thủ để tạo bất ngờ và áp đảo trên thị trường biến động', 'Chờ đợi đối thủ hành động trước', 'Sử dụng văn bản giấy'], 1, 'CLO4')
];

// ĐỀ GỐC 3 (40 câu): Chức năng Lãnh đạo, Động viên nhân viên, Truyền thông & Chức năng Kiểm tra
const root3 = [
  // Nhận biết (10 câu)
  q('BA102_Q081', 'Sự khác biệt căn bản giữa khái niệm "Lãnh đạo" (Leading) và "Quản lý" (Managing) là gì?', 'EASY', ['Không có sự khác biệt', 'Quản lý nhấn mạnh vào việc duy trì trật tự, tính kỷ luật và hiệu quả thực thi quy trình; Lãnh đạo nhấn mạnh vào việc truyền cảm hứng, định hướng tầm nhìn và dẫn dắt sự thay đổi', 'Lãnh đạo chỉ dành cho chủ tịch', 'Quản lý không có quyền hạn'], 1, 'CLO1'),
  q('BA102_Q082', 'Ba phong cách lãnh đạo kinh điển theo nghiên cứu của Kurt Lewin là:', 'EASY', ['Hiền lành, Dữ dằn, Trung lập', 'Phong cách độc đoán (Autocratic), Phong cách dân chủ (Democratic), Phong cách tự do (Laissez-faire)', 'Lãnh đạo bằng tiền, bằng tình cảm, bằng quyền lực', 'Ngắn hạn, Trung hạn, Dài hạn'], 1, 'CLO1'),
  q('BA102_Q083', 'Tháp nhu cầu của Abraham Maslow sắp xếp 5 bậc nhu cầu từ thấp lên cao theo thứ tự nào?', 'EASY', ['Xã hội -> Sinh học -> Tự khẳng định -> An toàn -> Được tôn trọng', 'Nhu cầu sinh học (Sinh lý) -> Nhu cầu an toàn -> Nhu cầu xã hội (Gắn kết) -> Nhu cầu được tôn trọng -> Nhu cầu tự khẳng định mình (Self-actualization)', 'Tiền -> Nhà -> Xe -> Tình yêu -> Danh vọng', 'Ăn uống -> Ngủ nghỉ -> Làm việc -> Nghỉ ngơi'], 1, 'CLO1'),
  q('BA102_Q084', 'Thuyết Hai nhân tố của Frederick Herzberg phân chia các yếu tố tác động tới người lao động thành 2 nhóm nào?', 'EASY', ['Yếu tố trong nhà và ngoài trời', 'Yếu tố duy trì (Hygiene factors - như lương, điều kiện làm việc) và Yếu tố động viên (Motivators - như sự công nhận, cơ hội phát triển bản thân)', 'Yếu tố tinh thần và vật chất', 'Yếu tố thưởng và phạt'], 1, 'CLO1'),
  q('BA102_Q085', 'Theo Herzberg, nếu doanh nghiệp cải thiện tốt các "Yếu tố duy trì" (như tăng lương cơ bản, cải thiện phòng làm việc) thì sẽ đạt được kết quả gì?', 'EASY', ['Nhân viên sẽ có động lực cống hiến tột bậc', 'Chỉ giúp loại bỏ sự bất mãn (Không bất mãn) nhưng không trực tiếp tạo ra động lực làm việc mạnh mẽ lâu dài', 'Nhân viên sẽ làm việc suốt ngày đêm', 'Năng suất tự động tăng 200%'], 1, 'CLO1'),
  q('BA102_Q086', 'Chức năng Kiểm tra (Controlling) trong quản trị là quá trình:', 'EASY', ['Theo dõi rình rập nhân viên', 'Đo lường kết quả thực tế, so sánh với các tiêu chuẩn đã đề ra trong kế hoạch và tiến hành các hành động điều chỉnh cần thiết để đảm bảo mục tiêu được hoàn thành', 'Xử phạt nhân viên đi làm muộn', 'Đóng dấu duyệt chi'], 1, 'CLO1'),
  q('BA102_Q087', 'Bốn bước cơ bản của quy trình kiểm tra chuẩn trong quản trị diễn ra theo thứ tự:', 'EASY', ['Phạt lỗi -> Đo lường -> Báo cáo -> Khen thưởng', 'Thiết lập các tiêu chuẩn -> Đo lường kết quả hoạt động thực tế -> So sánh kết quả thực tế với tiêu chuẩn -> Thực hiện hành động điều chỉnh', 'Kiểm tra đột xuất -> Lập biên bản -> Họp xử lý -> Bãi nhiệm', 'Quan sát -> Ghi chép -> Bỏ qua -> Lưu trữ'], 1, 'CLO1'),
  q('BA102_Q088', 'Kiểm tra lường trước (Feedforward Control / Kiểm tra trước) được thực hiện vào thời điểm nào?', 'EASY', ['Sau khi sản phẩm đã bán cho khách', 'Trước khi hoạt động thực tế bắt đầu nhằm dự báo và ngăn chặn các rủi ro, sự cố có thể phát sinh (ví dụ: kiểm tra chất lượng nguyên liệu đầu vào)', 'Trong khi dây chuyền đang chạy', 'Vào cuối năm tài chính'], 1, 'CLO1'),
  q('BA102_Q089', 'Kiểm tra đồng thời (Concurrent Control) được tiến hành khi nào?', 'EASY', ['Trước khi sản xuất', 'Ngay trong quá trình hoạt động đang diễn ra (ví dụ: giám sát chất lượng trực tiếp trên dây chuyền, giám thị phòng thi)', 'Sau khi hoàn thành công việc 1 tháng', 'Khi khách hàng khiếu nại'], 1, 'CLO1'),
  q('BA102_Q090', 'Kiểm tra phản hồi (Feedback Control / Kiểm tra sau) có đặc điểm gì?', 'EASY', ['Ngăn chặn lỗi trước khi xảy ra', 'Được thực hiện sau khi hoạt động đã hoàn thành (ví dụ: báo cáo tài chính quý, khảo sát mức độ hài lòng khách hàng sau khi dùng dịch vụ)', 'Chỉ dành cho công ty phần mềm', 'Không cung cấp dữ liệu nào'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA102_Q091', 'Thuyết X và Thuyết Y của Douglas McGregor mô tả hai quan điểm trái ngược nhau về bản chất con người như thế nào?', 'MEDIUM', ['Thuyết X nói về người giàu, Thuyết Y nói về người nghèo', 'Thuyết X nhìn nhận con người lười biếng, né tránh trách nhiệm và cần kiểm soát chặt chẽ; Thuyết Y nhìn nhận con người có tinh thần trách nhiệm, yêu thích làm việc và có tiềm năng sáng tạo nếu được trao quyền', 'Thuyết X nói về phụ nữ, Thuyết Y nói về nam giới', 'Thuyết X nhấn mạnh lương, Thuyết Y nhấn mạnh thưởng'], 1, 'CLO2'),
  q('BA102_Q092', 'Thuyết Kỳ vọng (Expectancy Theory) của Victor Vroom khẳng định động lực làm việc (Motivation) là hàm số của 3 nhân tố:', 'MEDIUM', ['Tiền x Quyền lực x Danh vọng', 'Kỳ vọng (Expectancy: Nỗ lực -> Kết quả) x Tính công cụ (Instrumentality: Kết quả -> Phần thưởng) x Giá trị phần thưởng (Valence)', 'Áp lực x Thời gian x Cơ hội', 'Mục tiêu x Đào tạo x Khen thưởng'], 1, 'CLO2'),
  q('BA102_Q093', 'Theo Thuyết Công bằng (Equity Theory) của J. Stacey Adams, người lao động sẽ cảm thấy bất công và giảm động lực làm việc khi:', 'MEDIUM', ['Họ nhận được ít tiền hơn tháng trước', 'Tỷ lệ giữa Phần thưởng nhận được so với Công sức đóng góp của họ nhỏ hơn tỷ lệ đó của những người đồng nghiệp tham chiếu (Outcomes/Inputs < Outcomes_others/Inputs_others)', 'Công ty tuyển thêm người mới', 'Sếp là người nghiêm khắc'], 1, 'CLO2'),
  q('BA102_Q094', 'Lưới Lãnh đạo (Leadership Grid của Blake & Mouton) đánh giá phong cách lãnh đạo dựa trên 2 chiều kích nào?', 'MEDIUM', ['Tuổi tác và Kinh nghiệm', 'Mức độ quan tâm đến con người (Concern for People) và Mức độ quan tâm đến sản xuất / công việc (Concern for Production)', 'Tiền lương và Quyền lực', 'Tính cách hướng nội và Hướng ngoại'], 1, 'CLO2'),
  q('BA102_Q095', 'Phong cách lãnh đạo tọa độ (9,9) trong Lưới Blake & Mouton được gọi là phong cách nào?', 'MEDIUM', ['Phong cách quản trị câu lạc bộ đồng quê', 'Phong cách lãnh đạo đồng đội (Team Management - quan tâm cao độ đến cả con người lẫn công việc)', 'Phong cách quản trị suy kiệt', 'Phong cách độc đoán'], 1, 'CLO2'),
  q('BA102_Q096', 'Lãnh đạo chuyển đổi (Transformational Leadership) có đặc điểm nổi bật nào?', 'MEDIUM', ['Chỉ trao đổi sòng phẳng tiền lấy công sức', 'Truyền cảm hứng mạnh mẽ, khơi dậy tầm nhìn lớn, thay đổi nhận thức và thúc đẩy cấp dưới vượt lên trên lợi ích cá nhân vì sứ mệnh chung của tổ chức', 'Kiểm soát giờ giấc nghiêm ngặt bằng camera', 'Không bao giờ xuất hiện trước nhân viên'], 1, 'CLO2'),
  q('BA102_Q097', 'Nhiễu (Noise) trong mô hình quá trình truyền thông của tổ chức là gì?', 'MEDIUM', ['Tiếng ồn động cơ máy bay', 'Bất kỳ yếu tố nào làm sai lệch, biến dạng hoặc cản trở thông điệp truyền đi giữa người gửi (Sender) và người nhận (Receiver)', 'Lỗi mạng Internet', 'Tin nhắn quá dài'], 1, 'CLO2'),
  q('BA102_Q098', 'Phương pháp Quản trị Chất lượng Toàn diện (TQM - Total Quality Management) đặt trọng tâm vào yếu tố nào?', 'MEDIUM', ['Chỉ tập trung kiểm tra sản phẩm lỗi ở cuối dây chuyền', 'Sự tham gia của mọi thành viên trong tổ chức nhằm liên tục cải tiến chất lượng (Kaizen) hướng tới sự thỏa mãn tối đa của khách hàng', 'Mua máy móc đắt nhất thế giới', 'Sa thải công nhân làm sai'], 1, 'CLO2'),
  q('BA102_Q099', 'Chu trình Deming (Vòng tròn PDCA) trong quản lý chất lượng bao gồm 4 giai đoạn:', 'MEDIUM', ['People - Data - Control - Action', 'Plan (Lập kế hoạch) -> Do (Thực hiện) -> Check (Kiểm tra) -> Act (Hành động cải tiến)', 'Purchase - Deliver - Confirm - Accept', 'Power - Design - Create - Automate'], 1, 'CLO2'),
  q('BA102_Q100', 'Thẻ điểm cân bằng (Balanced Scorecard - BSC) theo dõi hiệu quả hoạt động của tổ chức qua 4 khía cạnh cân bằng nào?', 'MEDIUM', ['Ngắn hạn, Trung hạn, Dài hạn, Vĩnh viễn', 'Khía cạnh Tài chính, Khía cạnh Khách hàng, Khía cạnh Quy trình nội bộ, Khía cạnh Học hỏi và Phát triển', 'Doanh thu, Chi phí, Lợi nhuận, Thuế', 'Chủ tịch, Giám đốc, Trưởng phòng, Nhân viên'], 1, 'CLO2'),
  q('BA102_Q101', 'Chỉ số đo lường hiệu suất then chốt (KPI - Key Performance Indicators) giúp tổ chức:', 'MEDIUM', ['Tính tiền phạt nhân viên', 'Định lượng các mục tiêu quan trọng và theo dõi tiến độ hoàn thành mục tiêu của từng cá nhân, phòng ban một cách khách quan, minh bạch', 'Theo dõi vị trí GPS của nhân viên', 'In bảng lương tự động'], 1, 'CLO2'),
  q('BA102_Q102', 'Hệ thống tiêu chuẩn ISO 9001 là bộ tiêu chuẩn quốc tế về lĩnh vực gì?', 'MEDIUM', ['Tiêu chuẩn an toàn thực phẩm', 'Hệ thống quản lý chất lượng (Quality Management System - QMS)', 'Tiêu chuẩn bảo vệ môi trường', 'Tiêu chuẩn kế toán quốc tế'], 1, 'CLO2'),
  q('BA102_Q103', 'Kênh truyền thông không chính thức (Grapevine / Kênh tin đồn) trong doanh nghiệp có đặc điểm gì?', 'MEDIUM', ['Do phòng nhân sự chính thức phát hành', 'Lan truyền thông tin rất nhanh qua các mối quan hệ xã hội tự phát giữa các nhân viên, có thể phản ánh tâm tư ngầm của tổ chức nhưng dễ bị thêu dệt sai lệch', 'Chỉ chứa thông tin chính xác 100%', 'Bị pháp luật cấm'], 1, 'CLO2'),
  q('BA102_Q104', 'Khi giải quyết xung đột trong tổ chức, phong cách "Hợp tác" (Collaborating) nhằm đạt kết quả nào?', 'MEDIUM', ['Thắng - Thua (Win - Lose)', 'Thắng - Thắng (Win - Win - cả hai bên cùng đạt được lợi ích tối đa thông qua giải pháp sáng tạo chung)', 'Thua - Thua (Lose - Lose)', 'Nhượng bộ hoàn toàn'], 1, 'CLO2'),
  q('BA102_Q105', 'Nguyên lý quản trị theo ngoại lệ (Management by Exception - MBE) trong kiểm tra khuyên nhà quản trị:', 'MEDIUM', ['Phải tự mình kiểm tra tất cả từng chi tiết nhỏ', 'Chỉ nên tập trung can thiệp và xử lý những sai lệch vượt quá giới hạn dung sai cho phép hoặc các tình huống đặc biệt quan trọng', 'Bỏ qua các lỗi lớn', 'Chỉ kiểm tra vào ngày lễ'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA102_Q106', 'Một nhóm lập trình viên trẻ tuổi, năng động, có trình độ chuyên môn rất cao và tinh thần trách nhiệm tuyệt vời đang thực hiện dự án phần mềm mới. Phong cách lãnh đạo phù hợp nhất là:', 'HARD', ['Phong cách độc đoán, chỉ đạo từng dòng mã', 'Phong cách dân chủ hoặc tự do (Laissez-faire) - trao quyền tự chủ và tạo điều kiện hỗ trợ nguồn lực tối đa', 'Phong cách đe dọa xử phạt', 'Phong cách quản lý vi mô (Micromanagement)'], 1, 'CLO3'),
  q('BA102_Q107', 'Trong một tình huống khẩn cấp như hỏa hoạn nhà xưởng hoặc sự cố sập máy chủ trung tâm đe dọa tê liệt toàn công ty, phong cách lãnh đạo cần thiết nhất là:', 'HARD', ['Phong cách tự do để mọi người tự bàn bạc', 'Phong cách độc đoán (Autocratic) - ra mệnh lệnh dứt khoát, nhanh chóng và quyết liệt để kiểm soát tình hình ngay lập tức', 'Phong cách dân chủ bỏ phiếu kín', 'Phong cách câu lạc bộ'], 1, 'CLO3'),
  q('BA102_Q108', 'Một kỹ sư phần mềm xuất sắc nhận thấy dù mình làm việc thâu đêm hoàn thành xuất sắc dự án nhưng mức thưởng cuối năm lại bằng đúng mức thưởng của một đồng nghiệp thường xuyên đi muộn và lười biếng. Theo Thuyết Công bằng, kỹ sư này có xu hướng:', 'HARD', ['Làm việc chăm chỉ gấp đôi', 'Cảm thấy bất mãn sâu sắc, có thể giảm bớt nỗ lực cống hiến, nghỉ ốm hoặc nộp đơn xin nghỉ việc', 'Không quan tâm', 'Tặng lại tiền thưởng cho sếp'], 1, 'CLO3'),
  q('BA102_Q109', 'Một công ty áp dụng hệ thống quét vân tay và camera kiểm tra từng phút nhân viên ngồi tại bàn làm việc, nhân viên đi vệ sinh quá 5 phút bị trừ lương. Cách quản lý này thể hiện quan điểm của:', 'HARD', ['Thuyết Y', 'Thuyết X (coi người lao động không đáng tin cậy và cần cưỡng bức kiểm soát)', 'Thuyết Maslow bậc cao', 'TQM'], 1, 'CLO3'),
  q('BA102_Q110', 'Để khuyến khích sự gắn bó lâu dài của đội ngũ cán bộ chủ chốt, tập đoàn công nghệ trao quyền mua cổ phiếu ưu đãi (ESOP) và tạo cơ hội dẫn dắt các dự án nghiên cứu lớn. Biện pháp này đánh vào bậc nào của tháp Maslow?', 'HARD', ['Nhu cầu sinh học', 'Nhu cầu được tôn trọng (Esteem) và Nhu cầu tự khẳng định mình (Self-actualization)', 'Nhu cầu ăn uống', 'Nhu cầu an toàn tối thiểu'], 1, 'CLO3'),
  q('BA102_Q111', 'Một hãng sản xuất ô tô kiểm tra toàn diện chất lượng từng lô thép và chip điện tử trước khi đưa vào kho lắp ráp. Đây là hình thức kiểm tra nào?', 'HARD', ['Kiểm tra phản hồi sau bán hàng', 'Kiểm tra lường trước (Feedforward Control)', 'Kiểm tra đồng thời', 'Kiểm tra tài chính'], 1, 'CLO3'),
  q('BA102_Q112', 'Khi điểm số hài lòng của khách hàng (CSAT) tại một chi nhánh ngân hàng giảm xuống dưới mức chuẩn 85% trong 2 tháng liên tiếp, Giám đốc chi nhánh tổ chức rà soát lại thái độ nhân viên và tinh chỉnh quy trình quầy giao dịch. Đây là hành động:', 'HARD', ['Lập kế hoạch mới', 'Hành động điều chỉnh trong quy trình kiểm tra (Corrective Action)', 'Tổ chức bộ máy lại từ đầu', 'Giải thể chi nhánh'], 1, 'CLO3'),
  q('BA102_Q113', 'Trong buổi họp giao ban, một Trưởng phòng liên tục ngắt lời nhân viên cấp dưới và chỉ trích gay gắt khi họ đưa ra ý tưởng mới. Rào cản truyền thông ở đây thuộc về:', 'HARD', ['Rào cản công nghệ', 'Rào cản tâm lý và định kiến từ phía người nghe (Thiếu kỹ năng lắng nghe tích cực)', 'Đường truyền internet chậm', 'Nhiễu vật lý'], 1, 'CLO3'),
  q('BA102_Q114', 'Một doanh nghiệp may mặc áp dụng phương pháp sản xuất tinh gọn Lean Manufacturing để loại bỏ 7 loại lãng phí (Muda) trong quy trình sản xuất. Mục tiêu chính là:', 'HARD', ['Tuyển thêm nhiều công nhân', 'Tối ưu hóa dòng chảy sản xuất, giảm thời gian chu kỳ và nâng cao hiệu quả kiểm soát chất lượng', 'Tăng lượng hàng tồn kho', 'Mua thêm nhà xưởng'], 1, 'CLO3'),
  q('BA102_Q115', 'Khi hai Trưởng phòng Kinh doanh và Sản xuất mâu thuẫn gay gắt về tiến độ giao hàng và chất lượng sản phẩm, Tổng giám đốc yêu cầu hai bên cùng ngồi lại phân tích nguyên nhân gốc rễ và thiết kế lại quy trình phối hợp để cả hai phòng đều đạt KPI. Phong cách xử lý xung đột này là:', 'HARD', ['Phong cách né tránh (Avoiding)', 'Phong cách hợp tác (Collaborating - Win-Win)', 'Phong cách áp đặt quyền lực', 'Phong cách nhượng bộ'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA102_Q116', 'Lý thuyết Lãnh đạo theo tình huống của Hersey & Blanchard (Situational Leadership Theory) đề xuất phong cách lãnh đạo phải linh hoạt điều chỉnh theo yếu tố nào của cấp dưới?', 'EXPERT', ['Chiều cao và cân nặng', 'Mức độ sẵn sàng / Trưởng thành của nhân viên (Maturity / Readiness: Năng lực chuyên môn và Sự tự tin/Cam kết làm việc)', 'Mối quan hệ họ hàng', 'Mức lương hiện tại'], 1, 'CLO4'),
  q('BA102_Q117', 'Hệ thống Quản trị theo Mục tiêu và Kết quả then chốt (OKR - Objectives and Key Results) được Google và Intel áp dụng có điểm khác biệt nổi trội nào so với KPI truyền thống?', 'EXPERT', ['OKR chỉ để trừ lương', 'OKR tập trung vào các mục tiêu đầy thách thức / khát vọng (Ambitious / Stretch goals), không gắn trực tiếp vào việc đánh giá lương thưởng mà nhằm thúc đẩy sự đổi mới bứt phá và liên kết toàn diện', 'OKR không bao giờ thay đổi', 'Chỉ áp dụng cho giám đốc'], 1, 'CLO4'),
  q('BA102_Q118', 'Khái niệm "Trí tuệ cảm xúc" (Emotional Intelligence - EQ) của Daniel Goleman đóng góp tới 80% thành công của các nhà lãnh đạo kiệt xuất nhờ 5 thành tố nào?', 'EXPERT', ['Toán học, logic, trí nhớ, ngôn ngữ, thể chất', 'Tự nhận thức (Self-awareness), Tự điều chỉnh (Self-regulation), Động lực nội tại (Motivation), Thấu cảm (Empathy) và Kỹ năng xã hội (Social skills)', 'Tính toán nhanh, nghiêm khắc, độc đoán, quyết liệt, khắt khe', 'Khả năng hùng biện một chiều'], 1, 'CLO4'),
  q('BA102_Q119', 'Phương pháp Six Sigma (6σ) hướng tới mục tiêu chất lượng hoàn hảo với tỷ lệ sai lỗi tối đa không vượt quá bao nhiêu?', 'EXPERT', ['3.4 lỗi trên 1.000 sản phẩm', '3.4 lỗi trên 1 triệu cơ hội sai sót (DPMO - Defects Per Million Opportunities)', '10% sản phẩm lỗi', '0.1% sản phẩm lỗi'], 1, 'CLO4'),
  q('BA102_Q120', 'Khái niệm "Lãnh đạo phục vụ" (Servant Leadership) do Robert K. Greenleaf đề xuất định hình lại vai trò của nhà lãnh đạo như thế nào?', 'EXPERT', ['Lãnh đạo là ông chủ ra lệnh', 'Lãnh đạo đặt nhu cầu phát triển và thành công của nhân viên và cộng đồng lên trên hết; quyền lực bắt nguồn từ việc phụng sự và hỗ trợ người khác đạt được tiềm năng cao nhất', 'Lãnh đạo làm việc tạp vụ', 'Bãi bỏ chức danh lãnh đạo'], 1, 'CLO4')
];

module.exports = {
  course: {
    code: 'BA102',
    name: 'Quản Trị Học Đại Cương',
    faculty: 'Khoa Kinh Tế & QTKD',
    category_code: 'CAT-BA102',
    credits: 3
  },
  root_1: root1,
  root_2: root2,
  root_3: root3,
  getAllQuestions: () => [...root1, ...root2, ...root3]
};
