// backend/services/examBank/ba101.bank.js
// Ngân hàng câu hỏi chuẩn hóa: BA101 — Kinh Tế Vi Mô (Microeconomics)
// Tổng cộng: 120 câu hỏi (3 Đề gốc x 40 câu hỏi)
'use strict';

function q(id, content, difficulty, answers, correctIdx, clo = 'CLO1') {
  return {
    id,
    course_code: 'BA101',
    content,
    difficulty,
    default_mark: 0.25,
    clo,
    answers: answers.map((text, idx) => ({
      id: `${id}_A${idx + 1}`,
      letter: ['A', 'B', 'C', 'D'][idx],
      content: text,
      is_correct: idx === correctIdx,
      fraction: idx === correctIdx ? 1.0 : 0.0
    }))
  };
}

// ĐỀ GỐC 1 (40 câu): Cung - Cầu, Cân bằng thị trường, Độ co giãn, Thặng dư kinh tế & Chính sách giá
const root1 = [
  // Nhận biết (10 câu)
  q('BA101_Q001', 'Kinh tế học vi mô nghiên cứu hành vi và quyết định kinh tế của các chủ thể nào?', 'EASY', ['Toàn bộ nền kinh tế quốc gia và tổng sản phẩm quốc nội (GDP)', 'Các đơn vị kinh tế cá nhân riêng lẻ như người tiêu dùng, hộ gia đình và doanh nghiệp', 'Chính sách tiền tệ của ngân hàng trung ương', 'Tỷ giá hối đoái và cán cân thanh toán quốc tế'], 1, 'CLO1'),
  q('BA101_Q002', 'Chi phí cơ hội (Opportunity Cost) của một sự lựa chọn được định nghĩa là:', 'EASY', ['Tổng số tiền phải chi trả trực tiếp cho sự lựa chọn đó', 'Giá trị của cơ hội tốt nhất bị bỏ qua khi đưa ra quyết định', 'Chi phí phát sinh ngoài ý muốn', 'Khoản lỗ trong báo cáo tài chính'], 1, 'CLO1'),
  q('BA101_Q003', 'Quy luật Cầu (Law of Demand) phát biểu rằng trong điều kiện các yếu tố khác không đổi (Ceteris Paribus):', 'EASY', ['Giá tăng thì lượng cầu tăng', 'Giá hàng hóa tăng thì lượng cầu đối với hàng hóa đó sẽ giảm xuống, và ngược lại', 'Thu nhập tăng thì lượng cầu giảm', 'Giá tăng không ảnh hưởng tới lượng cầu'], 1, 'CLO1'),
  q('BA101_Q004', 'Đường cầu (Demand Curve) thông thường trên đồ thị giá - lượng có đặc điểm hình học nào?', 'EASY', ['Dốc lên từ trái sang phải', 'Dốc xuống từ trái sang phải (độ dốc âm)', 'Nằm ngang song song trục hoành', 'Thẳng đứng song song trục tung'], 1, 'CLO1'),
  q('BA101_Q005', 'Quy luật Cung (Law of Supply) phát biểu rằng trong điều kiện các yếu tố khác không đổi:', 'EASY', ['Khi giá hàng hóa tăng lên thì lượng cung hàng hóa đó sẽ tăng theo', 'Khi giá tăng thì lượng cung giảm', 'Lượng cung độc lập với giá cả', 'Chi phí sản xuất tăng thì lượng cung tăng'], 0, 'CLO1'),
  q('BA101_Q006', 'Trạng thái cân bằng thị trường (Market Equilibrium) đạt được tại mức giá mà tại đó:', 'EASY', ['Doanh nghiệp đạt lợi nhuận tối đa', 'Lượng cầu bằng chính xác lượng cung (Qd = Qs)', 'Chính phủ can thiệp định giá', 'Người tiêu dùng mua được nhiều nhất'], 1, 'CLO1'),
  q('BA101_Q007', 'Khi giá thị trường cao hơn mức giá cân bằng, hiện tượng gì sẽ xảy ra trên thị trường?', 'EASY', ['Thiếu hụt hàng hóa (Shortage)', 'Dư thừa hàng hóa (Surplus)', 'Thị trường đóng băng', 'Cầu tăng đột biến'], 1, 'CLO1'),
  q('BA101_Q008', 'Khi giá thị trường thấp hơn mức giá cân bằng, thị trường sẽ rơi vào trạng thái:', 'EASY', ['Dư thừa hàng hóa', 'Dư cung', 'Thiếu hụt hàng hóa (Lượng cầu vượt lượng cung)', 'Cân bằng hoàn hảo'], 2, 'CLO1'),
  q('BA101_Q009', 'Hai hàng hóa được gọi là hàng hóa thay thế (Substitutes) nếu:', 'EASY', ['Giá của hàng hóa này tăng làm giảm lượng cầu hàng hóa kia', 'Giá của hàng hóa này tăng làm tăng lượng cầu đối với hàng hóa kia', 'Chúng luôn phải tiêu dùng cùng nhau', 'Độ co giãn chéo bằng 0'], 1, 'CLO1'),
  q('BA101_Q010', 'Hai hàng hóa được gọi là hàng hóa bổ sung (Complements) nếu:', 'EASY', ['Giá của hàng hóa này tăng dẫn đến sự sụt giảm lượng cầu của hàng hóa kia', 'Chúng có thể dùng thay thế cho nhau', 'Cả hai đều là hàng xa xỉ', 'Độ co giãn theo thu nhập âm'], 0, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA101_Q011', 'Sự khác biệt cốt lõi giữa "Sự dịch chuyển của đường cầu" và "Sự vận động dọc theo đường cầu" là gì?', 'MEDIUM', ['Không có sự khác biệt', 'Sự vận động dọc xảy ra khi bản thân giá của hàng hóa đó thay đổi; sự dịch chuyển xảy ra khi các yếu tố phi giá (thu nhập, thị hiếu, giá hàng liên quan) thay đổi', 'Dịch chuyển chỉ xảy ra với hàng xa xỉ', 'Vận động dọc làm thay đổi toàn bộ thị trường'], 1, 'CLO2'),
  q('BA101_Q012', 'Nếu thu nhập của người tiêu dùng tăng lên mà lượng cầu đối với một loại hàng hóa lại giảm xuống, hàng hóa đó được gọi là:', 'MEDIUM', ['Hàng hóa thông thường (Normal Goods)', 'Hàng hóa thứ cấp / cấp thấp (Inferior Goods)', 'Hàng hóa thiết yếu', 'Hàng hóa công cộng'], 1, 'CLO2'),
  q('BA101_Q013', 'Độ co giãn của cầu theo giá (Price Elasticity of Demand - Ed) đo lường điều gì?', 'MEDIUM', ['Sự thay đổi của giá khi lượng cầu đổi', 'Phần trăm thay đổi của lượng cầu chia cho phần trăm thay đổi của giá hàng hóa', 'Mức độ hài lòng của người mua', 'Tốc độ cung ứng của nhà sản xuất'], 1, 'CLO2'),
  q('BA101_Q014', 'Khi cầu về một mặt hàng là co giãn nhiều theo giá (|Ed| > 1), để tăng tổng doanh thu (TR = P * Q), doanh nghiệp nên:', 'MEDIUM', ['Tăng giá bán', 'Giảm giá bán hàng hóa', 'Giữ nguyên giá bán', 'Ngừng sản xuất'], 1, 'CLO2'),
  q('BA101_Q015', 'Khi cầu về một mặt hàng là co giãn ít theo giá (|Ed| < 1, ví dụ: xăng dầu, thuốc chữa bệnh), chính sách giá giúp tăng tổng doanh thu là:', 'MEDIUM', ['Giảm giá sâu', 'Tăng giá bán', 'Khuyến mãi giảm 50%', 'Tặng quà kèm'], 1, 'CLO2'),
  q('BA101_Q016', 'Cầu hoàn toàn không co giãn theo giá (Perfect Inelastic Demand) có đồ thị là đường:', 'MEDIUM', ['Nằm ngang song song trục hoành (|Ed| = ∞)', 'Thẳng đứng song song trục tung (Ed = 0)', 'Dốc 45 độ', 'Đường cong Parabol'], 1, 'CLO2'),
  q('BA101_Q017', 'Độ co giãn chéo của cầu theo giá (Exy) mang giá trị DƯƠNG (Exy > 0) khẳng định mối quan hệ nào giữa 2 hàng hóa X và Y?', 'MEDIUM', ['X và Y là hai hàng hóa độc lập', 'X và Y là hai hàng hóa thay thế cho nhau', 'X và Y là hai hàng hóa bổ sung', 'X là hàng cấp thấp'], 1, 'CLO2'),
  q('BA101_Q018', 'Độ co giãn của cầu theo thu nhập (Ei) mang giá trị lớn hơn 1 (Ei > 1) chỉ ra rằng hàng hóa đó thuộc nhóm:', 'MEDIUM', ['Hàng hóa thiết yếu', 'Hàng hóa cao cấp / xa xỉ (Luxury Goods)', 'Hàng hóa thứ cấp', 'Hàng hóa miễn phí'], 1, 'CLO2'),
  q('BA101_Q019', 'Thặng dư tiêu dùng (Consumer Surplus - CS) được tính bằng:', 'MEDIUM', ['Tổng số tiền người tiêu dùng đã trả', 'Chênh lệch giữa mức giá tối đa mà người tiêu dùng sẵn sàng trả và mức giá thực tế họ phải trả trên thị trường', 'Lợi nhuận của người bán', 'Doanh thu trừ chi phí'], 1, 'CLO2'),
  q('BA101_Q020', 'Thặng dư sản xuất (Producer Surplus - PS) được thể hiện trên đồ thị là diện tích nằm ở vị trí nào?', 'MEDIUM', ['Phía trên đường giá cân bằng và dưới đường cầu', 'Nằm phía dưới mức giá thị trường và phía trên đường cung', 'Bên phải điểm cân bằng', 'Dưới trục hoành'], 1, 'CLO2'),
  q('BA101_Q021', 'Giá trần (Price Ceiling) do Chính phủ áp đặt để bảo vệ người tiêu dùng sẽ gây ra tác động kinh tế nào nếu đặt dưới giá cân bằng?', 'MEDIUM', ['Gây dư thừa hàng hóa', 'Gây thiếu hụt hàng hóa (Cầu > Cung), dẫn tới hiện tượng xếp hàng hoặc thị trường chợ đen', 'Làm giá tăng vọt', 'Không có tác động gì'], 1, 'CLO2'),
  q('BA101_Q022', 'Giá sàn (Price Floor) do Chính phủ quy định (ví dụ: mức lương tối thiểu, giá sàn thu mua nông sản) đặt trên mức giá cân bằng dẫn đến:', 'MEDIUM', ['Thiếu hụt hàng hóa', 'Hiện tượng dư cung / dư thừa hàng hóa (ví dụ: thất nghiệp trên thị trường lao động)', 'Tăng thặng dư toàn xã hội', 'Cầu vượt cung'], 1, 'CLO2'),
  q('BA101_Q023', 'Tổn thất xã hội (Deadweight Loss - DWL) do thuế hoặc việc can thiệp giá của chính phủ phản ánh điều gì?', 'MEDIUM', ['Số tiền thuế thu vào ngân sách', 'Sự sụt giảm thặng dư toàn xã hội (tổng CS + PS) mà không chủ thể nào nhận được, đại diện cho sự kém hiệu quả của thị trường', 'Lợi nhuận của doanh nghiệp độc quyền', 'Chi phí in tiền'], 1, 'CLO2'),
  q('BA101_Q024', 'Khi chính phủ đánh một mức thuế t đồng/đơn vị sản phẩm lên người bán, ai sẽ là người gánh chịu phần thuế nhiều hơn?', 'MEDIUM', ['Luôn luôn là người bán', 'Bên nào có đường co giãn ít hơn (kém co giãn hơn theo giá) sẽ gánh chịu phần lớn gánh nặng thuế', 'Chia đôi đều 50-50 trong mọi trường hợp', 'Chỉ người mua gánh'], 1, 'CLO2'),
  q('BA101_Q025', 'Đường giới hạn khả năng sản xuất (PPF - Production Possibilities Frontier) minh họa cho nguyên lý kinh tế nào?', 'MEDIUM', ['Sự khan hiếm nguồn lực, sự đánh đổi và chi phí cơ hội ngày càng tăng', 'Quy luật cung cầu', 'Thương mại quốc tế', 'Lạm phát tiền tệ'], 0, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA101_Q026', 'Cho hàm cầu Qd = 100 - 2P và hàm cung Qs = 10 + 4P. Mức giá và sản lượng cân bằng của thị trường là:', 'HARD', ['P = 10, Q = 80', 'P = 15, Q = 70 (giải 100 - 2P = 10 + 4P => 6P = 90 => P = 15, Q = 70)', 'P = 20, Q = 60', 'P = 12, Q = 76'], 1, 'CLO3'),
  q('BA101_Q027', 'Với hàm cầu Qd = 100 - 2P tại mức giá cân bằng P = 15 và Q = 70, độ co giãn của cầu theo giá Ed là:', 'HARD', ['Ed = -2 * (15 / 70) ≈ -0.43 (cầu co giãn ít)', 'Ed = -2.0', 'Ed = -1.5', 'Ed = 0'], 0, 'CLO3'),
  q('BA101_Q028', 'Nếu giá một tách cà phê tăng 10% dẫn tới lượng cầu về đường giảm 15%, độ co giãn chéo Exy là bao nhiêu và 2 hàng hóa này có quan hệ gì?', 'HARD', ['Exy = +1.5, hàng hóa thay thế', 'Exy = -1.5 (-15% / +10%), hai hàng hóa này bổ sung cho nhau', 'Exy = -0.67, hàng hóa độc lập', 'Exy = 1.0, hàng hóa thiết yếu'], 1, 'CLO3'),
  q('BA101_Q029', 'Trên thị trường có Qd = 100 - 2P và Qs = 10 + 4P. Nếu Chính phủ áp đặt giá trần Pmax = 10, lượng thiếu hụt trên thị trường là bao nhiêu?', 'HARD', ['Thiếu hụt 10 đơn vị', 'Qd = 80, Qs = 50 => Thiếu hụt 30 đơn vị sản phẩm', 'Dư thừa 20 đơn vị', 'Cân bằng không thiếu hụt'], 1, 'CLO3'),
  q('BA101_Q030', 'Khi thu nhập của hộ gia đình tăng từ 10 triệu lên 12 triệu đồng/tháng (tăng 20%), chi tiêu mua thịt bò tăng từ 2 kg lên 2.6 kg (tăng 30%). Độ co giãn thu nhập Ei là:', 'HARD', ['Ei = 0.67 (hàng thiết yếu)', 'Ei = 30% / 20% = 1.5 (thịt bò là hàng hóa cao cấp / xa xỉ đối với hộ này)', 'Ei = -1.5 (hàng thứ cấp)', 'Ei = 1.0'], 1, 'CLO3'),
  q('BA101_Q031', 'Đường cung dốc đứng hoàn toàn (Es = 0). Khi chính phủ đánh thuế lên người bán thì:', 'HARD', ['Người mua gánh toàn bộ thuế', 'Người bán gánh chịu toàn bộ 100% khoản thuế vì giá thị trường không thay đổi', 'Doanh thu nhà nước bằng 0', 'Không có ai gánh thuế'], 1, 'CLO3'),
  q('BA101_Q032', 'Nếu đồng thời Cầu tăng mạnh và Cung giảm nhẹ trên thị trường, điều gì chắc chắn xảy ra với trạng thái cân bằng mới?', 'HARD', ['Sản lượng chắc chắn giảm', 'Mức giá cân bằng chắc chắn tăng lên, trong khi sự thay đổi của sản lượng là chưa xác định (phụ thuộc vào độ lớn của 2 sự dịch chuyển)', 'Giá chắc chắn giảm', 'Cả giá và sản lượng đều giữ nguyên'], 1, 'CLO3'),
  q('BA101_Q033', 'Thặng dư tiêu dùng (CS) của thị trường có hàm cầu P = 50 - 0.5Q tại mức giá cân bằng P = 30 và Q = 40 là diện tích tam giác bằng bao nhiêu?', 'HARD', ['CS = (50 - 30) * 40 / 2 = 400', 'CS = 800', 'CS = 200', 'CS = 600'], 0, 'CLO3'),
  q('BA101_Q034', 'Khi công nghệ sản xuất chíp bán dẫn có bước đột phá giúp giảm chi phí sản xuất, đường cung máy tính xách tay sẽ dịch chuyển như thế nào?', 'HARD', ['Dịch chuyển sang trái (giảm cung)', 'Dịch chuyển sang phải (tăng cung), dẫn đến giá cân bằng giảm và sản lượng giao dịch tăng', 'Không dịch chuyển mà chỉ trượt dọc', 'Dịch chuyển thẳng đứng lên trên'], 1, 'CLO3'),
  q('BA101_Q035', 'Khi một vụ hạn hán nghiêm trọng xảy ra làm giảm sản lượng lúa mì, biết rằng cầu lúa mì là co giãn ít theo giá (|Ed| < 1), tổng doanh thu của người nông dân trồng lúa mì sẽ:', 'HARD', ['Giảm mạnh do mất mùa', 'Tăng lên vì tỷ lệ tăng của giá cao hơn tỷ lệ sụt giảm của sản lượng', 'Không thay đổi', 'Bằng 0'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA101_Q036', 'Nghịch lý mùa màng (King\'s Law / Cobweb Model) trong nông nghiệp giải thích hiện tượng gì?', 'EXPERT', ['Nông dân luôn giàu có khi được mùa', 'Khi được mùa lớn, sản lượng tăng làm giá nông sản giảm sâu do cầu về lương thực kém co giãn theo giá, khiến tổng doanh thu của nông dân bị sụt giảm nghiêm trọng', 'Được mùa làm tăng lạm phát', 'Nông dân bỏ ruộng khi giá cao'], 1, 'CLO4'),
  q('BA101_Q037', 'Tổn thất tải trọng (Deadweight Loss) do thuế tăng tỷ lệ như thế nào với mức thuế t suất?', 'EXPERT', ['Tăng tỷ lệ thuận bậc nhất với mức thuế t', 'Tăng theo bình phương của mức thuế suất (DWL tỷ lệ thuận với t^2)', 'Giảm khi thuế tăng', 'Không phụ thuộc vào mức thuế'], 1, 'CLO4'),
  q('BA101_Q038', 'Trong mô hình cung cầu mạng nhện (Cobweb Model), điều kiện để thị trường dao động hội tụ dần về điểm cân bằng ổn định là:', 'EXPERT', ['Đường cầu dốc hơn đường cung', 'Độ dốc của đường cung lớn hơn độ dốc của đường cầu (Đường cung kém co giãn hơn đường cầu)', 'Độ dốc của đường cầu lớn hơn đường cung', 'Giá cả do chính phủ ấn định'], 1, 'CLO4'),
  q('BA101_Q039', 'Tại sao việc trợ cấp một mức s đồng/đơn vị sản phẩm cũng gây ra tổn thất xã hội (Deadweight Loss)?', 'EXPERT', ['Vì chi phí chính phủ bỏ ra để trợ cấp lớn hơn tổng thặng dư gia tăng của người tiêu dùng và nhà sản xuất, dẫn tới sản xuất quá mức tối ưu xã hội', 'Vì người tiêu dùng không thích trợ cấp', 'Vì doanh nghiệp từ chối nhận trợ cấp', 'Trợ cấp không bao giờ gây tổn thất xã hội'], 0, 'CLO4'),
  q('BA101_Q040', 'Định lý Coase về việc giải quyết ngoại ứng (Externalities) khẳng định thị trường tư nhân có thể tự giải quyết hiệu quả ngoại ứng mà không cần nhà nước can thiệp khi:', 'EXPERT', ['Chi phí giao dịch bằng 0 (hoặc rất nhỏ) và quyền sở hữu tài sản được xác định rõ ràng', 'Có sự hiện diện của tòa án', 'Mức thuế ô nhiễm thật cao', 'Doanh nghiệp thuộc sở hữu nhà nước'], 0, 'CLO4')
];

// ĐỀ GỐC 2 (40 câu): Lý thuyết hành vi người tiêu dùng & Lý thuyết sản xuất
const root2 = [
  // Nhận biết (10 câu)
  q('BA101_Q041', 'Độ thỏa dụng / Lợi ích (Utility) trong kinh tế học là thước đo biểu thị điều gì?', 'EASY', ['Số tiền tiết kiệm được', 'Mức độ thỏa mãn, hài lòng mà người tiêu dùng nhận được khi tiêu dùng một số lượng hàng hóa hay dịch vụ', 'Giá trị thương hiệu sản phẩm', 'Độ bền vật lý của sản phẩm'], 1, 'CLO1'),
  q('BA101_Q042', 'Lợi ích cận biên (Marginal Utility - MU) là gì?', 'EASY', ['Tổng lợi ích nhận được từ tất cả các đơn vị hàng hóa', 'Lợi ích tăng thêm nhận được khi tiêu thụ thêm một đơn vị hàng hóa hay dịch vụ (MU = ΔTU / ΔQ)', 'Chi phí mua một đơn vị hàng hóa', 'Mức giá rẻ nhất trên thị trường'], 1, 'CLO1'),
  q('BA101_Q043', 'Quy luật Lợi ích cận biên giảm dần (Law of Diminishing Marginal Utility) phát biểu rằng:', 'EASY', ['Tiêu thụ càng nhiều thì tổng lợi ích càng giảm ngay từ đầu', 'Khi một cá nhân tiêu dùng ngày càng nhiều một loại hàng hóa trong một khoảng thời gian nhất định, lợi ích cận biên thu được từ các đơn vị tiêu dùng bổ sung sẽ có xu hướng giảm dần', 'Người giàu có lợi ích cao hơn', 'Giá càng đắt thì càng thích'], 1, 'CLO1'),
  q('BA101_Q044', 'Đường bàng quan (Indifference Curve) là tập hợp các gói hàng hóa mà tại đó:', 'EASY', ['Người tiêu dùng chi tiêu cùng một số tiền', 'Mang lại cho người tiêu dùng cùng một mức độ thỏa mãn / tổng lợi ích như nhau', 'Có cùng chi phí sản xuất', 'Doanh nghiệp bán được cùng doanh thu'], 1, 'CLO1'),
  q('BA101_Q045', 'Tỷ lệ thay thế cận biên (Marginal Rate of Substitution - MRS_xy) đo lường:', 'EASY', ['Số lượng hàng hóa Y mà người tiêu dùng sẵn sàng từ bỏ để có thêm một đơn vị hàng hóa X mà vẫn giữ nguyên mức thỏa dụng (MRS = -ΔY/ΔX = MUx/MUy)', 'Tỷ giá hối đoái giữa 2 đồng tiền', 'Tỷ lệ lợi nhuận của 2 sản phẩm', 'Tốc độ tiêu hao hàng hóa'], 0, 'CLO1'),
  q('BA101_Q046', 'Đường ngân sách (Budget Line) biểu diễn điều gì?', 'EASY', ['Lợi ích tối đa của người mua', 'Tất cả các kết hợp của hai loại hàng hóa mà người tiêu dùng có thể mua được với toàn bộ thu nhập (I = Px*X + Py*Y) ở mức giá cho trước', 'Doanh thu dự kiến của doanh nghiệp', 'Khoản vay ngân hàng'], 1, 'CLO1'),
  q('BA101_Q047', 'Độ dốc của đường ngân sách bằng tỷ số nào sau đây?', 'EASY', ['-(Px / Py)', '-(Py / Px)', '-(MUx / MUy)', '-(I / Px)'], 0, 'CLO1'),
  q('BA101_Q048', 'Trong ngắn hạn (Short Run), yếu tố sản xuất nào thường được coi là cố định (Fixed Input)?', 'EASY', ['Lao động phổ thông', 'Nguyên vật liệu tiêu hao', 'Quy mô nhà xưởng, máy móc thiết bị cốt lõi (Vốn - K)', 'Điện năng tiêu thụ'], 2, 'CLO1'),
  q('BA101_Q049', 'Năng suất cận biên của lao động (Marginal Product of Labor - MPL) được tính bằng công thức:', 'EASY', ['MPL = Q / L', 'MPL = ΔQ / ΔL (Đạo hàm của hàm sản lượng Q theo biến số lao động L)', 'MPL = Q * L', 'MPL = TC / L'], 1, 'CLO1'),
  q('BA101_Q050', 'Năng suất trung bình của lao động (Average Product of Labor - APL) được tính bằng:', 'EASY', ['APL = ΔQ / ΔL', 'APL = Q / L (Tổng sản lượng chia cho tổng số lao động sử dụng)', 'APL = P * Q', 'APL = MC / L'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA101_Q051', 'Điều kiện để người tiêu dùng đạt trạng thái tối đa hóa lợi ích (Consumer Equilibrium) với ngân sách cho trước là:', 'MEDIUM', ['Mua nhiều sản phẩm đắt tiền nhất', 'Điểm tiếp xúc giữa đường bàng quan và đường ngân sách, tại đó MRS_xy = Px / Py (tương đương MUx / Px = MUy / Py)', 'Chi tiêu hết một nửa số tiền', 'Chọn gói hàng nằm ngoài đường ngân sách'], 1, 'CLO2'),
  q('BA101_Q052', 'Các đường bàng quan thông thường không bao giờ cắt nhau vì điều này sẽ vi phạm tiên đề nào trong lý thuyết sở thích?', 'MEDIUM', ['Tiên đề về sự khan hiếm', 'Tiên đề về tính bắc cầu (Transitivity) của sở thích người tiêu dùng', 'Tiên đề về tính độc lập', 'Tiên đề về lòng vị tha'], 1, 'CLO2'),
  q('BA101_Q053', 'Khi thu nhập của người tiêu dùng tăng lên trong khi giá của các hàng hóa không đổi, đường ngân sách sẽ:', 'MEDIUM', ['Xoay quanh trục tung', 'Dịch chuyển song song sang phải (ra xa gốc tọa độ)', 'Dịch chuyển song song sang trái', 'Không thay đổi vị trí'], 1, 'CLO2'),
  q('BA101_Q054', 'Khi giá của hàng hóa X giảm xuống trong khi thu nhập và giá hàng hóa Y giữ nguyên, đường ngân sách sẽ:', 'MEDIUM', ['Dịch chuyển song song sang phải', 'Xoay ra phía ngoài quanh điểm chặn trên trục tung (trục hàng hóa Y)', 'Xoay vào phía trong', 'Không biến đổi'], 1, 'CLO2'),
  q('BA101_Q055', 'Tác động thay thế (Substitution Effect) khi giá của hàng hóa X giảm phản ánh:', 'MEDIUM', ['Người tiêu dùng mua ít hàng hóa X hơn', 'Người tiêu dùng có xu hướng mua nhiều hàng hóa X hơn vì nó trở nên tương đối rẻ hơn so với hàng hóa khác (giữ nguyên mức thỏa dụng)', 'Thu nhập thực tế giảm đi', 'Lợi ích cận biên tăng vọt'], 1, 'CLO2'),
  q('BA101_Q056', 'Hàng hóa Giffen là trường hợp đặc biệt của hàng hóa cấp thấp khi mà:', 'MEDIUM', ['Cầu hoàn toàn không co giãn', 'Tác động thu nhập âm vượt trội hơn tác động thay thế, dẫn tới khi giá tăng thì lượng cầu lại tăng (đường cầu dốc lên)', 'Doanh nghiệp luôn có lãi', 'Hàng hóa được chính phủ trợ giá 100%'], 1, 'CLO2'),
  q('BA101_Q057', 'Quy luật Năng suất cận biên giảm dần (Law of Diminishing Marginal Returns) xảy ra khi nào trong sản xuất?', 'MEDIUM', ['Khi công nghệ bị thoái hóa', 'Khi liên tục tăng một yếu tố sản xuất biến đổi (như Lao động L) kết hợp với một lượng cố định các yếu tố sản xuất khác (như Vốn K), đến một ngưỡng nhất định năng suất cận biên MPL sẽ giảm dần', 'Khi doanh nghiệp sa thải nhân viên', 'Trong dài hạn khi mở rộng nhà máy'], 1, 'CLO2'),
  q('BA101_Q058', 'Mối quan hệ hình học giữa đường Năng suất cận biên (MP) và đường Năng suất trung bình (AP) là:', 'MEDIUM', ['Đường MP luôn nằm trên đường AP', 'Đường MP cắt đường AP từ trên xuống tại điểm cực đại của đường AP (khi MP > AP thì AP tăng, khi MP < AP thì AP giảm)', 'Đường AP cắt đường MP tại gốc tọa độ', 'Hai đường luôn song song'], 1, 'CLO2'),
  q('BA101_Q059', 'Giai đoạn sản xuất hợp lý (Giai đoạn II) của doanh nghiệp trong ngắn hạn nằm trong khoảng nào của lao động L?', 'MEDIUM', ['Từ L = 0 đến khi MP đạt cực đại', 'Từ điểm APL đạt cực đại (APL = MPL) cho đến khi MPL = 0 (khi tổng sản lượng Q đạt cực đại)', 'Sau khi MPL < 0', 'Bất kỳ mức lao động nào'], 1, 'CLO2'),
  q('BA101_Q060', 'Đường đồng sản lượng (Isoquant) biểu diễn tập hợp tất cả các kết hợp của các yếu tố đầu vào (K và L) nhằm:', 'MEDIUM', ['Đạt cùng một mức chi phí sản xuất', 'Tạo ra cùng một mức sản lượng đầu ra (Q) như nhau', 'Tối đa hóa doanh thu', 'Thuê cùng một số lượng công nhân'], 1, 'CLO2'),
  q('BA101_Q061', 'Tỷ lệ thay thế kỹ thuật cận biên (MRTS_LK) giữa Lao động và Vốn được tính bằng công thức:', 'MEDIUM', ['MRTS_LK = -ΔK / ΔL = MPL / MPK', 'MRTS_LK = L / K', 'MRTS_LK = w / r', 'MRTS_LK = TC / Q'], 0, 'CLO2'),
  q('BA101_Q062', 'Đường đồng phí (Isocost) biểu diễn tất cả các kết hợp giữa Vốn (K) và Lao động (L) mà doanh nghiệp có thể thuê với:', 'MEDIUM', ['Cùng một mức sản lượng đầu ra', 'Cùng một mức tổng chi phí sản xuất xác định (TC = w*L + r*K)', 'Chi phí bằng 0', 'Cùng một giá bán sản phẩm'], 1, 'CLO2'),
  q('BA101_Q063', 'Nguyên tắc phối hợp tối ưu các yếu tố sản xuất để tối thiểu hóa chi phí cho một mức sản lượng cho trước là:', 'MEDIUM', ['Thuê nhiều lao động nhất có thể', 'Điểm tiếp xúc giữa đường đồng sản lượng và đường đồng phí, tại đó: MRTS_LK = w / r (tương đương MPL / w = MPK / r)', 'Chi tiêu bằng nhau cho K và L', 'Không dùng vốn K'], 1, 'CLO2'),
  q('BA101_Q064', 'Hiệu suất tăng theo quy mô (Increasing Returns to Scale) xảy ra khi nào trong dài hạn?', 'MEDIUM', ['Khi tăng gấp đôi tất cả các yếu tố đầu vào thì sản lượng đầu ra tăng hơn gấp đôi', 'Khi sản lượng tăng đúng 2 lần', 'Khi chi phí cận biên tăng', 'Khi giá bán sản phẩm tăng'], 0, 'CLO2'),
  q('BA101_Q065', 'Hàm sản xuất Cobb-Douglas có dạng Q = A * L^α * K^β. Doanh nghiệp có hiệu suất không đổi theo quy mô (Constant Returns to Scale) khi:', 'MEDIUM', ['α + β > 1', 'α + β = 1', 'α + β < 1', 'α = β'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA101_Q066', 'Một người tiêu dùng có hàm thỏa dụng TU(X, Y) = X * Y, thu nhập I = 120.000 đồng, Px = 10.000 đồng, Py = 20.000 đồng. Gói hàng hóa tối ưu (X, Y) là:', 'HARD', ['X = 12, Y = 0', 'X = 6, Y = 3 (giải MUx/MUy = Y/X = Px/Py = 1/2 => X = 2Y, thế vào 10X + 20Y = 120 => 40Y = 120 => Y = 3, X = 6)', 'X = 4, Y = 4', 'X = 8, Y = 2'], 1, 'CLO3'),
  q('BA101_Q067', 'Với hàm sản xuất Q = 10 * L^0.5 * K^0.5, hàm này thể hiện tính chất quy mô nào?', 'HARD', ['Hiệu suất tăng theo quy mô', 'Hiệu suất không đổi theo quy mô (vì 0.5 + 0.5 = 1.0)', 'Hiệu suất giảm theo quy mô', 'Không thể xác định'], 1, 'CLO3'),
  q('BA101_Q068', 'Cho hàm sản xuất ngắn hạn Q = 100*L + 15*L^2 - L^3. Năng suất cận biên MPL đạt giá trị cực đại tại mức lao động L bằng:', 'HARD', ['L = 3', 'L = 5 (giải đạo hàm MPL\' = (100 + 30L - 3L^2)\' = 30 - 6L = 0 => L = 5)', 'L = 10', 'L = 15'], 1, 'CLO3'),
  q('BA101_Q069', 'Với hàm sản lượng Q = 100*L + 15*L^2 - L^3, sản lượng Q đạt cực đại khi mức lao động L bằng:', 'HARD', ['L = 5', 'L = 12.8 (tại điểm MPL = 0)', 'L = 10 (tại MPL = 100 + 30(10) - 3(100) = 100 != 0)', 'L = 20'], 1, 'CLO3'),
  q('BA101_Q070', 'Một doanh nghiệp có hàm sản xuất Q = K * L, giá thuê lao động w = 4 USD, giá thuê vốn r = 9 USD. Doanh nghiệp cần phối hợp K và L theo tỷ lệ nào để tối ưu chi phí?', 'HARD', ['K / L = 4 / 9', 'K / L = w / r = 4 / 9 (vì MRTS = K / L = w / r)', 'K / L = 9 / 4', 'K = L'], 1, 'CLO3'),
  q('BA101_Q071', 'Một người tiêu dùng chi tiêu hết thu nhập cho hai hàng hóa X và Y. Hiện tại MUx / Px = 8 và MUy / Py = 5. Để tối đa hóa lợi ích, người này nên:', 'HARD', ['Tăng mua Y, giảm mua X', 'Tăng mua X và giảm mua Y (chuyển tiền từ Y sang X vì 1 đồng chi cho X mang lại nhiều lợi ích hơn)', 'Giữ nguyên tiêu dùng', 'Ngừng mua cả 2'], 1, 'CLO3'),
  q('BA101_Q072', 'Nếu một hàng hóa có đường bàng quan là các đoạn thẳng dốc xuống có độ dốc cố định (MRS không đổi), hai hàng hóa đó là:', 'HARD', ['Hai hàng hóa bổ sung hoàn hảo', 'Hai hàng hóa thay thế hoàn hảo cho nhau (Perfect Substitutes)', 'Hàng hóa độc lập', 'Hàng hóa Giffen'], 1, 'CLO3'),
  q('BA101_Q073', 'Hai hàng hóa có đường bàng quan hình chữ L vuông góc (L-shaped) là ví dụ điển hình của:', 'HARD', ['Hai hàng hóa thay thế hoàn hảo', 'Hai hàng hóa bổ sung hoàn hảo (ví dụ: chiếc giày trái và chiếc giày phải)', 'Hàng hóa xa xỉ', 'Hàng hóa thứ cấp'], 1, 'CLO3'),
  q('BA101_Q074', 'Đường tiêu dùng theo thu nhập (Income-Consumption Curve - ICC) kết nối các điểm cân bằng tiêu dùng khi thu nhập thay đổi là cơ sở để xây dựng đường nào?', 'HARD', ['Đường cầu thị trường', 'Đường Engel (biểu diễn mối quan hệ giữa thu nhập và lượng cầu hàng hóa)', 'Đường Phillips', 'Đường tổng chi phí'], 1, 'CLO3'),
  q('BA101_Q075', 'Khi một doanh nghiệp tăng gấp 3 lần cả vốn K và lao động L mà sản lượng đầu ra tăng gấp 4 lần, đường chi phí trung bình dài hạn (LRAC) sẽ:', 'HARD', ['Dốc lên', 'Dốc xuống (Lợi thế kinh tế nhờ quy mô - Economies of Scale)', 'Nằm ngang', 'Thẳng đứng'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA101_Q076', 'Phương trình Slutsky phân rã tổng tác động của sự thay đổi giá cả (Total Price Effect) thành hai thành phần nào?', 'EXPERT', ['Tác động lạm phát và tác động thất nghiệp', 'Tác động thay thế (Substitution Effect) và Tác động thu nhập (Income Effect)', 'Tác động cố định và biến đổi', 'Tác động ngắn hạn và dài hạn'], 1, 'CLO4'),
  q('BA101_Q077', 'Độ co giãn thay thế giữa các yếu tố sản xuất (Elasticity of Substitution - σ) đo lường điều gì?', 'EXPERT', ['Tỷ lệ % thay đổi của tỷ lệ K/L chia cho tỷ lệ % thay đổi của MRTS_LK dọc theo một đường đồng sản lượng', 'Tốc độ tăng trưởng doanh thu', 'Chi phí cận biên', 'Lợi nhuận gộp'], 0, 'CLO4'),
  q('BA101_Q078', 'Nguyên lý Bộc lộ sở thích (Revealed Preference Theory) của Paul Samuelson xây dựng lý thuyết người tiêu dùng dựa trên cơ sở nào?', 'EXPERT', ['Giả định người tiêu dùng có bảng đo thỏa dụng chính xác bằng số', 'Quan sát hành vi mua sắm thực tế của người tiêu dùng trên thị trường khi giá cả và thu nhập thay đổi thay vì dựa vào khái niệm thỏa dụng trừu tượng', 'Khảo sát ý kiến người mua qua phiếu điều tra', 'Đo điện não đồ'], 1, 'CLO4'),
  q('BA101_Q079', 'Hàm thỏa dụng gián tiếp (Indirect Utility Function - V(P, I)) thể hiện:', 'EXPERT', ['Lợi ích cận biên nhỏ nhất', 'Mức thỏa dụng tối đa mà người tiêu dùng có thể đạt được như một hàm phụ thuộc trực tiếp vào vectơ giá cả P và mức thu nhập I', 'Tổng số tiền người tiêu dùng đã tiết kiệm', 'Hàm chi phí của doanh nghiệp'], 1, 'CLO4'),
  q('BA101_Q080', 'Bổ đề Shephard (Shephard\'s Lemma) trong lý thuyết sản xuất phát biểu rằng đạo hàm riêng của hàm chi phí theo giá của yếu tố đầu vào (ví dụ: ∂C/∂w) chính là:', 'EXPERT', ['Mức lợi nhuận cực đại', 'Hàm cầu có điều kiện đối với yếu tố đầu vào đó (Lao động L*)', 'Sản lượng đầu ra Q', 'Độ dốc của đường cung'], 1, 'CLO4')
];

// ĐỀ GỐC 3 (40 câu): Chi phí sản xuất, Cấu trúc thị trường, Cạnh tranh hoàn hảo, Độc quyền & Thất bại thị trường
const root3 = [
  // Nhận biết (10 câu)
  q('BA101_Q081', 'Chi phí cố định (Fixed Cost - FC) là loại chi phí có đặc điểm gì trong ngắn hạn?', 'EASY', ['Thay đổi tỷ lệ thuận với sản lượng sản xuất', 'Không thay đổi theo mức sản lượng đầu ra (phát sinh ngay cả khi sản lượng Q = 0, ví dụ: tiền thuê mặt bằng, khấu hao máy móc)', 'Chi phí mua nguyên vật liệu', 'Chỉ phát sinh khi làm thêm giờ'], 1, 'CLO1'),
  q('BA101_Q082', 'Chi phí biến đổi (Variable Cost - VC) là chi phí:', 'EASY', ['Luôn cố định theo năm', 'Biến đổi phụ thuộc trực tiếp vào mức sản lượng sản xuất của doanh nghiệp (ví dụ: tiền lương công nhân trực tiếp, tiền mua nguyên liệu)', 'Tiền đóng bảo hiểm', 'Lãi vay ngân hàng cố định'], 1, 'CLO1'),
  q('BA101_Q083', 'Chi phí cận biên (Marginal Cost - MC) được định nghĩa là:', 'EASY', ['Tổng chi phí chia cho tổng sản lượng', 'Chi phí tăng thêm để sản xuất thêm một đơn vị sản phẩm đầu ra (MC = ΔTC / ΔQ = ΔVC / ΔQ)', 'Chi phí cố định bình quân', 'Chi phí cơ hội bị mất'], 1, 'CLO1'),
  q('BA101_Q084', 'Thị trường cạnh tranh hoàn hảo (Perfect Competition) có đặc điểm cốt lõi nào?', 'EASY', ['Chỉ có 1 người bán duy nhất kiểm soát giá', 'Có vô số người mua và người bán, sản phẩm hoàn toàn đồng nhất, thông tin hoàn hảo, tự do gia nhập và rút lui khỏi ngành', 'Các hãng cạnh tranh bằng quảng cáo khốc liệt', 'Chính phủ ấn định sản lượng'], 1, 'CLO1'),
  q('BA101_Q085', 'Trong thị trường cạnh tranh hoàn hảo, doanh nghiệp là người:', 'EASY', ['Định giá (Price Setter)', 'Chấp nhận giá (Price Taker - phải bán theo giá thị trường P do cung cầu quyết định)', 'Kiểm soát nguồn cung', 'Thương lượng giá theo hợp đồng'], 1, 'CLO1'),
  q('BA101_Q086', 'Đối với hãng cạnh tranh hoàn hảo, Doanh thu cận biên (MR) luôn bằng với đại lượng nào?', 'EASY', ['Bằng chi phí cố định FC', 'Bằng chính mức giá bán thị trường (MR = P)', 'Bằng 0', 'Bằng tổng chi phí TC'], 1, 'CLO1'),
  q('BA101_Q087', 'Thị trường độc quyền thuần túy (Monopoly) có đặc trưng nào sau đây?', 'EASY', ['Có rất nhiều doanh nghiệp cạnh tranh', 'Chỉ có duy nhất một nhà sản xuất / cung ứng toàn bộ sản phẩm trên thị trường, sản phẩm không có hàng hóa thay thế gần gũi, rào cản gia nhập ngành rất cao', 'Sản phẩm hoàn toàn miễn phí', 'Giá bán luôn bằng chi phí cận biên'], 1, 'CLO1'),
  q('BA101_Q088', 'Ngoại ứng tiêu cực (Negative Externality, ví dụ: ô nhiễm môi trường do nhà máy xả thải) dẫn đến hậu quả gì cho thị trường tự do?', 'EASY', ['Thị trường sản xuất ít hơn mức tối ưu xã hội', 'Thị trường tự do có xu hướng sản xuất quá mức sản lượng tối ưu của toàn xã hội (Overproduction) do chi phí cá nhân nhỏ hơn chi phí xã hội', 'Người dân được bồi thường tự động', 'Không ảnh hưởng tới ai'], 1, 'CLO1'),
  q('BA101_Q089', 'Hàng hóa công cộng thuần túy (Pure Public Goods, ví dụ: quốc phòng, hải đăng) có hai đặc tính cơ bản là:', 'EASY', ['Đắt tiền và khan hiếm', 'Không có tính cạnh tranh trong tiêu dùng (Non-rivalrous) và Không có tính loại trừ (Non-excludable)', 'Chỉ do tư nhân sản xuất', 'Có thể bán vé thu tiền dễ dàng'], 1, 'CLO1'),
  q('BA101_Q090', 'Nguyên tắc vàng để tối đa hóa lợi nhuận (Profit Maximization) áp dụng cho MỌI loại hình doanh nghiệp là sản xuất tại mức sản lượng mà tại đó:', 'EASY', ['Doanh thu cực đại', 'Doanh thu cận biên bằng Chi phí cận biên (MR = MC)', 'Giá bán P cao nhất', 'Chi phí bình quân ATC thấp nhất'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('BA101_Q091', 'Đường Chi phí cận biên (MC) luôn cắt đường Chi phí trung bình (ATC) và Chi phí biến đổi trung bình (AVC) tại điểm nào?', 'MEDIUM', ['Điểm đầu tiên', 'Điểm cực tiểu (thấp nhất) của các đường ATC và AVC', 'Điểm cực đại', 'Điểm cắt trục tung'], 1, 'CLO2'),
  q('BA101_Q092', 'Trong ngắn hạn, điều kiện để một hãng cạnh tranh hoàn hảo quyết định ĐÓNG CỬA sản xuất ngay lập tức (Shutdown Rule) là khi:', 'MEDIUM', ['Lợi nhuận bị âm', 'Mức giá thị trường giảm xuống dưới mức chi phí biến đổi trung bình cực tiểu (P < AVC_min)', 'Giá thị trường thấp hơn ATC', 'Doanh thu không bù đắp được chi phí cố định FC'], 1, 'CLO2'),
  q('BA101_Q093', 'Nếu giá thị trường nằm trong khoảng `AVC_min < P < ATC_min`, doanh nghiệp cạnh tranh hoàn hảo nên hành động như thế nào trong ngắn hạn?', 'MEDIUM', ['Đóng cửa giải thể ngay lập tức', 'Tiếp tục sản xuất trong ngắn hạn dù bị lỗ, vì doanh thu vẫn bù đắp được toàn bộ chi phí biến đổi VC và còn dư một phần để bù đắp chi phí cố định FC (giảm bớt mức lỗ so với đóng cửa)', 'Tăng giá bán lên gấp đôi', 'Vay nợ ngân hàng'], 1, 'CLO2'),
  q('BA101_Q094', 'Đường cung ngắn hạn của một doanh nghiệp cạnh tranh hoàn hảo chính là:', 'MEDIUM', ['Toàn bộ đường chi phí trung bình ATC', 'Phần đường Chi phí cận biên (MC) nằm phía trên điểm cực tiểu của đường Chi phí biến đổi trung bình (AVC_min)', 'Đường nằm ngang tại mức giá P', 'Đường chi phí cố định'], 1, 'CLO2'),
  q('BA101_Q095', 'Trong dài hạn, sự tự do gia nhập và rút lui khỏi ngành của thị trường cạnh tranh hoàn hảo sẽ dẫn đến kết quả cân bằng dài hạn nào?', 'MEDIUM', ['Các hãng thu được siêu lợi nhuận', 'Lợi nhuận kinh tế của các hãng bằng 0 (P = ATC_min), các hãng chỉ thu được lợi nhuận thông thường (Normal Profit)', 'Ngành bị độc quyền hóa', 'Tất cả các hãng đều phá sản'], 1, 'CLO2'),
  q('BA101_Q096', 'Tại sao đối với nhà độc quyền thuần túy, đường Doanh thu cận biên (MR) luôn nằm phía dưới đường Cầu (P)?', 'MEDIUM', ['Vì nhà độc quyền bị đánh thuế cao', 'Để bán thêm được một đơn vị sản lượng, nhà độc quyền phải hạ giá bán của toàn bộ tất cả các đơn vị sản phẩm trước đó (khi không phân biệt giá)', 'Vì chi phí sản xuất bằng 0', 'Do quy luật cung'], 1, 'CLO2'),
  q('BA101_Q097', 'Mức độ sức mạnh độc quyền được đo lường bằng Chỉ số Lerner (Lerner Index: L) có công thức là:', 'MEDIUM', ['L = (P - MC) / P = 1 / |Ed|', 'L = P / MC', 'L = TR - TC', 'L = P * Q'], 0, 'CLO2'),
  q('BA101_Q098', 'Phân biệt giá cấp 1 (First-degree Price Discrimination / Hoàn hảo) của nhà độc quyền là hình thức định giá như thế nào?', 'MEDIUM', ['Giảm giá cho khách mua nhiều', 'Định giá bán cho mỗi khách hàng đúng bằng mức giá tối đa mà người đó sẵn sàng chi trả (sát mức giá đặt), chiếm đoạt toàn bộ thặng dư tiêu dùng chuyển thành lợi nhuận', 'Bán giá khác nhau theo khu vực địa lý', 'Bán đồng giá cho mọi người'], 1, 'CLO2'),
  q('BA101_Q099', 'Phân biệt giá cấp 3 (Third-degree Price Discrimination) dựa trên cơ sở phân chia khách hàng theo tiêu chí nào?', 'MEDIUM', ['Phân nhóm khách hàng thành các thị trường riêng biệt có độ co giãn của cầu theo giá khác nhau (ví dụ: vé xem phim giảm giá cho sinh viên, giá vé máy bay hạng thương gia)', 'Ngẫu nhiên', 'Theo thời gian trong ngày', 'Theo số lượng mua sỉ'], 0, 'CLO2'),
  q('BA101_Q100', 'Thị trường Độc quyền nhóm (Oligopoly) có đặc điểm chiến lược nổi bật nào?', 'MEDIUM', ['Các hãng hành động hoàn toàn độc lập', 'Tính phụ thuộc lẫn nhau mang tính chiến lược (Mutual Interdependence): Quyết định về giá và sản lượng của một hãng ảnh hưởng sâu sắc tới phản ứng của các đối thủ cạnh tranh', 'Không có rào cản gia nhập', 'Sản phẩm luôn giống nhau 100%'], 1, 'CLO2'),
  q('BA101_Q101', 'Mô hình Đường cầu gãy (Kinked Demand Curve) của Sweezy giải thích hiện tượng kinh tế nào trong thị trường độc quyền nhóm?', 'MEDIUM', ['Giá cả biến động liên tục từng giờ', 'Tính cứng nhắc / ổn định của giá cả (Price Rigidity), các hãng ngại thay đổi giá vì sợ đối thủ chỉ bám theo khi hạ giá mà không bám theo khi tăng giá', 'Doanh nghiệp liên tục phá sản', 'Cạnh tranh hoàn hảo'], 1, 'CLO2'),
  q('BA101_Q102', 'Cân bằng Nash (Nash Equilibrium) trong Lý thuyết trò chơi (Game Theory) đạt được khi:', 'MEDIUM', ['Tất cả người chơi đều bị lỗ', 'Mỗi người chơi lựa chọn chiến lược tốt nhất cho mình dựa trên chiến lược mà đối thủ đã chọn, và không ai có động cơ đơn phương thay đổi chiến lược', 'Chính phủ ra lệnh chọn chiến lược', 'Một người thắng tất cả'], 1, 'CLO2'),
  q('BA101_Q103', 'Tình thế "Lưỡng nan của tù nhân" (Prisoner\'s Dilemma) chứng minh nghịch lý nào trong kinh tế học?', 'MEDIUM', ['Hợp tác luôn tự động diễn ra', 'Hành vi theo đuổi lợi ích cá nhân thuần túy của các bên có thể dẫn tới một kết quả cân bằng kém hiệu quả cho cả hai bên so với việc hợp tác ngầm', 'Người phạm tội luôn được tha bổng', 'Cảnh sát không có bằng chứng'], 1, 'CLO2'),
  q('BA101_Q104', 'Giải pháp can thiệp của chính phủ đối với doanh nghiệp tạo ra Ngoại ứng tiêu cực (Negative Externality) là:', 'MEDIUM', ['Trợ cấp sản xuất', 'Đánh thuế Pigou (Pigovian Tax) đúng bằng mức chi phí thiệt hại ngoại ứng biên (MEC) để đưa chi phí tư nhân về bằng chi phí xã hội', 'Bỏ qua không xử lý', 'Cấp độc quyền'], 1, 'CLO2'),
  q('BA101_Q105', 'Vấn đề Kẻ ăn không / Kẻ đi xe miễn phí (Free-rider Problem) phát sinh đối với hàng hóa nào?', 'MEDIUM', ['Hàng hóa tư nhân', 'Hàng hóa công cộng (Public Goods), do đặc tính không thể loại trừ khiến mọi người đều có động cơ hưởng thụ mà không chịu tự nguyện chi trả tiền', 'Hàng hóa xa xỉ', 'Dịch vụ viễn thông'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('BA101_Q106', 'Một hãng cạnh tranh hoàn hảo có hàm chi phí TC = Q^2 + 10Q + 100. Khi giá thị trường P = 50, mức sản lượng tối ưu để hãng tối đa hóa lợi nhuận là:', 'HARD', ['Q = 10', 'Q = 20 (giải MC = 2Q + 10 = P = 50 => 2Q = 40 => Q = 20)', 'Q = 30', 'Q = 15'], 1, 'CLO3'),
  q('BA101_Q107', 'Với hãng có TC = Q^2 + 10Q + 100 tại mức sản lượng tối ưu Q = 20 và giá P = 50, lợi nhuận cực đại của hãng đạt được là:', 'HARD', ['200', '300 (TR = 50 * 20 = 1000; TC = 20^2 + 10(20) + 100 = 700 => Lợi nhuận = 1000 - 700 = 300)', '500', '100'], 1, 'CLO3'),
  q('BA101_Q108', 'Một nhà độc quyền đối diện với đường cầu thị trường P = 100 - Q và có chi phí cận biên không đổi MC = 20. Mức giá và sản lượng tối đa hóa lợi nhuận là:', 'HARD', ['P = 50, Q = 50', 'P = 60, Q = 40 (MR = 100 - 2Q = MC = 20 => 2Q = 80 => Q = 40; thế vào P = 100 - 40 = 60)', 'P = 20, Q = 80', 'P = 70, Q = 30'], 1, 'CLO3'),
  q('BA101_Q109', 'Lợi nhuận kinh tế tối đa của nhà độc quyền trong câu trên (với FC = 100) là bao nhiêu?', 'HARD', ['1500 (TR = 60 * 40 = 2400; TC = 20 * 40 + 100 = 900 => Lợi nhuận = 1500)', '1600', '800', '1200'], 0, 'CLO3'),
  q('BA101_Q110', 'Tổn thất xã hội (Deadweight Loss - DWL) gây ra bởi nhà độc quyền (P = 100 - Q, MC = 20) so với mức sản lượng cạnh tranh hoàn hảo (P = MC) là:', 'HARD', ['DWL = (60 - 20) * (80 - 40) / 2 = 800', 'DWL = 400', 'DWL = 1600', 'DWL = 200'], 0, 'CLO3'),
  q('BA101_Q111', 'Một doanh nghiệp có hàm tổng chi phí TC = 2Q^3 - 12Q^2 + 40Q. Điểm hòa vốn (Break-even point) của doanh nghiệp đạt được tại mức sản lượng Q bằng:', 'HARD', ['Q = 2', 'Q = 3 (tìm cực tiểu của ATC = 2Q^2 - 12Q + 40, đạo hàm = 4Q - 12 = 0 => Q = 3)', 'Q = 4', 'Q = 6'], 1, 'CLO3'),
  q('BA101_Q112', 'Mô hình Độc quyền nhóm Cournot (hai hãng cạnh tranh về sản lượng đồng thời) dẫn tới kết quả sản lượng ngành so với cạnh tranh hoàn hảo và độc quyền là:', 'HARD', ['Lớn hơn cạnh tranh hoàn hảo', 'Nằm ở khoảng giữa: Lớn hơn mức sản lượng độc quyền thuần túy nhưng nhỏ hơn mức sản lượng cạnh tranh hoàn hảo', 'Bằng chính xác độc quyền', 'Nhỏ hơn độc quyền'], 1, 'CLO3'),
  q('BA101_Q113', 'Trong mô hình Stackelberg (hai hãng cạnh tranh sản lượng, hãng 1 đi trước làm Leader, hãng 2 đi sau làm Follower), hãng nào sẽ có lợi thế vượt trội?', 'HARD', ['Hãng đi sau (Follower)', 'Hãng đi trước (Leader) có lợi thế tiên phong, chiếm thị phần lớn hơn và thu được lợi nhuận cao hơn hãng đi sau', 'Hai hãng chia đều thị phần', 'Không hãng nào có lợi'], 1, 'CLO3'),
  q('BA101_Q114', 'Một nhà máy gây ô nhiễm có chi phí cận biên tư nhân MPC = 10 + 2Q và chi phí thiệt hại ngoại ứng MEC = 0.5Q. Chi phí cận biên xã hội (MSC) bằng bao nhiêu?', 'HARD', ['MSC = 10 + 1.5Q', 'MSC = MPC + MEC = 10 + 2.5Q', 'MSC = 2.5Q', 'MSC = 10 - 2Q'], 1, 'CLO3'),
  q('BA101_Q115', 'Chính sách Định giá theo chi phí cận biên (P = MC) áp dụng cho độc quyền tự nhiên (Natural Monopoly có chi phí trung bình giảm liên tục) sẽ dẫn đến:', 'HARD', ['Hãng thu siêu lợi nhuận', 'Hãng bị thua lỗ vì P = MC < ATC, do đó nhà nước phải thực hiện bù lỗ cho doanh nghiệp', 'Hãng đạt cân bằng hoàn hảo không lỗ', 'Hãng tăng giá tự do'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('BA101_Q116', 'Hiện tượng Thông tin bất đối xứng (Asymmetric Information) trên thị trường dẫn đến hai vấn đề nghiêm trọng nào?', 'EXPERT', ['Lạm phát và thất nghiệp', 'Lựa chọn nghịch (Adverse Selection) xảy ra trước khi ký hợp đồng và Rủi ro đạo đức (Moral Hazard) xảy ra sau khi ký hợp đồng', 'Độc quyền và phá sản', 'Thiếu hụt và dư thừa'], 1, 'CLO4'),
  q('BA101_Q117', 'Bài toán Thị trường cho những quả chanh ("The Market for Lemons" của George Akerlof) giải thích hiện tượng nào trên thị trường xe cũ?', 'EXPERT', ['Người mua xe luôn mua được xe tốt giá rẻ', 'Sự bất đối xứng thông tin về chất lượng xe khiến xe kém chất lượng (lemon) dần dần đánh bật hoàn toàn xe tốt (peach) ra khỏi thị trường, thậm chí làm sụp đổ thị trường', 'Giá xe tăng phi mã', 'Thị trường tự điều tiết hoàn hảo'], 1, 'CLO4'),
  q('BA101_Q118', 'Cơ chế Tín hiệu hóa (Signaling của Michael Spence) giúp giải quyết vấn đề lựa chọn nghịch trong tuyển dụng lao động bằng cách nào?', 'EXPERT', ['Người lao động chấp nhận lương bằng 0', 'Ứng viên có năng lực cao sử dụng bằng cấp đại học xuất sắc như một tín hiệu đáng tin cậy để chứng minh năng suất lao động với nhà tuyển dụng vì chi phí đạt bằng cấp này với họ thấp hơn người năng lực kém', 'Nhà nước bắt buộc nhận mọi ứng viên', 'Bỏ qua phỏng vấn'], 1, 'CLO4'),
  q('BA101_Q119', 'Định lý Cạnh tranh Bertrand (Bertrand Paradox) phát biểu rằng hai hãng độc quyền nhóm cạnh tranh về GIÁ với sản phẩm đồng nhất và MC không đổi sẽ dẫn tới:', 'EXPERT', ['Cả 2 hãng bán giá độc quyền', 'Cuộc chiến giá đẩy giá bán tụt dốc về đúng bằng Chi phí cận biên (P = MC), lợi nhuận kinh tế bằng 0 như thị trường cạnh tranh hoàn hảo', 'Hai hãng sáp nhập', 'Giá tiến về vô cùng'], 1, 'CLO4'),
  q('BA101_Q120', 'Chỉ số Herfindahl-Hirschman (HHI) dùng trong quản lý cạnh tranh và chống độc quyền được tính bằng:', 'EXPERT', ['Tổng thị phần của 4 hãng lớn nhất', 'Tổng bình phương thị phần của tất cả các hãng trong ngành (HHI = Σ s_i^2), giá trị càng lớn thì mức độ tập trung thị trường càng cao', 'Tỷ lệ nợ trên vốn', 'Doanh thu trung bình'], 1, 'CLO4')
];

module.exports = {
  course: {
    code: 'BA101',
    name: 'Kinh Tế Vi Mô',
    faculty: 'Khoa Kinh Tế & QTKD',
    category_code: 'CAT-BA101',
    credits: 3
  },
  root_1: root1,
  root_2: root2,
  root_3: root3,
  getAllQuestions: () => [...root1, ...root2, ...root3]
};
