// backend/services/examBank/eng101.bank.js
// Ngân hàng câu hỏi chuẩn hóa: ENG101 — Tiếng Anh Học Thuật 1 (Academic English B1)
// Tổng cộng: 120 câu hỏi (3 Đề gốc x 40 câu hỏi)
'use strict';

function q(id, content, difficulty, answers, correctIdx, clo = 'CLO1') {
  return {
    id,
    course_code: 'ENG101',
    content,
    difficulty,
    default_mark: 0.25,
    clo,
    answers: answers.map((text, idx) => ({
      id: `${id}_A${idx + 1}`,
      letter: ['A', 'B', 'C', 'D'][idx],
      content: text,
      is_correct: idx === correctIdx,
      fraction: idx === correctIdx ? 1.0 : 0.0
    }))
  };
}

// ĐỀ GỐC 1 (40 câu): Academic Vocabulary (AWL), Grammar in Academic Contexts, Passive Voice, Complex Sentences
const root1 = [
  // Nhận biết (10 câu)
  q('ENG101_Q001', 'Choose the word that best completes the sentence: "The researchers gathered empirical _______ to support their original hypothesis."', 'EASY', ['evidence', 'rumors', 'opinions', 'emotions'], 0, 'CLO1'),
  q('ENG101_Q002', 'What is the correct noun form of the verb "analyse" in academic writing?', 'EASY', ['analysation', 'analysis', 'analytic', 'analyser'], 1, 'CLO1'),
  q('ENG101_Q003', 'Identify the passive voice sentence among the following:', 'EASY', ['The scientist conducted the experiment in June.', 'The survey was distributed to over 500 undergraduate students.', 'Students should submit their assignments on Friday.', 'The professor lectured for two hours.'], 1, 'CLO1'),
  q('ENG101_Q004', 'Choose the correct preposition: "The study focused primarily _______ the correlation between sleep quality and academic performance."', 'EASY', ['at', 'on', 'with', 'in'], 1, 'CLO1'),
  q('ENG101_Q005', 'Which of the following is a subordinating conjunction indicating contrast?', 'EASY', ['Moreover', 'Furthermore', 'Although', 'Therefore'], 2, 'CLO1'),
  q('ENG101_Q006', 'Select the synonym for the academic word "significant":', 'EASY', ['trivial', 'meaningful / substantial', 'uncertain', 'accidental'], 1, 'CLO1'),
  q('ENG101_Q007', 'In formal academic English, which phrase is preferred over "a lot of"?', 'EASY', ['heaps of', 'tons of', 'a considerable amount of / numerous', 'loads of'], 2, 'CLO1'),
  q('ENG101_Q008', 'Which verb tense is typically used in academic abstracts to state universally established scientific facts?', 'EASY', ['Past continuous', 'Present simple', 'Past perfect', 'Future perfect'], 1, 'CLO1'),
  q('ENG101_Q009', 'Select the correct adjective form of "significance":', 'EASY', ['signify', 'significantly', 'significant', 'signification'], 2, 'CLO1'),
  q('ENG101_Q010', 'Choose the suitable modal verb for cautious academic hedging: "The observed data _______ indicate a potential trend."', 'EASY', ['must', 'will definitively', 'may / might', 'should undoubtedly'], 2, 'CLO1'),

  // Thông hiểu (15 câu)
  q('ENG101_Q011', 'Complete the sentence: "Neither the principal investigator nor the lab assistants _______ aware of the equipment malfunction."', 'MEDIUM', ['was', 'were', 'is', 'be'], 1, 'CLO2'),
  q('ENG101_Q012', 'Choose the correct relative pronoun: "The methodology _______ was adopted in this paper follows international standards."', 'MEDIUM', ['who', 'which / that', 'whom', 'whose'], 1, 'CLO2'),
  q('ENG101_Q013', 'Why is the passive voice frequently utilized in academic methodology sections?', 'MEDIUM', ['Because it uses fewer words', 'To place objective emphasis on the research process and results rather than the individual researcher', 'To confuse readers', 'Because active voice is grammatically incorrect in English'], 1, 'CLO2'),
  q('ENG101_Q014', 'Select the best academic replacement for the informal phrasal verb "find out":', 'MEDIUM', ['discover / determine', 'look into', 'bring up', 'figure out'], 0, 'CLO2'),
  q('ENG101_Q015', 'Choose the word that means "to make something possible or easier" from the Academic Word List (AWL):', 'MEDIUM', ['facilitate', 'hinder', 'complicate', 'deteriorate'], 0, 'CLO2'),
  q('ENG101_Q016', 'Identify the complex sentence among the options:', 'MEDIUM', ['The team analyzed the data, and they published the report.', 'Because initial trials failed, the engineers revised the algorithm.', 'The library is open from 8 AM to 9 PM.', 'Read the instructions carefully and begin.'], 1, 'CLO2'),
  q('ENG101_Q017', 'Complete the conditional sentence: "If renewable energy sources _______ more widely adopted, global emissions would decrease significantly."', 'MEDIUM', ['are', 'were', 'will be', 'had been'], 1, 'CLO2'),
  q('ENG101_Q018', 'Select the antonym of the academic word "consistent":', 'MEDIUM', ['coherent', 'incompatible / contradictory', 'reliable', 'constant'], 1, 'CLO2'),
  q('ENG101_Q019', 'What is the function of the transition word "consequently" in an academic passage?', 'MEDIUM', ['To introduce an opposing point of view', 'To demonstrate a direct result or causal effect of the preceding statement', 'To provide a chronological timeline', 'To introduce a personal anecdote'], 1, 'CLO2'),
  q('ENG101_Q020', 'Choose the correct form: "A large percentage of the university budget _______ allocated to digital library resources annually."', 'MEDIUM', ['is', 'are', 'were', 'have been'], 0, 'CLO2'),
  q('ENG101_Q021', 'Select the sentence that maintains an objective, formal academic tone:', 'MEDIUM', ['I think this software is awesome and super fast.', 'The experimental results demonstrate that the new algorithm operates with greater computational efficiency.', 'You can easily see that the numbers are huge.', 'We got really lucky with the lab results.'], 1, 'CLO2'),
  q('ENG101_Q022', 'Which collocation is widely accepted in academic literature?', 'MEDIUM', ['do an experiment / perform an experiment', 'make an experiment', 'create a research', 'produce a hypothesis'], 0, 'CLO2'),
  q('ENG101_Q023', 'Choose the correct word: "The primary _______ of this investigation is to examine urban heat island effects."', 'MEDIUM', ['objective / aim', 'hobby', 'wish', 'fancy'], 0, 'CLO2'),
  q('ENG101_Q024', 'Complete the sentence: "Despite _______ numerous technical obstacles, the research team completed the prototype on schedule."', 'MEDIUM', ['encounter', 'encountered', 'encountering', 'to encounter'], 2, 'CLO2'),
  q('ENG101_Q025', 'What does the term "peer-reviewed journal" signify?', 'MEDIUM', ['A magazine written by students', 'An academic publication in which submitted articles are critically evaluated by independent experts in the field prior to publication', 'A daily newspaper', 'A non-scholarly blog'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('ENG101_Q026', 'Identify the error in parallel structure: "The study involved collecting data, analyzing samples, and to interview participants."', 'HARD', ['collecting data', 'analyzing samples', '"to interview participants" (should be "interviewing participants")', 'The study involved'], 2, 'CLO3'),
  q('ENG101_Q027', 'Rewrite into formal academic style: "They set up the machine to see what happens when it gets super hot."', 'HARD', ['The machine was tested to look at heat.', 'The apparatus was calibrated to examine thermal behavior under extreme temperatures.', 'They ran the hot test.', 'The system was heated up a whole bunch.'], 1, 'CLO3'),
  q('ENG101_Q028', 'Choose the correct hedging phrase to replace the overgeneralized statement: "All social media users suffer from severe depression."', 'HARD', ['Evidence suggests that extensive social media usage may be associated with increased risks of depressive symptoms in certain cohorts.', 'Nobody doubts that social media ruins happiness.', 'It is 100% certain that social media causes despair.', 'All people are definitely sad.'], 0, 'CLO3'),
  q('ENG101_Q029', 'Complete with the appropriate participle clause: "_______ by international financial institutions, the development project commenced in January."', 'HARD', ['Funding', 'Funded', 'Having funded', 'To fund'], 1, 'CLO3'),
  q('ENG101_Q030', 'Which of the following sentences correctly utilizes an inverted conditional structure?', 'HARD', ['If had the researchers known, they would stop.', 'Had the researchers known the secondary effects, they would have modified the dosage.', 'Should the team know, they will change.', 'Were the data known, it changed.'], 1, 'CLO3'),
  q('ENG101_Q031', 'Choose the best word: "The correlation between socioeconomic status and educational achievement is well _______ in contemporary literature."', 'HARD', ['documented / established', 'imagined', 'invented', 'pretended'], 0, 'CLO3'),
  q('ENG101_Q032', 'Identify the sentence with correct subject-verb agreement involving collective nouns and percentages:', 'HARD', ['Seventy percent of the earth\'s surface are covered by water.', 'Seventy percent of the earth\'s surface is covered by water.', 'Ten miles are a long distance to walk.', 'The committee disagree on everything.'], 1, 'CLO3'),
  q('ENG101_Q033', 'Select the option that appropriately synthesizes two clauses using a non-defining relative clause: "Dr. Smith developed the algorithm. He received the Turing Award yesterday."', 'HARD', ['Dr. Smith, who developed the algorithm, received the Turing Award yesterday.', 'Dr. Smith that developed the algorithm received the award.', 'Dr. Smith which developed the algorithm got the prize.', 'Dr. Smith whose algorithm developed received it.'], 0, 'CLO3'),
  q('ENG101_Q034', 'Choose the appropriate connector: "The initial hypothesis was disproven; _______, the investigation yielded unexpected insights into cellular metabolism."', 'HARD', ['nevertheless / however', 'for instance', 'in other words', 'namely'], 0, 'CLO3'),
  q('ENG101_Q035', 'Select the sentence that avoids run-on errors (comma splices):', 'HARD', ['The sample size was inadequate, the results cannot be generalized.', 'The sample size was inadequate; therefore, the results cannot be generalized to the broader population.', 'The sample size was inadequate so the results cannot be generalized and nobody liked it.', 'The sample size was small, however we continued.'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('ENG101_Q036', 'In academic discourse, what distinguish "epistemic modality" (hedging) from "deontic modality"?', 'EXPERT', ['Epistemic modality relates to grammatical gender', 'Epistemic modality expresses degrees of possibility, likelihood, and certainty regarding knowledge claims (e.g., "suggests", "may indicate"), whereas deontic modality conveys obligation and permission (e.g., "must", "should")', 'They are identical', 'Deontic modality is only used in poetry'], 1, 'CLO4'),
  q('ENG101_Q037', 'Analyze the sentence: "It was not until the statistical anomaly was verified that the laboratory published the findings." What rhetorical device is employed here?', 'EXPERT', ['Simile', 'Cleft sentence structure (It-cleft) used to emphasize the exact timing of the verification', 'Chiasmus', 'Oxymoron'], 1, 'CLO4'),
  q('ENG101_Q038', 'What is the semantic distinction between "prescriptive grammar" and "descriptive grammar" in linguistics and academic English?', 'EXPERT', ['Prescriptive specifies strict rules for how language "should" be used correctly, while descriptive investigates and records how language is actually used by native speakers', 'Descriptive grammar is only for writing novels', 'Prescriptive grammar is outdated and illegal', 'There is no difference'], 0, 'CLO4'),
  q('ENG101_Q039', 'Identify the nominalization technique applied to convert: "Because the government implemented new regulations rapidly, the economy suffered."', 'EXPERT', ['"The economy became bad because of government stuff."', '"The rapid implementation of new governmental regulations adversely affected the economy."', '"They made rules fast so it hurt."', '"Regulations were fast, suffering happened."'], 1, 'CLO4'),
  q('ENG101_Q040', 'In academic corpus linguistics, what does the term "collocational strength" (e.g., measured via Mutual Information or t-score) indicate?', 'EXPERT', ['The volume of letters in a word', 'The statistical probability that two lexical items co-occur significantly more frequently than would be expected by random chance in academic texts', 'The speed of typing words', 'The rhyme scheme of a paragraph'], 1, 'CLO4')
];

// ĐỀ GỐC 2 (40 câu): Academic Reading Skills, Skimming, Scanning, Topic Sentences, Cohesion & Inferences
const root2 = [
  // Nhận biết (10 câu)
  q('ENG101_Q041', 'What is the primary objective of "skimming" an academic journal article?', 'EASY', ['To memorize every single statistical figure', 'To rapidly read through the headings, abstract, introduction, and conclusion to grasp the general gist or main idea', 'To find a specific phone number or year', 'To correct spelling errors'], 1, 'CLO1'),
  q('ENG101_Q042', 'What is "scanning" in academic reading techniques?', 'EASY', ['Reading the entire text aloud', 'Rapidly moving one\'s eyes across the text to locate specific pieces of information (such as a date, name, or statistic)', 'Translating the text word-by-word into Vietnamese', 'Summarizing the whole book'], 1, 'CLO1'),
  q('ENG101_Q043', 'Where is the "topic sentence" of an academic paragraph most commonly positioned?', 'EASY', ['At the very end of the paragraph only', 'At or near the beginning of the paragraph to introduce the central controlling idea', 'In a separate footnote', 'Randomly placed in the middle'], 1, 'CLO1'),
  q('ENG101_Q044', 'In academic reading, words such as "this, these, that, those, the former, the latter" are examples of:', 'EASY', ['Adverbs of frequency', 'Cohesive reference devices used to link back to previously mentioned ideas', 'Conjunctions of reason', 'Passive verbs'], 1, 'CLO1'),
  q('ENG101_Q045', 'An academic "abstract" functions as:', 'EASY', ['An advertisement for the author\'s book', 'A concise, standalone summary of the entire study, including background, methods, major findings, and conclusions', 'A list of references cited', 'A biography of the author'], 1, 'CLO1'),
  q('ENG101_Q046', 'Which section of an empirical research paper provides a critical interpretation of the findings in relation to existing literature?', 'EASY', ['Methodology', 'Discussion / Implications', 'Results only', 'Appendix'], 1, 'CLO1'),
  q('ENG101_Q047', 'What is the definition of "inference" in critical reading?', 'EASY', ['Copying the text word-for-word', 'Drawing a logical conclusion based on evidence and reasoning rather than on explicit statements', 'Ignoring unfamiliar terminology', 'Disagreeing with the author'], 1, 'CLO1'),
  q('ENG101_Q048', 'A statement such as "The global population reached 8 billion in November 2022" is an example of:', 'EASY', ['An unverified opinion', 'An empirical fact verifiable by demographic data', 'A speculative claim', 'A personal belief'], 1, 'CLO1'),
  q('ENG101_Q049', 'A statement such as "Online learning is far superior to traditional classroom lectures in all respects" represents:', 'EASY', ['A verifiable factual certainty', 'An opinion / subjective claim requiring balanced empirical substantiation', 'A mathematical formula', 'A legal statute'], 1, 'CLO1'),
  q('ENG101_Q050', 'What does the abbreviation "e.g." (exempli gratia) stand for in academic texts?', 'EASY', ['that is (in other words)', 'for example', 'and so forth', 'note well'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('ENG101_Q051', 'Read the sentence: "Although artificial intelligence has accelerated medical diagnostics, ethical concerns regarding algorithmic bias remain unresolved." What is the author\'s primary emphasis?', 'MEDIUM', ['AI should be banned in hospitals', 'Acknowledging AI benefits while highlighting the persistent gravity of ethical dilemmas and bias', 'Diagnostics has nothing to do with algorithms', 'Doctors will be replaced tomorrow'], 1, 'CLO2'),
  q('ENG101_Q052', 'When an academic author uses the phrase "on the other hand", what logical relationship is being signaled?', 'MEDIUM', ['A causal sequence', 'A contrasting perspective or counter-argument', 'An chronological summary', 'An identical repeating point'], 1, 'CLO2'),
  q('ENG101_Q053', 'In the sentence: "Urbanization has triggered deforestation; as a result, local biodiversity has plummeted." What is the cohesive relationship between the two clauses?', 'MEDIUM', ['Contrast', 'Cause and Effect (Causality)', 'Temporal sequence', 'Exemplification'], 1, 'CLO2'),
  q('ENG101_Q054', 'What technique should a student use to deduce the meaning of an unfamiliar word like "photosensitive" in context?', 'MEDIUM', ['Skip the entire paragraph', 'Analyze morphological word roots (photo = light, sensitive = reactive) and surrounding contextual clues', 'Look up every word in an English-Vietnamese dictionary immediately', 'Guess randomly'], 1, 'CLO2'),
  q('ENG101_Q055', 'What is the purpose of conducting a "Literature Review" (Tổng quan tài liệu) in an academic paper?', 'MEDIUM', ['To fill up page quota', 'To synthesize existing scholarly research, establish theoretical background, and identify research gaps that the present study addresses', 'To list all books in the university library', 'To review grammar errors'], 1, 'CLO2'),
  q('ENG101_Q056', 'Identify the primary organizational pattern of a text that discusses similarities and differences between SQL and NoSQL databases:', 'MEDIUM', ['Chronological timeline', 'Compare and Contrast structure', 'Problem-Solution pattern', 'Process narrative'], 1, 'CLO2'),
  q('ENG101_Q057', 'What is the main role of "supporting sentences" within a well-structured academic paragraph?', 'MEDIUM', ['To introduce completely unrelated topics', 'To provide evidence, data, examples, and detailed explanations that validate the controlling idea of the topic sentence', 'To restate the title of the book', 'To ask questions to the reader'], 1, 'CLO2'),
  q('ENG101_Q058', 'In academic writing, what does "authorial stance" / "voice" refer to?', 'MEDIUM', ['The physical posture of the author while typing', 'The author\'s perspective, attitude, and degree of commitment towards the claims and evidence presented in the text', 'The font style chosen for publication', 'The loudness of spoken delivery'], 1, 'CLO2'),
  q('ENG101_Q059', 'What does the Latin abbreviation "i.e." (id est) mean when used in academic reading passages?', 'MEDIUM', ['for example', 'that is / in other words (used to clarify or restate an idea)', 'and others', 'compare with'], 1, 'CLO2'),
  q('ENG101_Q060', 'If an author repeatedly uses qualifying terms such as "preliminary", "provisional", and "tentative", the tone of the research findings can be described as:', 'MEDIUM', ['Dogmatic and overconfident', 'Cautious, prudent, and measured (appropriate for early-stage empirical findings)', 'Aggressive and dismissive', 'Bored and disinterested'], 1, 'CLO2'),
  q('ENG101_Q061', 'Read the passage: "Solar panel production has dropped in cost by 80% over the decade. Concurrently, battery storage density has doubled." What can be inferred about the future of renewable energy adoption?', 'MEDIUM', ['Renewable energy will become less economically viable', 'Renewable energy is becoming increasingly cost-effective and practical for widespread commercial grid adoption', 'Coal plants will increase in price', 'Batteries will be phased out'], 1, 'CLO2'),
  q('ENG101_Q062', 'What is the role of an "Appendix" in a research paper?', 'MEDIUM', ['To list the author\'s social media links', 'To present supplementary materials (such as raw data tables, survey questionnaires, or mathematical proofs) that are too detailed for the main body', 'To apologize for mistakes', 'To replace the bibliography'], 1, 'CLO2'),
  q('ENG101_Q063', 'Which signal word indicates that an academic author is about to summarize or conclude an argument?', 'MEDIUM', ['In summary / In conclusion / To recapitulate', 'Furthermore', 'Initially', 'In contrast'], 0, 'CLO2'),
  q('ENG101_Q064', 'When reading a research table with statistical data, what does "p < 0.05" conventionally indicate in scientific disciplines?', 'MEDIUM', ['The experiment failed', 'The observed result is statistically significant and highly unlikely to have occurred purely by random chance (less than 5% probability)', 'The sample size was 5 people', 'The error rate is 95%'], 1, 'CLO2'),
  q('ENG101_Q065', 'Identify the cohesive device used in the following sentences: "Many researchers favor quantitative methodologies. However, proponents of qualitative research argue for deeper contextual nuance."', 'MEDIUM', ['Lexical repetition', 'Conjunctive adversative transition ("However") establishing contrast between two research camps', 'Pronoun reference', 'Ellipsis'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('ENG101_Q066', 'Read the excerpt: "While proponents champion smart cities for resource efficiency, critics highlight pervasive surveillance and algorithmic disenfranchisement." The primary structure of this excerpt is:', 'HARD', ['Pure chronological recounting', 'Dialectical / Counter-perspective contrast comparing divergent evaluative perspectives', 'Linear cause and effect', 'Anecdotal narrative'], 1, 'CLO3'),
  q('ENG101_Q067', 'An academic text states: "Only 12% of surveyed participants reported completing the online module, despite 94% possessing high-speed broadband." What is the implicit implication?', 'HARD', ['High-speed internet prevents study', 'Access to technological infrastructure alone is insufficient to guarantee learner engagement and course completion', 'Surveys are always inaccurate', 'The internet was disconnected'], 1, 'CLO3'),
  q('ENG101_Q068', 'Determine the purpose of the underlined rhetorical question in an academic monograph: "Can developing nations reconcile industrial modernization with net-zero carbon pledges?"', 'HARD', ['To test the reader\'s memory', 'To frame a central research question and engage the reader in exploring an intricate socio-economic dilemma', 'To show the author does not know the answer', 'To request an immediate answer via email'], 1, 'CLO3'),
  q('ENG101_Q069', 'In critical reading, what constitutes a "hasty generalization" fallacy?', 'HARD', ['Using proper APA citations', 'Drawing an overarching, universal conclusion based on an insufficiently small or unrepresentative sample size', 'Presenting statistical graphs', 'Using peer-reviewed sources'], 1, 'CLO3'),
  q('ENG101_Q070', 'Identify which sentence represents an author\'s concession before delivering a counter-argument:', 'HARD', ['"Granted, initial capital expenditures for geothermal energy are substantial; nonetheless, long-term operational returns far surpass fossil alternatives."', '"Geothermal energy is cheap and always easy."', '"Nobody should ever use coal."', '"Cost does not matter at all."'], 0, 'CLO3'),
  q('ENG101_Q071', 'Read the following paragraph excerpt: "First, water is filtered to remove particulates. Next, ultraviolet radiation eliminates pathogenic bacteria. Finally, minerals are reintroduced for taste." The organizational structure is:', 'HARD', ['Cause and effect', 'Sequential process / Chronological flow', 'Compare and contrast', 'Problem-solution'], 1, 'CLO3'),
  q('ENG101_Q072', 'What is the primary function of "hedging" in scientific conclusions (e.g., "The data tend to indicate...", "It appears probable that...")?', 'HARD', ['To conceal poor results', 'To express academic modesty and avoid unsubstantiated overclaiming, recognizing limitations in empirical data', 'To sound poetic', 'To lengthen the word count'], 1, 'CLO3'),
  q('ENG101_Q073', 'When an academic author cites contrasting studies (e.g., "While Author A found positive outcomes, Author B reported negligible differences"), what critical skill is being demonstrated?', 'HARD', ['Plagiarism', 'Scholarly synthesis and balanced evaluation of conflicting literature', 'Indecisiveness', 'Copy-pasting'], 1, 'CLO3'),
  q('ENG101_Q074', 'What constitutes an "ad hominem" fallacy in evaluative critiques?', 'HARD', ['Attacking an author\'s personal character or background rather than refuting their empirical arguments or evidence', 'Using Latin phrases', 'Calculating false averages', 'Submitting papers after the deadline'], 0, 'CLO3'),
  q('ENG101_Q075', 'In reading a scientific methodology, what is the role of a "Control Group" (Nhóm đối chứng)?', 'HARD', ['To control the budget', 'To serve as an untreated baseline comparison against which the experimental treatment group can be objectively measured', 'To instruct the researchers', 'To distribute snacks'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('ENG101_Q076', 'In advanced academic reading, what does "evaluating the provenance and epistemological framework" of a source entail?', 'EXPERT', ['Checking whether the paper has colorful pictures', 'Critically interrogating the author\'s institutional credibility, funding affiliations, underlying methodological paradigms, and peer validation', 'Translating the text into 3 languages', 'Printing the article on heavy paper'], 1, 'CLO4'),
  q('ENG101_Q077', 'What is the significance of distinguishing between "Correlation" and "Causation" in academic literature analysis?', 'EXPERT', ['They are interchangeable terms', 'Correlation merely indicates that two variables fluctuate together statistically, whereas causation requires empirical proof that variable X directly produces the change in variable Y', 'Correlation is qualitative while causation is always monetary', 'Causation only applies to physics'], 1, 'CLO4'),
  q('ENG101_Q078', 'Analyze the rhetorical purpose of "metadiscourse markers" (e.g., "In the next section, we will demonstrate...", "As noted earlier...") in long scholarly texts:', 'EXPERT', ['They act as conceptual roadmaps guiding the reader through the structural architecture and cognitive logic of the academic text', 'They exist purely to inflate word counts', 'They are required by law in the UK', 'They signal translation errors'], 0, 'CLO4'),
  q('ENG101_Q079', 'What is "confirmation bias" in the context of critical reading and systematic literature reviews?', 'EXPERT', ['Confirming the booking of a conference', 'The subconscious cognitive tendency to selectively search for, interpret, and favor information that confirms preexisting beliefs while disregarding disconfirming evidence', 'A positive peer-review score', 'Signing an agreement'], 1, 'CLO4'),
  q('ENG101_Q080', 'In quantitative research reading, what does the "Reproducibility Crisis" (Cuộc khủng hoảng khả năng tái lập) refer to?', 'EXPERT', ['Shortage of paper in university print shops', 'The alarming methodological finding that a significant proportion of published scientific studies cannot be replicated or verified by independent researchers replicating the original protocol', 'Failure of photocopy machines', 'Loss of digital passwords'], 1, 'CLO4')
];

// ĐỀ GỐC 3 (40 câu): Academic Writing & Study Skills, Paraphrasing, Avoiding Plagiarism, Referencing (APA), Lecture Note-taking
const root3 = [
  // Nhận biết (10 câu)
  q('ENG101_Q081', 'What is the definition of "Plagiarism" (Đạo văn) in higher education academia?', 'EASY', ['Failing an exam', 'Using another person\'s ideas, words, data, or intellectual work without appropriate attribution or citation, presenting them as one\'s own', 'Studying in a group', 'Submitting an assignment early'], 1, 'CLO1'),
  q('ENG101_Q082', 'What is "Paraphrasing" (Diễn giải lại)?', 'EASY', ['Translating a sentence with Google Translate without reading', 'Expressing the original author\'s meaning using one\'s own sentence structure and vocabulary while maintaining full accuracy and providing a citation', 'Copying text directly inside quotation marks', 'Deleting half of a paragraph'], 1, 'CLO1'),
  q('ENG101_Q083', 'According to standard APA 7th edition referencing style, what elements are included in an in-text parenthetical citation for a direct quote?', 'EASY', ['Author\'s last name, publication year, and page number (e.g., Smith, 2020, p. 45)', 'Author\'s first name and phone number', 'Title of the book only', 'URL link and date of download'], 0, 'CLO1'),
  q('ENG101_Q084', 'A well-constructed academic paragraph typically consists of three foundational components:', 'EASY', ['Title, image, and caption', 'Topic sentence, Supporting sentences (with evidence/analysis), and Concluding/Transition sentence', 'Questions, answers, and jokes', 'Introduction, 10 bullet points, and conclusion'], 1, 'CLO1'),
  q('ENG101_Q085', 'The Cornell Note-taking System divides a standard note page into which three sections?', 'EASY', ['Top, middle, and bottom thirds', 'Cue / Keyword column (left), Note-taking area (right), and Summary section (bottom)', 'Title page, body page, references', 'Rough draft, clean draft, final draft'], 1, 'CLO1'),
  q('ENG101_Q086', 'Which referencing style is predominant in the social sciences, psychology, and education?', 'EASY', ['IEEE style', 'APA style (American Psychological Association)', 'Chicago Footnotes style', 'MLA style for literature'], 1, 'CLO1'),
  q('ENG101_Q087', 'What is the function of a "Thesis Statement" in an academic essay or research paper?', 'EASY', ['To state the author\'s birth date', 'To articulate the central claim, argument, or overarching purpose of the entire essay in one or two clear sentences, typically located at the end of the introduction', 'To list the references', 'To thank parents and teachers'], 1, 'CLO1'),
  q('ENG101_Q088', 'When directly quoting a short excerpt (fewer than 40 words) in an APA paper, what punctuation is mandatory around the borrowed words?', 'EASY', ['Double quotation marks ("...")', 'Parentheses ((...))', 'Square brackets ([...])', 'No punctuation needed'], 0, 'CLO1'),
  q('ENG101_Q089', 'What is "self-plagiarism"?', 'EASY', ['Reading one\'s own diary', 'Submitting one\'s own previously published or graded academic work (in whole or in part) for a new assignment or course without authorization or citation', 'Studying alone', 'Writing in first person'], 1, 'CLO1'),
  q('ENG101_Q090', 'In formal academic writing, which of the following practices is strongly discouraged?', 'EASY', ['Using precise technical vocabulary', 'Using informal contractions (e.g., don\'t, can\'t, won\'t, it\'s)', 'Organizing ideas with topic sentences', 'Providing empirical evidence for claims'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('ENG101_Q091', 'What are the two essential requirements of an effective paraphrase?', 'MEDIUM', ['Keeping identical syntax and replacing every word with a thesaurus synonym', 'Substantially altering the sentence structure and vocabulary while preserving the original meaning faithfully, accompanied by an accurate citation', 'Making the text twice as long', 'Removing all difficult terminology'], 1, 'CLO2'),
  q('ENG101_Q092', 'Which signposting phrase is most suitable for introducing an illustrative example in an academic essay?', 'MEDIUM', ['"By the way, check this out..."', '"This phenomenon is exemplified by...", "To illustrate this point, consider..."', '"Let me tell you about..."', '"As everybody knows..."'], 1, 'CLO2'),
  q('ENG101_Q093', 'What is the primary function of a "Concluding Sentence" at the end of an academic body paragraph?', 'MEDIUM', ['To introduce an entirely new topic', 'To synthesize the paragraph\'s main point, relate it back to the essay\'s thesis, or provide a logical transition to the subsequent paragraph', 'To list the URLs visited', 'To copy the topic sentence word-for-word'], 1, 'CLO2'),
  q('ENG101_Q094', 'In an APA 7th edition reference list, how should the entries be arranged?', 'MEDIUM', ['In chronological order of publication', 'In alphabetical order by the primary author\'s last name', 'In order of importance', 'Grouped by book, website, and journal'], 1, 'CLO2'),
  q('ENG101_Q095', 'What is the main advantage of synthesizing multiple scholarly sources in a single paragraph (e.g., "Smith (2019) and Nguyen (2021) both demonstrate...")?', 'MEDIUM', ['It saves paper', 'It demonstrates comprehensive literature engagement, thematic integration, and stronger scholarly validation of the claim', 'It avoids reading the full texts', 'It confuses plagiarism detection software'], 1, 'CLO2'),
  q('ENG101_Q096', 'When taking notes during a fast-paced university lecture, which strategy is most effective?', 'MEDIUM', ['Attempting to transcribe every single word the professor utters', 'Focusing on main concepts, definitions, signpost signals, and utilizing abbreviations / conceptual diagrams', 'Recording audio and never listening to it', 'Closing one\'s notebook and relying solely on memory'], 1, 'CLO2'),
  q('ENG101_Q097', 'What is the formatting convention for a "block quotation" (a direct quote of 40 words or more) in APA 7th edition?', 'MEDIUM', ['Enclosed in double quotation marks and italics', 'Indented 0.5 inches from the left margin as a freestanding block, double-spaced, without quotation marks', 'Printed in red ink', 'Placed in the footer of the page'], 1, 'CLO2'),
  q('ENG101_Q098', 'Which of the following demonstrates an acceptable academic transition showing concession?', 'MEDIUM', ['"Consequently"', '"Admittedly, ...; nevertheless, ..."', '"Furthermore"', '"In summary"'], 1, 'CLO2'),
  q('ENG101_Q099', 'What information is contained in a DOI (Digital Object Identifier) found on scholarly articles?', 'MEDIUM', ['The price of the journal', 'A persistent, permanent alphanumeric string identifying the unique digital object and providing a reliable link to its location on the internet', 'The author\'s passport number', 'The university library code'], 1, 'CLO2'),
  q('ENG101_Q100', 'What is "patchwriting" and why is it considered academic dishonesty or poor scholarship?', 'MEDIUM', ['Writing with a fountain pen', 'Copying from a source text with only minimal, superficial word substitutions or rearrangements without genuinely rephrasing the cognitive structure', 'Writing on patches of cloth', 'Reviewing someone\'s code'], 1, 'CLO2'),
  q('ENG101_Q101', 'Identify the correct APA in-text citation format for a work with three or more authors on its very first appearance (APA 7th edition rule):', 'MEDIUM', ['(Smith, Johnson, Williams, & Brown, 2021)', '(Smith et al., 2021)', '(Smith and others, 2021)', '(Smith & Co., 2021)'], 1, 'CLO2'),
  q('ENG101_Q102', 'What is the role of an "annotated bibliography"?', 'MEDIUM', ['A bibliography with illustrations', 'A list of citations to books, articles, and documents, where each citation is followed by a brief descriptive and evaluative paragraph (annotation) assessing the source\'s relevance and quality', 'A list of books sold online', 'A signature list'], 1, 'CLO2'),
  q('ENG101_Q103', 'Why should academic writers avoid rhetorical questions (e.g., "Why did this happen?") in formal research reports?', 'MEDIUM', ['Because computers cannot parse question marks', 'Academic prose favors direct, declarative statements that advance arguments with authoritative clarity rather than conversational queries', 'Because questions are illegal in essays', 'To keep paragraphs shorter'], 1, 'CLO2'),
  q('ENG101_Q104', 'In an academic presentation, what is the purpose of "signpost language" (e.g., "Turning now to our experimental methodology...", "To conclude this point...")?', 'MEDIUM', ['To sound like a television host', 'To clearly signal to the audience the progression of the talk, transitions between sections, and the organizational framework', 'To waste time', 'To avoid answering audience questions'], 1, 'CLO2'),
  q('ENG101_Q105', 'What is the fundamental difference between "primary sources" and "secondary sources"?', 'MEDIUM', ['Primary sources are always in English', 'Primary sources are original, firsthand records created during the period of study (e.g., raw survey data, historical diaries); secondary sources analyze, interpret, and evaluate primary sources (e.g., textbook review articles)', 'Primary sources are cheaper', 'Secondary sources are always fictional'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('ENG101_Q106', 'Original text: "Global temperatures have risen by 1.1 degrees Celsius since the pre-industrial era, predominantly driven by human fossil fuel combustion." Select the best, fully legitimate paraphrase:', 'HARD', ['Global temperatures went up 1.1 degrees Celsius since pre-industrial times, mainly driven by human burning fossil fuel.', 'Since the pre-industrial period, global mean temperatures have escalated by roughly 1.1°C, an increase largely attributable to anthropogenic fossil fuel emissions (IPCC, 2021).', 'It has gotten hot because people burn things.', 'Global temperatures have risen by 1.1 degrees Celsius due to coal and gas.'], 1, 'CLO3'),
  q('ENG101_Q107', 'Identify which of the following constitutes an APA 7th reference entry for a journal article with accurate italicization and capitalization:', 'HARD', ['Smith, J. (2020). Machine learning applications. Journal of Computing, 12(3), 45-60.', 'Smith, J. (2020). Machine learning applications in tertiary education. *Journal of Computing in Higher Education*, *12*(3), 45–60. https://doi.org/10.1007/s12345', 'Smith (2020) "Machine learning applications" Journal of Computing.', 'J. Smith, 2020, Journal of Computing.'], 1, 'CLO3'),
  q('ENG101_Q108', 'Which paragraph demonstrates strong internal cohesion and unity?', 'HARD', ['A paragraph containing 5 disjointed sentences about different hobbies of the author.', 'A paragraph opening with a clear topic sentence on renewable energy, followed by two empirical studies verifying solar efficiency, contrasted with storage challenges, and ending with a synthesis sentence linking back to sustainability.', 'A paragraph that begins with biology and ends with football.', 'A paragraph composed entirely of quotes from 10 different websites.'], 1, 'CLO3'),
  q('ENG101_Q109', 'Select the appropriate correction for an "orphan quote" (a quotation dropped into a paragraph without introductory framing):', 'HARD', ['Leave it standalone in its own line.', 'Introduce the quotation with a signal phrase (e.g., According to Williams (2021), "..."), followed by critical commentary explaining how the quote supports the thesis.', 'Remove all quotation marks and pretend it is one\'s own words.', 'Put the quote in bold text.'], 1, 'CLO3'),
  q('ENG101_Q110', 'In synthesizing two conflicting research perspectives on remote work productivity, the most scholarly stance is:', 'HARD', ['Declare that one author is completely stupid.', 'Critically analyze differences in the two studies\' sample demographics, industry sectors, and data collection methodologies to explain why their findings diverged.', 'Ignore the negative study and only report the positive one.', 'Flip a coin to decide who is right.'], 1, 'CLO3'),
  q('ENG101_Q111', 'Which of the following is considered an acceptable practice when taking Cornell notes during a guest lecture?', 'HARD', ['Writing full narrative essays on the right side', 'Recording core ideas with abbreviations on the right, formulating review questions and cue keywords on the left column within 24 hours, and drafting a brief synthesis summary at the bottom', 'Leaving the summary area blank forever', 'Never reviewing the notes'], 1, 'CLO3'),
  q('ENG101_Q112', 'What is the correct treatment in APA 7th style when referencing a secondary source (a source cited within another source, e.g., Rabani\'s study cited in Miller, 2019)?', 'HARD', ['Mention Rabani in text, but cite Miller in parentheses (as cited in Miller, 2019), and include only Miller in the Reference list.', 'Include both in the reference list without reading Miller.', 'Invent the original paper citation from Rabani.', 'Ignore Miller completely.'], 0, 'CLO3'),
  q('ENG101_Q113', 'A student modifies only three words in a 50-word paragraph copied from an online report and provides no quotation marks or page number. This is an instance of:', 'HARD', ['Excellent scholarly paraphrasing', 'Plagiarism / Patchwriting (severe academic misconduct)', 'Creative writing', 'Accepted collaboration'], 1, 'CLO3'),
  q('ENG101_Q114', 'Select the sentence that exemplifies the most effective use of academic signposting to structure a 3-part presentation:', 'HARD', ['"I will talk about stuff."', '"This presentation is structured into three main sections: first, we review the theoretical framework; second, we present our empirical findings; and finally, we discuss policy recommendations."', '"Here are some slides I made."', '"Let us look at slide 1, then slide 2, then slide 3."'], 1, 'CLO3'),
  q('ENG101_Q115', 'When preparing an academic poster presentation for a conference, what is the optimal visual-to-text balance recommended by scholarly communication guidelines?', 'HARD', ['100% small text in 10-point font', 'Roughly 40-50% white space and high-resolution diagrams/charts, with concise bulleted findings legible from a 1.5-meter distance', 'Only black and white tables', 'No images or graphics allowed'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('ENG101_Q116', 'What is the "H-index" in bibliometric scholarly performance analysis, and what does an h-index of 25 signify?', 'EXPERT', ['The author has published 25 pages total', 'The researcher has published at least 25 academic papers, each of which has been cited at least 25 times by other publications', 'The author\'s university ranking is 25th', 'The author has 25 PhD students'], 1, 'CLO4'),
  q('ENG101_Q117', 'Analyze the ethical implications of using generative AI tools (such as ChatGPT) in drafting academic manuscripts without explicit disclosure:', 'EXPERT', ['It is completely encouraged with zero accountability', 'It violates academic transparency and integrity codes if AI-generated text is passed off as original intellectual labor without formal declaration in methodology / acknowledgments', 'All AI usage is punishable by law', 'AI text is immune to plagiarism algorithms'], 1, 'CLO4'),
  q('ENG101_Q118', 'What is "Predatory Publishing" (Xuất bản học thuật săn mồi) and what are its key warning indicators?', 'EXPERT', ['Publishing books about wild animals', 'Unscrupulous online publishers that exploit the open-access model by charging high author processing fees (APCs) while conducting superficial or zero genuine peer review and spamming academics', 'Publishing textbooks at low prices', 'Government university presses'], 1, 'CLO4'),
  q('ENG101_Q119', 'What distinguishes an "ORCID iD" (Open Researcher and Contributor ID) from a university staff ID?', 'EXPERT', ['ORCID is a national tax code', 'A persistent, globally recognized unique digital identifier that disambiguates an individual scholar from others with identical names across all publishers and institutions globally', 'A library card number', 'A password for Google Scholar'], 1, 'CLO4'),
  q('ENG101_Q120', 'In academic publishing agreements, what does the "Creative Commons Attribution License (CC-BY 4.0)" permit readers to do?', 'EXPERT', ['Only read the paper inside a physical library', 'Freely share, copy, distribute, and adapt the material in any medium, even commercially, provided appropriate credit is given to the original authors', 'Nothing without written permission from the government', 'Claim ownership of the copyright'], 1, 'CLO4')
];

module.exports = {
  course: {
    code: 'ENG101',
    name: 'Tiếng Anh Học Thuật 1',
    faculty: 'Khoa Ngoại Ngữ',
    category_code: 'CAT-ENG101',
    credits: 4
  },
  root_1: root1,
  root_2: root2,
  root_3: root3,
  getAllQuestions: () => [...root1, ...root2, ...root3]
};
