// backend/services/examBank/tou101.bank.js
// Ngân hàng câu hỏi chuẩn hóa: TOU101 — Tổng Quan Du Lịch & Dịch Vụ Lữ Hành
// Tổng cộng: 120 câu hỏi (3 Đề gốc x 40 câu hỏi)
'use strict';

function q(id, content, difficulty, answers, correctIdx, clo = 'CLO1') {
  return {
    id,
    course_code: 'TOU101',
    content,
    difficulty,
    default_mark: 0.25,
    clo,
    answers: answers.map((text, idx) => ({
      id: `${id}_A${idx + 1}`,
      letter: ['A', 'B', 'C', 'D'][idx],
      content: text,
      is_correct: idx === correctIdx,
      fraction: idx === correctIdx ? 1.0 : 0.0
    }))
  };
}

// ĐỀ GỐC 1 (40 câu): Khái niệm du lịch, Khách du lịch, Tài nguyên du lịch, Các loại hình du lịch
const root1 = [
  // Nhận biết (10 câu)
  q('TOU101_Q001', 'Theo Luật Du lịch Việt Nam năm 2017, "Du lịch" được định nghĩa là:', 'EASY', ['Chuyến đi dạo quanh nơi mình sinh sống', 'Các hoạt động có liên quan đến chuyến đi của con người ngoài nơi cư trú thường xuyên trong thời gian không quá 01 năm liên tục nhằm đáp ứng nhu cầu tham quan, nghỉ dưỡng, giải trí, tìm hiểu, khám phá tài nguyên du lịch hoặc kết hợp với mục đích hợp pháp khác', 'Chuyến đi tìm kiếm việc làm định cư ở nước ngoài', 'Việc đi buôn bán hàng hóa xuyên biên giới'], 1, 'CLO1'),
  q('TOU101_Q002', 'Theo quy định của Tổ chức Du lịch Thế giới (UNWTO), để được tính là "Khách du lịch" (Tourist), thời gian lưu trú tại điểm đến phải thỏa mãn điều kiện nào?', 'EASY', ['Dưới 4 giờ đồng hồ', 'Có lưu trú ít nhất 01 đêm (từ 24 giờ trở lên) tại cơ sở lưu trú và không quá 01 năm', 'Chỉ cần đến chụp ảnh rồi về trong ngày', 'Phải ở lại ít nhất 1 tháng'], 1, 'CLO1'),
  q('TOU101_Q003', 'Người đi tham quan, du lịch và trở về trong ngày mà không lưu trú qua đêm tại điểm đến được gọi là gì?', 'EASY', ['Khách du lịch quốc tế', 'Khách tham quan trong ngày (Same-day visitor / Excursionist)', 'Khách định cư', 'Khách thương mại'], 1, 'CLO1'),
  q('TOU101_Q004', 'Khái niệm "Khách du lịch quốc tế đến" (Inbound Tourist) dùng để chỉ:', 'EASY', ['Công dân Việt Nam đi du lịch sang châu Âu', 'Người nước ngoài, người Việt Nam định cư ở nước ngoài vào Việt Nam du lịch', 'Người dân từ Hà Nội vào Đà Nẵng du lịch', 'Người nước ngoài đến Việt Nam làm đại sứ ngoại giao'], 1, 'CLO1'),
  q('TOU101_Q005', 'Khái niệm "Khách du lịch ra nước ngoài" (Outbound Tourist) dùng để chỉ:', 'EASY', ['Người nước ngoài đến Việt Nam', 'Công dân Việt Nam và người nước ngoài cư trú tại Việt Nam đi du lịch ra nước ngoài', 'Du khách đi thuyền trên sông Mekong', 'Người xuất khẩu lao động'], 1, 'CLO1'),
  q('TOU101_Q006', 'Tài nguyên du lịch tự nhiên bao gồm các yếu tố nào sau đây?', 'EASY', ['Di tích lịch sử, bảo tàng, chùa chiền', 'Địa hình, khí hậu, thủy văn, hệ sinh thái sinh vật và cảnh quan thiên nhiên', 'Lễ hội truyền thống và làng nghề', 'Ẩm thực dân gian'], 1, 'CLO1'),
  q('TOU101_Q007', 'Tài nguyên du lịch nhân văn bao gồm các yếu tố nào?', 'EASY', ['Núi non, hang động, bãi biển', 'Di tích lịch sử - văn hóa, danh lam thắng cảnh, lễ hội, nghề thủ công truyền thống, nghệ thuật dân gian và ẩm thực', 'Sông ngòi và suối nước nóng', 'Rừng nguyên sinh'], 1, 'CLO1'),
  q('TOU101_Q008', 'Loại hình du lịch MICE là viết tắt của các từ tiếng Anh nào?', 'EASY', ['Music, Internet, Computer, Entertainment', 'Meetings (Hội họp), Incentives (Khen thưởng), Conferences/Conventions (Hội nghị/Hội thảo), Exhibitions/Events (Triển lãm/Sự kiện)', 'Market, Investment, Commerce, Economy', 'Modern, International, Cultural, Eco'], 1, 'CLO1'),
  q('TOU101_Q009', 'Địa danh nào sau đây của Việt Nam được UNESCO công nhận là Di sản Thiên nhiên Thế giới?', 'EASY', ['Phố cổ Hội An', 'Vịnh Hạ Long và Vườn quốc gia Phong Nha - Kẻ Bàng', 'Hoàng thành Thăng Long', 'Quần thể di tích Cố đô Huế'], 1, 'CLO1'),
  q('TOU101_Q010', 'Tính chất "Tính thời vụ" (Seasonality) trong hoạt động du lịch bắt nguồn chủ yếu từ yếu tố nào?', 'EASY', ['Giá vé máy bay thay đổi', 'Sự biến đổi của điều kiện khí hậu, thời tiết tự nhiên kết hợp với thời gian nghỉ phép, kỳ nghỉ hè của du khách', 'Do quy định của cảnh sát', 'Do chất lượng thức ăn'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('TOU101_Q011', 'Sản phẩm du lịch (Tourism Product) có đặc tính vô hình (Intangibility) có nghĩa là gì?', 'MEDIUM', ['Không thể nhìn thấy bằng mắt thường', 'Khách du lịch không thể sờ mó, nếm thử hay cảm nhận trực tiếp chất lượng dịch vụ trước khi quyết định mua và trải nghiệm thực tế', 'Sản phẩm không có giá bán', 'Sản phẩm bị giấu kín'], 1, 'CLO2'),
  q('TOU101_Q012', 'Đặc tính "Tính đồng thời giữa sản xuất và tiêu dùng" (Inseparability) của dịch vụ du lịch thể hiện ở điểm nào?', 'MEDIUM', ['Sản xuất trước rồi cất vào kho', 'Dịch vụ du lịch (như hướng dẫn, phục vụ phòng, vận chuyển) được sản xuất và tiêu thụ cùng một thời điểm, có sự tham gia trực tiếp của du khách', 'Có thể gửi hàng qua bưu điện', 'Có thể đổi trả lại như hàng hóa hữu hình'], 1, 'CLO2'),
  q('TOU101_Q013', 'Đặc tính "Tính không thể lưu kho / dễ hỏng" (Perishability) của sản phẩm du lịch dẫn tới hệ quả kinh tế nào?', 'MEDIUM', ['Thực phẩm trong khách sạn bị ôi thiu', 'Một phòng khách sạn không được thuê trong đêm nay hay một ghế máy bay bỏ trống trong chuyến bay không thể đem cất kho để bán bù vào ngày mai, doanh thu bị mất vĩnh viễn', 'Khách sạn bị xuống cấp sau 10 năm', 'Đóng cửa vào mùa mưa'], 1, 'CLO2'),
  q('TOU101_Q014', 'Mô hình Hệ thống Du lịch của Neil Leiper bao gồm 3 yếu tố cơ bản nào?', 'MEDIUM', ['Khách sạn, Máy bay, Hướng dẫn viên', 'Vùng phát sinh du khách (Generating region), Tuyến đường quá cảnh (Transit route) và Vùng điểm đến du lịch (Destination region), cùng với Du khách và Ngành du lịch', 'Chính phủ, Doanh nghiệp, Người dân', 'Tự nhiên, Nhân văn, Xã hội'], 1, 'CLO2'),
  q('TOU101_Q015', 'Tác động lan tỏa kinh tế (Tourism Multiplier Effect - Hệ số nhân du lịch) phản ánh điều gì?', 'MEDIUM', ['Giá vé tour tăng theo cấp số nhân', 'Chi tiêu ban đầu của khách du lịch được tuần hoàn và tạo ra thêm các vòng thu nhập, việc làm gián tiếp cho nhiều ngành kinh tế khác (nông nghiệp, xây dựng, giao thông)', 'Khách sạn nhân đôi số phòng', 'Số lượng du khách tăng gấp đôi'], 1, 'CLO2'),
  q('TOU101_Q016', 'Sức chứa du lịch (Tourism Carrying Capacity) của một điểm đến được hiểu là:', 'MEDIUM', ['Số lượng giường tối đa trong một khách sạn', 'Mức độ khai thác du lịch tối đa mà điểm đến có thể tiếp nhận mà không làm hủy hoại môi trường tự nhiên, văn hóa bản địa hoặc làm suy giảm chất lượng trải nghiệm của du khách', 'Sức chở của chiếc xe buýt du lịch', 'Trọng lượng tối đa của cây cầu'], 1, 'CLO2'),
  q('TOU101_Q017', 'Du lịch sinh thái (Ecotourism) khác với du lịch đại chúng (Mass Tourism) ở điểm cốt lõi nào?', 'MEDIUM', ['Giá tour đắt hơn nhiều', 'Tập trung vào trải nghiệm thiên nhiên gắn liền với trách nhiệm bảo tồn môi trường sinh thái, tôn trọng văn hóa bản địa và đóng góp trực tiếp cho sinh kế của cộng đồng địa phương', 'Chỉ dành cho nhà khoa học', 'Đi bằng xe đạp'], 1, 'CLO2'),
  q('TOU101_Q018', 'Đặc điểm của khách du lịch MICE so với khách du lịch nghỉ dưỡng thuần túy là:', 'MEDIUM', ['Chi tiêu rất ít tiền', 'Khả năng chi trả cao, sử dụng dịch vụ cao cấp (khách sạn 4-5 sao, trung tâm hội nghị quốc tế), đi theo đoàn đông và ít bị ảnh hưởng bởi tính mùa vụ thời tiết', 'Chỉ đi du lịch vào cuối tuần', 'Không cần phòng họp'], 1, 'CLO2'),
  q('TOU101_Q019', 'Du lịch cộng đồng (Community-Based Tourism - CBT) mang lại lợi ích nổi bật nào cho người dân địa phương?', 'MEDIUM', ['Người dân bị di dời đi nơi khác', 'Cộng đồng địa phương trực tiếp tham gia quản lý, cung cấp dịch vụ du lịch (homestay, trải nghiệm nông nghiệp) và được hưởng lợi trực tiếp từ nguồn thu du lịch', 'Bán hết đất đai cho tập đoàn lớn', 'Không cần lao động'], 1, 'CLO2'),
  q('TOU101_Q020', 'Hiện tượng "Rò rỉ kinh tế trong du lịch" (Economic Leakage) xảy ra khi nào?', 'MEDIUM', ['Bị mất cắp tài sản trên tour', 'Một phần lớn doanh thu từ chi tiêu của du khách bị chuyển ra nước ngoài (trả tiền cho các hãng hàng không ngoại, tập đoàn khách sạn đa quốc gia, hàng nhập khẩu) thay vì đọng lại ở kinh tế địa phương', 'Doanh nghiệp trốn thuế', 'Khách không thanh toán tiền phòng'], 1, 'CLO2'),
  q('TOU101_Q021', 'Vòng đời của một Điểm đến du lịch theo mô hình của Butler (TALC) trải qua các giai đoạn theo thứ tự:', 'MEDIUM', ['Thành công -> Thất bại', 'Khám phá (Exploration) -> Tham gia (Involvement) -> Phát triển (Development) -> Củng cố (Consolidation) -> Trì trệ (Stagnation) -> Suy thoái hoặc Tái định vị (Rejuvenation)', 'Xây dựng -> Khai trương -> Đóng cửa', 'Mùa xuân -> Mùa hè -> Mùa thu -> Mùa đông'], 1, 'CLO2'),
  q('TOU101_Q022', 'Tài nguyên du lịch có khả năng tái tạo khác tài nguyên không thể tái tạo ở điểm nào?', 'MEDIUM', ['Không có giá trị tiền bạc', 'Tài nguyên nhân văn (như lễ hội, phong tục, nghệ thuật) có thể được phục dựng, làm giàu thêm qua thời gian; trong khi các hang động karst tự nhiên, địa mạo hóa thạch một khi đã bị phá hủy thì không thể phục hồi', 'Tài nguyên tái tạo không cần bảo tồn', 'Tất cả tài nguyên đều vĩnh cửu'], 1, 'CLO2'),
  q('TOU101_Q023', 'Cơ sở hạ tầng du lịch (Infrastructure) khác với Cơ sở vật chất kỹ thuật du lịch (Superstructure) ở điểm nào?', 'MEDIUM', ['Không có sự khác nhau', 'Cơ sở hạ tầng là hệ thống nền tảng dùng chung của toàn xã hội (hệ thống giao thông, điện, nước, viễn thông, bệnh viện); còn cơ sở vật chất kỹ thuật du lịch phục vụ chuyên biệt cho du khách (khách sạn, nhà hàng, khu vui chơi)', 'Cơ sở hạ tầng chỉ dành riêng cho du lịch', 'Cơ sở vật chất kỹ thuật do nhà nước đầu tư 100%'], 1, 'CLO2'),
  q('TOU101_Q024', 'Khái niệm "Cú sốc văn hóa" (Culture Shock) của du khách quốc tế là gì?', 'MEDIUM', ['Bị điện giật tại khách sạn', 'Cảm giác bỡ ngỡ, hoang mang, lo âu hoặc mất phương hướng tạm thời khi tiếp xúc với một môi trường văn hóa, tín ngưỡng, tập quán xa lạ và khác biệt hoàn toàn với quê hương mình', 'Bị ngộ độc thực phẩm', 'Mất hộ chiếu'], 1, 'CLO2'),
  q('TOU101_Q025', 'Quần thể danh thắng Tràng An (Ninh Bình) được UNESCO công nhận là Di sản gì đặc biệt của Việt Nam và Đông Nam Á?', 'MEDIUM', ['Di sản văn hóa thuần túy', 'Di sản thế giới kép / Hỗn hợp đầu tiên (kết hợp cả giá trị nổi bật toàn cầu về Văn hóa và Thiên nhiên)', 'Di sản thiên nhiên đơn lẻ', 'Khu dự trữ sinh quyển thế giới'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('TOU101_Q026', 'Để giải quyết tính mùa vụ thấp điểm vào mùa đông tại các điểm du lịch biển miền Bắc Việt Nam (như Sầm Sơn, Cát Bà), giải pháp chiến lược tối ưu là:', 'HARD', ['Đóng cửa toàn bộ khách sạn 6 tháng', 'Đa dạng hóa sản phẩm du lịch: Phát triển du lịch hội nghị MICE, du lịch chăm sóc sức khỏe (Onsen, Spa khoáng nóng), lễ hội ẩm thực và giảm giá kích cầu các gói nghỉ dưỡng mùa đông', 'Bơm nước nóng ra biển', 'Bắt buộc cán bộ công chức đi tắm biển mùa đông'], 1, 'CLO3'),
  q('TOU101_Q027', 'Hiện tượng quá tải du lịch (Overtourism) tại một số điểm đến nổi tiếng (như Sa Pa, Venice) gây ra tác động tiêu cực nào sau đây?', 'HARD', ['Tăng giá bất động sản đẩy người dân bản địa ra ngoài, tắc nghẽn giao thông, ô nhiễm rác thải và làm mai một bản sắc văn hóa truyền thống', 'Người dân địa phương trở nên giàu có quá nhanh', 'Khách du lịch được phục vụ chu đáo hơn', 'Không khí trở nên trong lành hơn'], 0, 'CLO3'),
  q('TOU101_Q028', 'Khi phát triển mô hình Du lịch nông nghiệp công nghệ cao tại Đà Lạt, nhà đầu tư kết hợp các yếu tố nào để gia tăng chuỗi giá trị?', 'HARD', ['Chỉ bán vé vào cổng', 'Kết hợp quy trình canh tác nông nghiệp sạch (dâu tây, hoa, rau thủy canh) với dịch vụ trải nghiệm tự tay thu hoạch, thưởng thức tại chỗ và bán sản phẩm chế biến làm quà lưu niệm', 'Xóa bỏ toàn bộ nhà kính', 'Cấm du khách chụp ảnh'], 1, 'CLO3'),
  q('TOU101_Q029', 'Một di tích lịch sử quốc gia đón nhận 10.000 lượt khách mỗi ngày trong khi sức chứa tâm lý và vật lý tối đa chỉ là 3.000 lượt khách. Giải pháp quản lý điểm đến bền vững là:', 'HARD', ['Phá dỡ di tích để mở rộng đường đi', 'Áp dụng hệ thống bán vé đặt chỗ theo khung giờ (Time-slot ticketing), phân luồng tuyến tham quan một chiều và tăng giá vé giờ cao điểm để điều tiết dòng khách', 'Không cho bất kỳ ai vào tham quan', 'Miễn phí vé vào cửa'], 1, 'CLO3'),
  q('TOU101_Q030', 'Chiến lược "Du lịch chậm" (Slow Tourism) đang trở thành xu hướng mới trên toàn cầu nhằm đáp ứng nhu cầu nào của du khách hiện đại?', 'HARD', ['Đi bằng phương tiện chậm nhất như xe bò', 'Thoát khỏi nhịp sống hối hả, lưu trú dài ngày hơn tại một điểm đến để hòa nhập sâu sắc vào văn hóa địa phương, bảo vệ môi trường và tái tạo năng lượng tinh thần', 'Chỉ đi du lịch một mình', 'Không sử dụng điện thoại'], 1, 'CLO3'),
  q('TOU101_Q031', 'Việc thương mại hóa quá mức các lễ hội truyền thống (Commercialization of Culture) có thể dẫn tới nguy cơ nào?', 'HARD', ['Làm lễ hội đông vui hơn', 'Biến các nghi lễ tâm linh thiêng liêng thành những màn trình diễn giả tạo, méo mó phục vụ kinh doanh thuần túy (sự dàn dựng sân khấu hóa văn hóa - Staged Authenticity)', 'Tăng thêm kinh phí trùng tu', 'Không có tác động tiêu cực nào'], 1, 'CLO3'),
  q('TOU101_Q032', 'Để xây dựng một sản phẩm du lịch mạo hiểm (Adventure Tourism, ví dụ: thám hiểm hang Sơn Đoòng, leo Fansipan) thành công, yếu tố tiên quyết hàng đầu là:', 'HARD', ['Giá tour phải thật rẻ', 'Quy chuẩn an toàn tuyệt đối, đội ngũ chuyên gia/hướng dẫn viên có chứng chỉ cứu hộ quốc tế và bảo hiểm du lịch chuyên biệt mạo hiểm', 'Cho phép mọi đối tượng tự do tham gia', 'Không cần trang thiết bị bảo hộ'], 1, 'CLO3'),
  q('TOU101_Q033', 'Khi phân đoạn thị trường du lịch theo nhân khẩu học (Demographics), các tiêu chí cơ bản được sử dụng gồm:', 'HARD', ['Sở thích và phong cách sống', 'Độ tuổi, giới tính, mức thu nhập, trình độ học vấn, tình trạng hôn nhân và nghề nghiệp', 'Khí hậu nơi đến', 'Tần suất dùng mạng xã hội'], 1, 'CLO3'),
  q('TOU101_Q034', 'Một du khách Pháp đến Hà Nội thưởng thức bún chả, phở và tham gia lớp học nấu ăn truyền thống tại phố cổ. Du khách này đang tham gia loại hình du lịch nào?', 'HARD', ['Du lịch mạo hiểm', 'Du lịch ẩm thực (Culinary / Gastronomy Tourism) kết hợp du lịch văn hóa', 'Du lịch MICE', 'Du lịch y tế'], 1, 'CLO3'),
  q('TOU101_Q035', 'Chỉ số Năng lực Phát triển Du lịch (Travel & Tourism Development Index - TTDI) do Diễn đàn Kinh tế Thế giới (WEF) công bố đánh giá dựa trên trụ cột nào?', 'HARD', ['Chỉ dựa vào số lượng khách quốc tế', 'Môi trường kinh doanh, an ninh an toàn, hạ tầng giao thông/dịch vụ, tài nguyên tự nhiên/văn hóa và tính bền vững môi trường', 'Số lượng khách sạn 5 sao', 'Diện tích bãi biển'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('TOU101_Q036', 'Khái niệm "Doxey\'s Irridex" (Chỉ số kích ứng của cư dân bản địa đối với du lịch) mô tả sự chuyển biến tâm lý của cộng đồng địa phương qua 4 giai đoạn nào?', 'EXPERT', ['Vui vẻ -> Hạnh phúc -> Giàu có -> Tự hào', 'Hân hoan chào đón (Euphoria) -> Thờ ơ xem là hiển nhiên (Apathy) -> Khó chịu/Kích ứng (Irritation) -> Phản kháng/Đối địch (Antagonism)', 'Yêu thích -> Ghét bỏ -> Xung đột -> Bỏ đi', 'Không bao giờ thay đổi tâm lý'], 1, 'CLO4'),
  q('TOU101_Q037', 'Trong kinh tế học du lịch, phương pháp Chi phí Du lịch (Travel Cost Method - TCM) thường được các nhà nghiên cứu áp dụng để làm gì?', 'EXPERT', ['Tính tiền vé xe buýt', 'Định giá kinh tế phi thị trường của các tài nguyên tự nhiên (như Vườn quốc gia, danh lam thắng cảnh) dựa trên chi phí thời gian và tiền bạc mà du khách sẵn sàng bỏ ra để đến tham quan', 'Tính thuế giá trị gia tăng', 'Đo lường mức lạm phát'], 1, 'CLO4'),
  q('TOU101_Q038', 'Mô hình Đánh giá Vòng đời Du lịch của Plog (Plog\'s Psychographic Model) phân loại tính cách du khách theo thang đo nào?', 'EXPERT', ['Người hướng nội và Người hướng ngoại', 'Du khách thích an toàn, quen thuộc (Allocentric / Dependables) đến Du khách thích phiêu lưu mạo hiểm, khám phá vùng đất mới lạ (Venturers / Allocentrics)', 'Người nghèo đến Người giàu', 'Thanh niên đến Người cao tuổi'], 1, 'CLO4'),
  q('TOU101_Q039', 'Khái niệm "Tourism Gentrification" (Sự biến đổi thành thị do du lịch hóa) diễn tả hiện tượng kinh tế - xã hội nào tại các trung tâm lịch sử?', 'EXPERT', ['Thành phố được quét dọn sạch hơn', 'Làn sóng đầu tư du lịch làm tăng vọt giá thuê mặt bằng và chi phí sinh hoạt, biến các khu dân cư lâu đời thành khách sạn, quán bar, đẩy cư dân truyền thống ra vùng ngoại ô', 'Người dân bản địa sở hữu nhiều nhà hơn', 'Giao thông được thông suốt hoàn toàn'], 1, 'CLO4'),
  q('TOU101_Q040', 'Bộ quy tắc đạo đức toàn cầu trong du lịch (Global Code of Ethics for Tourism) do UNWTO thông qua gồm 10 điều khoản nhằm hướng tới mục tiêu tối thượng nào?', 'EXPERT', ['Bắt buộc du khách phải chi tiêu tối đa tiền', 'Tối đa hóa lợi ích kinh tế xã hội của du lịch đồng thời giảm thiểu tối đa các tác động tiêu cực đến môi trường, di sản văn hóa và thúc đẩy hòa bình, hiểu biết lẫn nhau giữa các dân tộc', 'Độc quyền hóa ngành lữ hành', 'Cấm du lịch tự túc'], 1, 'CLO4')
];

// ĐỀ GỐC 2 (40 câu): Kinh doanh lữ hành, Thiết kế tour, Điều hành tour & Quản trị rủi ro du lịch
const root2 = [
  // Nhận biết (10 câu)
  q('TOU101_Q041', 'Doanh nghiệp kinh doanh dịch vụ lữ hành (Tour Operator) khác với Đại lý du lịch (Travel Agency) ở điểm cốt lõi nào?', 'EASY', ['Đại lý du lịch tự thiết kế tour', 'Doanh nghiệp lữ hành trực tiếp nghiên cứu, xây dựng, bán và tổ chức thực hiện các chương trình du lịch (tour); trong khi đại lý du lịch chỉ bán lại tour của lữ hành để hưởng hoa hồng đại lý', 'Doanh nghiệp lữ hành không có giấy phép', 'Đại lý du lịch có vốn lớn hơn'], 1, 'CLO1'),
  q('TOU101_Q042', 'Theo Luật Du lịch Việt Nam 2017, doanh nghiệp kinh doanh dịch vụ lữ hành quốc tế phục vụ khách du lịch quốc tế đến Việt Nam (Inbound) phải ký quỹ bao nhiêu tiền tại ngân hàng?', 'EASY', ['50 triệu đồng', '250 triệu đồng (hoặc 500 triệu đồng tùy phạm vi cả Inbound và Outbound)', '1 tỷ đồng', '100 triệu đồng'], 1, 'CLO1'),
  q('TOU101_Q043', 'Chương trình du lịch trọn gói (Package Tour / Inclusive Tour) là chuyến du lịch bao gồm:', 'EASY', ['Chỉ có vé máy bay', 'Tập hợp đầy đủ các dịch vụ cơ bản: Vận chuyển, lưu trú, ăn uống, tham quan, hướng dẫn viên và bảo hiểm du lịch được bán với mức giá trọn gói duy nhất', 'Chỉ có phòng khách sạn', 'Chuyến đi tự phát không có kế hoạch'], 1, 'CLO1'),
  q('TOU101_Q044', 'Văn bản nào thể hiện chi tiết lộ trình di chuyển, các điểm dừng chân, thời gian tham quan và các hoạt động của một tour du lịch được gọi là:', 'EASY', ['Hợp đồng lao động', 'Lịch trình tour (Itinerary)', 'Bảng thanh toán tiền lương', 'Vé máy bay điện tử'], 1, 'CLO1'),
  q('TOU101_Q045', 'Chuyến đi khảo sát thực tế tuyến điểm du lịch mới trước khi thiết kế và chào bán tour được gọi là chuyến đi gì?', 'EASY', ['Tour nghỉ dưỡng', 'FAM trip (Familiarization Trip) hoặc khảo sát tuyến điểm (Site Inspection)', 'Tour khám bệnh', 'Chuyến dã ngoại'], 1, 'CLO1'),
  q('TOU101_Q046', 'Người chịu trách nhiệm điều phối toàn bộ các khâu đặt dịch vụ (xe, phòng, nhà hàng, vé tham quan) và giám sát quá trình diễn ra tour tại văn phòng lữ hành là:', 'EASY', ['Hướng dẫn viên dẫn đoàn', 'Nhân viên điều hành tour (Tour Operator / Tour Coordinator)', 'Kế toán công ty', 'Nhân viên bảo vệ'], 1, 'CLO1'),
  q('TOU101_Q047', 'Thuật ngữ "Allotment" trong hợp đồng giữa công ty lữ hành và khách sạn có nghĩa là gì?', 'EASY', ['Hủy phòng hàng loạt', 'Số lượng phòng khách sạn cam kết giữ trước cho công ty lữ hành trong một khoảng thời gian nhất định kèm theo thời hạn chốt giữ phòng (Release Date)', 'Phòng miễn phí cho lái xe', 'Tiền đặt cọc mua tài sản'], 1, 'CLO1'),
  q('TOU101_Q048', 'Bảo hiểm du lịch (Travel Insurance) cho du khách mua tour trọn gói tại Việt Nam có tính chất như thế nào?', 'EASY', ['Tùy chọn không bắt buộc', 'Bắt buộc công ty lữ hành phải mua cho khách du lịch trong suốt thời gian thực hiện chương trình du lịch (trừ khi khách đã có bảo hiểm riêng theo quy định)', 'Chỉ dành cho tour mạo hiểm', 'Do hướng dẫn viên tự nguyện trả'], 1, 'CLO1'),
  q('TOU101_Q049', 'Hồ sơ đoàn tour do bộ phận điều hành bàn giao cho hướng dẫn viên trước ngày khởi hành thường được gọi là gì?', 'EASY', ['Sổ tay nhật ký', 'Hồ sơ bàn giao tour / Lệnh điều tour (Tour Dossier / Tour Folder)', 'Báo cáo thuế', 'Đơn xin phép'], 1, 'CLO1'),
  q('TOU101_Q050', 'Chính sách FOC (Free of Charge) trong du lịch thường áp dụng cho đối tượng nào trong đoàn khách?', 'EASY', ['Người già trên 80 tuổi', 'Trưởng đoàn (Tour Leader) hoặc miễn phí 1 khách khi đoàn đạt số lượng nhất định (ví dụ: 15 khách trả tiền + 1 FOC)', 'Tất cả trẻ em', 'Người đặt tour sớm nhất'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('TOU101_Q051', 'Công thức tính giá thành một tour trọn gói (Tour Costing) cho một du khách bao gồm hai nhóm chi phí cơ bản nào?', 'MEDIUM', ['Chi phí ăn và uống', 'Chi phí cố định bình quân trên mỗi khách (Chi phí thuê xe, hướng dẫn viên chia cho số khách dự kiến) cộng với Chi phí biến đổi của từng khách (Tiền phòng, tiền ăn, vé tham quan, bảo hiểm)', 'Tiền lương giám đốc và tiền điện văn phòng', 'Chi phí quảng cáo chia đều'], 1, 'CLO2'),
  q('TOU101_Q052', 'Khi tính toán giá tour cho một đoàn khách, nếu số lượng khách thực tế tham gia ÍT HƠN số lượng khách dự kiến ban đầu thì điều gì xảy ra với chi phí cố định bình quân?', 'MEDIUM', ['Chi phí cố định bình quân giảm đi', 'Chi phí cố định bình quân trên mỗi khách tăng lên, làm giảm tỷ suất lợi nhuận của công ty lữ hành hoặc thậm chí gây lỗ', 'Không thay đổi chi phí', 'Giá thành bằng 0'], 1, 'CLO2'),
  q('TOU101_Q053', 'Khái niệm "Single Supplement" (Phụ thu phòng đơn) áp dụng trong trường hợp nào?', 'MEDIUM', ['Khách đi một mình nhưng bắt buộc phải ngủ ghép', 'Một du khách trong đoàn có nhu cầu ở riêng một mình một phòng khách sạn thay vì ngủ ghép 2 người/phòng (Twin/Double) theo tiêu chuẩn tour', 'Phòng chỉ có 1 chiếc giường đơn', 'Khách trả phòng muộn'], 1, 'CLO2'),
  q('TOU101_Q054', 'Nguyên tắc thiết kế hành trình tour (Tour Itinerary) khoa học đòi hỏi lộ trình di chuyển phải tránh điều gì?', 'MEDIUM', ['Đi qua các cây cầu lớn', 'Tránh hành trình đi đường vòng vèo lặp lại đường cũ (Backtracking), hạn chế thời gian ngồi trên xe quá dài và bố trí các điểm tham quan theo nhịp điệu sinh học hợp lý', 'Dừng chân nghỉ ngơi', 'Ghé thăm các di tích'], 1, 'CLO2'),
  q('TOU101_Q055', 'Trong hợp đồng dịch vụ lữ hành, điều khoản "Bất khả kháng" (Force Majeure) áp dụng cho các sự kiện nào?', 'MEDIUM', ['Hướng dẫn viên ngủ quên', 'Các sự kiện bất thường không thể lường trước và không thể khắc phục được như thiên tai, bão lũ, động đất, dịch bệnh, chiến tranh khiến tour không thể thực hiện được', 'Khách đổi ý không muốn đi', 'Xe bị hết xăng'], 1, 'CLO2'),
  q('TOU101_Q056', 'Quy trình giải quyết khiếu nại của khách du lịch sau tour cần được xử lý theo các bước nào?', 'MEDIUM', ['Phớt lờ khiếu nại', 'Lắng nghe chân thành -> Ghi nhận chi tiết sự việc -> Xác minh độc lập với đối tác cung ứng dịch vụ -> Đưa ra giải pháp thỏa đáng (bồi thường/xin lỗi) -> Lưu trữ rút kinh nghiệm', 'Đổ lỗi cho hướng dẫn viên', 'Kiện khách hàng ra tòa ngay'], 1, 'CLO2'),
  q('TOU101_Q057', 'Hệ thống phân phối toàn cầu GDS (Global Distribution System, ví dụ: Amadeus, Sabre) đóng vai trò gì trong ngành lữ hành?', 'MEDIUM', ['Mạng xã hội chia sẻ ảnh', 'Mạng lưới công nghệ thông tin tự động hóa kết nối các đại lý du lịch trên toàn thế giới với các hãng hàng không, khách sạn, công ty cho thuê xe để đặt chỗ và xuất vé thời gian thực', 'Phần mềm kế toán nội bộ', 'Hệ thống định vị xe buýt'], 1, 'CLO2'),
  q('TOU101_Q058', 'Tại sao công ty lữ hành cần xây dựng Kế hoạch Quản trị Rủi ro và Ứng phó Khủng hoảng (Crisis Management Plan) trước mùa cao điểm?', 'MEDIUM', ['Để nộp phạt cho thanh tra', 'Chủ động nhận diện các kịch bản sự cố tiềm ẩn (tai nạn xe, ngộ độc thực phẩm, khách lạc, thất lạc hành lý) và chuẩn bị sẵn quy trình phản ứng nhanh để bảo vệ tính mạng du khách và uy tín doanh nghiệp', 'Để nâng giá tour lên cao', 'Nhằm quảng cáo trên tivi'], 1, 'CLO2'),
  q('TOU101_Q059', 'Thuật ngữ "Rooming List" trong điều hành tour là danh sách ghi rõ thông tin gì gửi cho khách sạn?', 'MEDIUM', ['Thực đơn bữa tối', 'Danh sách phân chia phòng của các thành viên trong đoàn (Họ tên, giới tính, ngày sinh, số hộ chiếu, cách ghép phòng Single, Double, Twin, Triple)', 'Giá tiền từng phòng', 'Biển số xe ô tô'], 1, 'CLO2'),
  q('TOU101_Q060', 'Dịch vụ Land Tour trong kinh doanh lữ hành có nghĩa là gì?', 'MEDIUM', ['Tour đi bộ đường dài', 'Gói dịch vụ du lịch mặt đất trọn gói tại điểm đến (xe vận chuyển, khách sạn, ăn uống, vé tham quan, HDV địa phương) do công ty lữ hành địa phương cung cấp, chưa bao gồm vé máy bay khứ hồi', 'Tour bán đất bất động sản', 'Tour tham quan nông trại'], 1, 'CLO2'),
  q('TOU101_Q061', 'Kỹ thuật định giá tour "Chi phí cộng lãi" (Cost-plus Pricing) được tính bằng:', 'MEDIUM', ['Giá của đối thủ cạnh tranh chia đôi', 'Tổng giá thành ước tính của tour cộng thêm một tỷ lệ phần trăm lợi nhuận biên mục tiêu (Markup) của doanh nghiệp', 'Giá vé máy bay cộng tiền khách sạn', 'Bán bằng giá vốn'], 1, 'CLO2'),
  q('TOU101_Q062', 'Khi xảy ra sự cố một khách trong đoàn bị tai nạn thương tích trong quá trình tham quan, hành động đầu tiên của hướng dẫn viên là:', 'MEDIUM', ['Gọi điện báo nhà báo', 'Sơ cứu khẩn cấp tại chỗ và đưa ngay du khách đến cơ sở y tế gần nhất, đồng thời báo cáo khẩn về bộ phận điều hành công ty và liên hệ bảo hiểm', 'Tiếp tục dẫn đoàn đi chơi bình thường', 'Bắt khách tự đi taxi'], 1, 'CLO2'),
  q('TOU101_Q063', 'Tour khởi hành định kỳ (Scheduled / Guaranteed Departure Tour) là tour có đặc điểm gì?', 'MEDIUM', ['Chỉ khởi hành khi có trên 100 khách', 'Tour được lên lịch khởi hành vào các ngày cố định trong tuần hoặc trong tháng và cam kết khởi hành đúng lịch kể cả khi số lượng khách ít', 'Khởi hành ngẫu nhiên', 'Khách tự lái xe'], 1, 'CLO2'),
  q('TOU101_Q064', 'Thuật ngữ "No-show" trong ngành du lịch khách sạn dùng để chỉ tình huống nào?', 'MEDIUM', ['Khách không xem biểu diễn nghệ thuật', 'Khách hàng đã đặt chỗ trước nhưng không đến nhận dịch vụ vào ngày quy định mà không thực hiện thông báo hủy trước đó', 'Khách đến đúng giờ', 'Khách trả phòng sớm'], 1, 'CLO2'),
  q('TOU101_Q065', 'Báo cáo kết thúc tour (Tour Final Report / Tour Debriefing) do hướng dẫn viên nộp cho phòng điều hành sau chuyến đi nhằm mục đích:', 'MEDIUM', ['Kể chuyện cười trên tour', 'Đánh giá chất lượng thực tế của các nhà cung ứng dịch vụ (xe, nhà hàng, khách sạn), phản hồi của du khách, quyết toán tài chính tạm ứng và các vấn đề phát sinh cần khắc phục', 'Xin nghỉ phép', 'Lấy hóa đơn VAT'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('TOU101_Q066', 'Một tour Hà Nội - Hạ Long 2 ngày 1 đêm có chi phí cố định cho cả đoàn (tiền xe 29 chỗ + tiền công HDV) là 6.000.000 đồng. Chi phí biến đổi cho mỗi khách là 800.000 đồng. Nếu đoàn có 20 khách, giá thành của 1 khách là:', 'HARD', ['1.000.000 đồng', '1.100.000 đồng (Chi phí cố định/khách = 6.000.000 / 20 = 300.000đ; Tổng giá thành = 300.000 + 800.000 = 1.100.000đ)', '1.400.000 đồng', '800.000 đồng'], 1, 'CLO3'),
  q('TOU101_Q067', 'Với tour có giá thành 1.100.000 đồng/khách, công ty lữ hành muốn mức lãi gộp là 20% trên giá bán (Margin = 20%). Giá bán tour cho mỗi khách phải thiết lập là:', 'HARD', ['1.320.000 đồng', '1.375.000 đồng (Giá bán = Giá thành / (1 - Margin) = 1.100.000 / 0.8 = 1.375.000đ)', '1.200.000 đồng', '1.500.000 đồng'], 1, 'CLO3'),
  q('TOU101_Q068', 'Trong chuyến bay đến Đà Nẵng, hãng hàng không thông báo chuyến bay bị trễ giờ (Delay) 4 tiếng so với lịch trình dự kiến, làm lỡ bữa ăn trưa đã đặt tại nhà hàng. Nhân viên điều hành tour cần xử lý:', 'HARD', ['Hủy luôn tour trả khách về', 'Liên hệ ngay với nhà hàng dời bữa ăn sang bữa tối hoặc lùi giờ ăn, sắp xếp xe đón tại sân bay theo giờ mới, mua đồ ăn nhẹ cho khách tại sân bay và thông báo chân thành cho khách đoàn', 'Bỏ đói du khách', 'Yêu cầu khách tự bắt xe buýt'], 1, 'CLO3'),
  q('TOU101_Q069', 'Một du khách quốc tế trong đoàn làm mất hộ chiếu tại khu chợ đêm ở Hà Nội trước ngày bay về nước 1 ngày. Quy trình hỗ trợ khẩn cấp của công ty lữ hành là:', 'HARD', ['Mua vé máy bay mới cho khách tự về', 'Đưa du khách đến công an phường sở tại trình báo lấy xác nhận mất hộ chiếu, chụp ảnh thẻ, liên hệ Đại sứ quán/Lãnh sự quán của nước du khách tại Hà Nội để làm giấy thông hành khẩn cấp', 'Khuyên du khách trốn lại Việt Nam', 'Không chịu trách nhiệm'], 1, 'CLO3'),
  q('TOU101_Q070', 'Khi đoàn khách đang tham quan trên vịnh biển thì có dự báo bão khẩn cấp đổ bộ sớm hơn dự kiến. Trách nhiệm an toàn tối thượng của HDV và công ty lữ hành là:', 'HARD', ['Tiếp tục cho khách chèo thuyền ngắm bão', 'Tuân thủ tuyệt đối lệnh cấm biển của Cảng vụ, lập tức phối hợp thuyền trưởng đưa tàu và toàn bộ du khách về bến cảng neo đậu an toàn, đưa khách về khách sạn kiên cố', 'Để khách tự bơi vào bờ', 'Tổ chức tiệc trên tàu'], 1, 'CLO3'),
  q('TOU101_Q071', 'Một công ty lữ hành xây dựng sản phẩm tour du lịch xe đạp xuyên Việt (Cycling Tour). Tiêu chuẩn chọn đối tác vận chuyển hậu cần (Logistics Support) quan trọng nhất là:', 'HARD', ['Xe giá rẻ nhất', 'Xe tải chuyên dụng có giá đỡ bảo vệ xe đạp, có trang bị bộ đồ nghề sửa chữa chuyên dụng, phụ tùng thay thế và chở hành lý, nước uống bám sát đoàn', 'Xe cứu hỏa', 'Xe máy tay ga'], 1, 'CLO3'),
  q('TOU101_Q072', 'Khi phát hiện một nhà hàng trong chương trình tour phục vụ thức ăn có mùi lạ không đảm bảo vệ sinh an toàn thực phẩm, phản ứng đúng đắn của HDV là:', 'HARD', ['Bảo du khách cứ ăn thử xem sao', 'Yêu cầu quản lý nhà hàng dừng phục vụ món đó ngay lập tức, đổi món ăn mới đảm bảo tươi ngon an toàn hoặc chuyển đoàn sang nhà hàng đạt chuẩn khác, lập biên bản sự việc', 'Bỏ đi ra ngoài', 'Ăn hết món đó trước'], 1, 'CLO3'),
  q('TOU101_Q073', 'Một đoàn khách doanh nghiệp 50 người yêu cầu tổ chức chương trình Team Building trên bãi biển. Bộ phận lữ hành cần xin phép cơ quan nào trước khi thực hiện?', 'HARD', ['Bộ Công an', 'Ủy ban nhân dân địa phương hoặc Ban Quản lý bãi biển / Bán đảo du lịch sở tại kèm theo phương án cứu hộ cứu nạn và cam kết dọn dẹp vệ sinh môi trường sau sự kiện', 'Hội đồng Khảo thí', 'Không cần xin phép ai'], 1, 'CLO3'),
  q('TOU101_Q074', 'Trong quá trình đàm phán hợp đồng cung ứng phòng với một chuỗi khách sạn resort mùa cao điểm, điều khoản "Cut-off Date" được hiểu là:', 'HARD', ['Ngày khách sạn đóng cửa bảo trì', 'Hạn chót mà công ty lữ hành phải xác nhận số lượng phòng thực tế và danh sách khách (Rooming List); sau thời điểm này các phòng không xác nhận sẽ tự động bị khách sạn thu hồi bán cho bên khác mà không chịu phạt', 'Ngày trả tiền tip', 'Ngày khai trương khách sạn'], 1, 'CLO3'),
  q('TOU101_Q075', 'Một du khách theo tour bị dị ứng nghiêm trọng với hải sản (đã ghi chú rõ trong phiếu đăng ký tour). Trách nhiệm kiểm tra của nhân viên điều hành và HDV là:', 'HARD', ['Không cần làm gì thêm', 'Nhắc nhở và kiểm tra lại thực đơn với bếp của tất cả các nhà hàng trong hành trình để chế biến khẩu phần ăn riêng biệt, đồng thời HDV đối chiếu kỹ trước khi món ăn được dọn lên bàn khách', 'Bắt khách tự đi mua bánh mì', 'Bảo khách nhịn ăn'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('TOU101_Q076', 'Hệ thống Quản lý Doanh thu (Yield / Revenue Management) áp dụng trong định giá tour và phòng khách sạn dựa trên cơ chế nào?', 'EXPERT', ['Bán đồng giá cố định quanh năm', 'Định giá động (Dynamic Pricing) theo thời gian thực dựa trên thuật toán dự báo cầu thị trường, phân khúc khách hàng và thời điểm đặt chỗ nhằm tối đa hóa tổng doanh thu trên mỗi đơn vị dịch vụ sẵn có', 'Giảm giá 90% vào mùa hè', 'Chỉ bán cho khách VIP'], 1, 'CLO4'),
  q('TOU101_Q077', 'Phương pháp Đánh giá Vòng đời Sản phẩm Tour (Tour Product Life Cycle Management) đòi hỏi doanh nghiệp lữ hành phải thực hiện hành động nào khi một tour truyền thống bước vào giai đoạn bão hòa/suy thoái?', 'EXPERT', ['Vứt bỏ hoàn toàn tuyến điểm', 'Tái cấu trúc và làm mới sản phẩm (Tour Rejuvenation): Bổ sung các trải nghiệm độc đáo mới (ẩm thực địa phương, workshop nghề thủ công, ứng dụng công nghệ thực tế ảo AR), thay đổi phân khúc thị trường mục tiêu', 'Giữ nguyên sản phẩm cũ', 'Chỉ chạy quảng cáo tốn kém'], 1, 'CLO4'),
  q('TOU101_Q078', 'Bộ chỉ số Quản lý Rủi ro ISO 31000 áp dụng trong vận hành doanh nghiệp lữ hành quốc tế chuẩn hóa quy trình nào?', 'EXPERT', ['In ấn brochure quảng cáo', 'Nhận diện rủi ro -> Phân tích rủi ro -> Đánh giá mức độ rủi ro -> Xử lý kiểm soát rủi ro (Giảm thiểu, Chuyển giao qua bảo hiểm, Né tránh) -> Giám sát và truyền thông liên tục', 'Tuyển chọn tiếp viên hàng không', 'Chấm điểm khách sạn'], 1, 'CLO4'),
  q('TOU101_Q079', 'Hợp đồng liên minh kinh doanh kiểu Code-share (Liên danh chuyến bay) giữa các hãng hàng không mang lại giá trị gia tăng nào cho việc thiết kế tour lữ hành toàn cầu?', 'EXPERT', ['Làm giá vé đắt hơn', 'Cho phép các hãng bay kết nối mạng lưới đường bay của nhau, du khách chỉ cần mua 1 vé duy nhất, làm thủ tục check-in và gửi hành lý thẳng tới điểm đến cuối cùng qua nhiều chặng bay liên minh', 'Làm thất lạc hành lý nhiều hơn', 'Tất cả máy bay đều cùng một loại'], 1, 'CLO4'),
  q('TOU101_Q080', 'Cơ chế giải quyết tranh chấp du lịch quốc tế thông qua Tòa Trọng tài Quốc tế (như ICC hoặc VIAC) được ưu tiên lựa chọn trong các hợp đồng lữ hành xuyên biên giới nhờ ưu thế nào?', 'EXPERT', ['Tất cả các phiên tòa đều công khai cho báo chí', 'Tính bảo mật thông tin kinh doanh, thủ tục nhanh chóng linh hoạt, sự am hiểu sâu sắc của các trọng tài viên về thông lệ thương mại du lịch quốc tế và phán quyết có hiệu lực thi hành tại hơn 160 quốc gia theo Công ước New York', 'Chi phí luôn bằng 0', 'Bắt buộc xử theo luật của nước nhỏ hơn'], 1, 'CLO4')
];

// ĐỀ GỐC 3 (40 câu): Hướng dẫn du lịch, Quản trị khách sạn & dịch vụ lưu trú, Chuyển đổi số & Du lịch bền vững
const root3 = [
  // Nhận biết (10 câu)
  q('TOU101_Q081', 'Theo Luật Du lịch Việt Nam 2017, Hướng dẫn viên du lịch bao gồm các loại thẻ nào sau đây?', 'EASY', ['Hướng dẫn viên cao cấp và sơ cấp', 'Hướng dẫn viên du lịch quốc tế, Hướng dẫn viên du lịch nội địa, Hướng dẫn viên du lịch tại điểm', 'Hướng dẫn viên tự do và chính thức', 'Hướng dẫn viên trên bờ và dưới biển'], 1, 'CLO1'),
  q('TOU101_Q082', 'Điều kiện về trình độ học vấn để được cấp Thẻ Hướng dẫn viên du lịch quốc tế tại Việt Nam là gì?', 'EASY', ['Tốt nghiệp Trung học cơ sở', 'Tốt nghiệp cao đẳng trở lên chuyên ngành hướng dẫn du lịch; hoặc tốt nghiệp cao đẳng trở lên chuyên ngành khác và có chứng chỉ nghiệp vụ hướng dẫn du lịch quốc tế kèm chứng chỉ ngoại ngữ phù hợp', 'Chỉ cần biết lái xe ô tô', 'Tốt nghiệp tiểu học'], 1, 'CLO1'),
  q('TOU101_Q083', 'Bộ phận Lễ tân (Front Office - FO) trong khách sạn được ví như là:', 'EASY', ['Trái tim / Bộ mặt đại diện của khách sạn, là điểm tiếp xúc đầu tiên và trực tiếp giải quyết mọi yêu cầu của khách từ check-in đến check-out', 'Khu vực cấm vào', 'Nơi bảo dưỡng máy móc', 'Phòng kế toán nội bộ'], 0, 'CLO1'),
  q('TOU101_Q084', 'Bộ phận Buồng phòng (Housekeeping - HK) trong khách sạn chịu trách nhiệm chính về công việc gì?', 'EASY', ['Bán tour du lịch', 'Đảm bảo sự sạch sẽ, vệ sinh, gọn gàng, an toàn và thẩm mỹ của tất cả các phòng khách, khu vực công cộng và dịch vụ giặt là trong khách sạn', 'Nấu các món ăn tiệc', 'Bảo vệ an ninh bãi xe'], 1, 'CLO1'),
  q('TOU101_Q085', 'Bộ phận F&B (Food and Beverage) trong khách sạn đảm nhận chức năng gì?', 'EASY', ['Kinh doanh phòng ngủ', 'Kinh doanh dịch vụ ẩm thực, phục vụ ăn uống tại các nhà hàng, quầy bar, phòng tiệc hội nghị và dịch vụ phục vụ tận phòng (Room Service)', 'Bảo dưỡng thang máy', 'Bán vé máy bay'], 1, 'CLO1'),
  q('TOU101_Q086', 'Tiêu chuẩn xếp hạng khách sạn từ 1 sao đến 5 sao tại Việt Nam do cơ quan nào thẩm định và ban hành?', 'EASY', ['Hội phụ nữ', 'Cục Du lịch Quốc gia Việt Nam (Bộ Văn hóa, Thể thao và Du lịch) thẩm định theo Tiêu chuẩn Quốc gia TCVN 4391', 'Chủ khách sạn tự dán nhãn sao', 'Công ty bảo vệ'], 1, 'CLO1'),
  q('TOU101_Q087', 'Trang web OTA (Online Travel Agency) là thuật ngữ chỉ các nền tảng kinh doanh nào?', 'EASY', ['Cơ quan quản lý nhà nước', 'Đại lý du lịch trực tuyến chuyên bán phòng khách sạn, vé máy bay và tour qua ứng dụng Internet (như Booking.com, Agoda, Traveloka, Trip.com)', 'Trang web trò chơi trực tuyến', 'Trang báo điện tử'], 1, 'CLO1'),
  q('TOU101_Q088', 'Khái niệm "Khách du lịch tự túc" (FIT - Free Independent Traveler) dùng để chỉ:', 'EASY', ['Khách đi theo tour trọn gói 50 người', 'Khách du lịch cá nhân hoặc nhóm nhỏ tự lên kế hoạch, tự đặt các dịch vụ riêng lẻ mà không đi theo tour trọn gói cố định của công ty lữ hành', 'Khách không trả tiền dịch vụ', 'Khách đi bằng tàu hỏa'], 1, 'CLO1'),
  q('TOU101_Q089', 'Khái niệm "GIT" (Group Inclusive Tour) trong du lịch là:', 'EASY', ['Khách đi một mình', 'Khách du lịch đi theo đoàn trọn gói có hướng dẫn viên theo suốt tuyến và tổ chức theo chương trình định sẵn', 'Khách đi công tác', 'Khách ba lô'], 1, 'CLO1'),
  q('TOU101_Q090', 'Nguyên tắc cơ bản nhất trong Đạo đức nghề nghiệp của Hướng dẫn viên du lịch là gì?', 'EASY', ['Bằng mọi cách ép khách mua sắm để nhận hoa hồng cao', 'Tôn trọng du khách, trung thực, bảo đảm an toàn tính mạng tài sản của khách, tôn trọng pháp luật và bảo vệ hình ảnh văn hóa đất nước', 'Bỏ rơi khách khi hết giờ làm việc', 'Nhận tiền tip trước mới phục vụ'], 1, 'CLO1'),

  // Thông hiểu (15 câu)
  q('TOU101_Q091', 'Chỉ số RevPAR (Revenue Per Available Room - Doanh thu trên mỗi phòng sẵn có) trong khách sạn được tính bằng công thức:', 'MEDIUM', ['RevPAR = Tổng doanh thu / Tổng số khách', 'RevPAR = Công suất phòng trung bình (Occupancy Rate) * Giá bán phòng trung bình (ADR)', 'RevPAR = Tiền lương nhân viên / Số phòng', 'RevPAR = Giá phòng cao nhất'], 1, 'CLO2'),
  q('TOU101_Q092', 'Chỉ số ADR (Average Daily Rate) trong quản trị khách sạn đo lường điều gì?', 'MEDIUM', ['Giá phòng trung bình thực tế thu được trên mỗi phòng có khách ở trong một ngày', 'Số phòng bị bỏ trống', 'Chi phí giặt là một ngày', 'Tổng lợi nhuận của nhà hàng'], 0, 'CLO2'),
  q('TOU101_Q093', 'Kỹ thuật bán nâng cấp phòng (Up-selling) tại quầy Lễ tân khách sạn được thực hiện khi nào?', 'MEDIUM', ['Khi khách muốn hủy phòng', 'Khi nhân viên lễ tân khéo léo giới thiệu và thuyết phục khách hàng nâng cấp lên hạng phòng cao hơn (như Suite, Ocean View) với mức phụ thu hợp lý tại thời điểm check-in', 'Bán thêm đồ lưu niệm', 'Bán vé xe buýt'], 1, 'CLO2'),
  q('TOU101_Q094', 'Hình thức lưu trú "Homestay" chuẩn mực mang lại trải nghiệm cốt lõi nào cho du khách?', 'MEDIUM', ['Dịch vụ sang trọng như khách sạn 5 sao', 'Trải nghiệm "Cùng ăn, cùng ở, cùng sinh hoạt" với gia đình người dân địa phương để tìm hiểu sâu sắc về phong tục tập quán và đời sống thực tế', 'Tự do nấu nướng một mình trong căn hộ biệt lập', 'Nghỉ dưỡng trong rừng không có người'], 1, 'CLO2'),
  q('TOU101_Q095', 'Khái niệm "Điểm đến du lịch thông minh" (Smart Tourism Destination) ứng dụng các công nghệ nào?', 'MEDIUM', ['Chỉ dùng đèn chiếu sáng thông thường', 'Ứng dụng IoT, Dữ liệu lớn (Big Data), Trí tuệ nhân tạo (AI), Điện toán đám mây và 5G để quản lý dòng khách, cung cấp thông tin số hóa đa ngôn ngữ thời gian thực cho du khách', 'Xây dựng nhiều nhà cao tầng', 'Tất cả dịch vụ do robot làm'], 1, 'CLO2'),
  q('TOU101_Q096', 'Tại sao hướng dẫn viên du lịch tuyệt đối không được tự ý đưa quan điểm chính trị, tôn giáo cực đoan hoặc phán xét cá nhân vào bài thuyết minh?', 'MEDIUM', ['Vì bài thuyết minh sẽ bị dài', 'Vì cần đảm bảo tính khách quan khoa học, tôn trọng sự đa dạng văn hóa tín ngưỡng của du khách và giữ gìn hình ảnh quốc gia', 'Vì khách không biết tiếng Việt', 'Do quy định của hãng xe'], 1, 'CLO2'),
  q('TOU101_Q097', 'Phương pháp thuyết minh du lịch kết hợp nghệ thuật Kể chuyện (Storytelling) mang lại hiệu quả gì?', 'MEDIUM', ['Đọc thuộc lòng các con số thống kê khô khan', 'Thổi hồn cảm xúc vào các di tích, biến các sự kiện lịch sử thành những câu chuyện sống động, hấp dẫn, chạm vào trái tim và khắc sâu vào trí nhớ của du khách', 'Làm cho du khách dễ ngủ trên xe', 'Tránh phải trả lời câu hỏi'], 1, 'CLO2'),
  q('TOU101_Q098', 'Khi một du khách trong đoàn có biểu hiện bị sốc nhiệt / say nắng trong chuyến tham quan ngoài trời, sơ cứu chuẩn ban đầu là:', 'MEDIUM', ['Cho uống nước đá thật lạnh ngay', 'Đưa du khách ngay vào chỗ râm mát, nới lỏng quần áo, quạt mát, lau khăn ướt lên trán/nách và cho uống từng ngụm nhỏ nước có pha chút muối hoặc Oresol', 'Bắt khách tiếp tục đi bộ', 'Đắp chăn ấm kín người'], 1, 'CLO2'),
  q('TOU101_Q099', 'Hệ thống Quản lý Khách sạn PMS (Property Management System, ví dụ: Opera, Smile) hỗ trợ quản trị các nghiệp vụ nào?', 'MEDIUM', ['Tự động lái xe đưa đón', 'Quản lý đặt phòng, hồ sơ khách hàng, tình trạng buồng phòng, thanh toán hóa đơn, tích hợp khóa thẻ từ và báo cáo tài chính của khách sạn', 'Chỉ dùng để quét mã QR', 'Dùng để chụp ảnh nhân viên'], 1, 'CLO2'),
  q('TOU101_Q100', 'Thuật ngữ "Turn-down Service" (Dịch vụ chỉnh trang phòng buổi tối) của bộ phận Buồng phòng bao gồm:', 'MEDIUM', ['Dọn sạch toàn bộ đồ đạc của khách', 'Trải lại góc chăn ga gối ngủ, kéo rèm cửa, bật đèn ngủ ấm áp, đặt nước uống/thanh chocolate và xịt hương tinh dầu dịu nhẹ tạo không gian thư giãn cho giấc ngủ của khách', 'Thay đổi toàn bộ nội thất', 'Tính thêm tiền dịch vụ'], 1, 'CLO2'),
  q('TOU101_Q101', 'Kỹ năng Hoạt náo (Animation) của hướng dẫn viên trên xe ô tô du lịch nhằm giải quyết vấn đề gì?', 'MEDIUM', ['Bắt du khách phải thức suốt đêm', 'Xua tan sự mệt mỏi trong các chặng đường dài, kết nối các thành viên trong đoàn, tạo bầu không khí vui tươi, gắn kết thông qua các trò chơi giao lưu và câu đố trí tuệ', 'Tập thể dục trên nóc xe', 'Tránh nói chuyện với lái xe'], 1, 'CLO2'),
  q('TOU101_Q102', 'Nguyên tắc "Leave No Trace" (Không để lại dấu vết) trong du lịch sinh thái và cắm trại ngoài trời bao gồm thông điệp cốt lõi nào?', 'MEDIUM', ['Được phép chặt cây nhóm lửa thoải mái', '"Không lấy gì ngoài những bức ảnh, không để lại gì ngoài những dấu chân, không giết gì ngoài thời gian" - bảo vệ nguyên vẹn môi trường thiên nhiên hoang dã', 'Được chôn rác nhựa dưới đất', 'Mang các loài động vật hoang dã về nuôi'], 1, 'CLO2'),
  q('TOU101_Q103', 'Chứng nhận Nhãn sinh thái Bông Sen Xanh áp dụng cho các cơ sở lưu trú du lịch tại Việt Nam nhằm tôn vinh điều gì?', 'MEDIUM', ['Khách sạn có giá phòng đắt nhất', 'Cơ sở lưu trú có nỗ lực bảo vệ môi trường, sử dụng năng lượng tiết kiệm hiệu quả, giảm rác thải nhựa và đóng góp cho phát triển du lịch bền vững', 'Khách sạn trồng nhiều hoa sen', 'Cơ sở có nhiều bể bơi nhất'], 1, 'CLO2'),
  q('TOU101_Q104', 'Dịch vụ Concierge tại sảnh khách sạn 5 sao có chức năng chuyên biệt gì phục vụ khách?', 'MEDIUM', ['Chỉ xách hành lý', 'Cung cấp dịch vụ hỗ trợ thông tin chuyên sâu cao cấp cho khách: Đặt bàn nhà hàng Michelin, mua vé xem nghệ thuật đặc biệt, thuê xe sang, đặt tour riêng và giải quyết mọi yêu cầu cá nhân hóa đặc thù', 'Kiểm tra giấy tờ tùy thân', 'Bảo dưỡng điều hòa'], 1, 'CLO2'),
  q('TOU101_Q105', 'Ứng dụng Thẻ Du lịch Thông minh và Công nghệ nhận diện khuôn mặt (FaceID / Biometrics) tại các sân bay và điểm du lịch mang lại lợi thế gì?', 'MEDIUM', ['Làm thủ tục lâu hơn', 'Tối ưu hóa quy trình thủ tục không chạm (Contactless), rút ngắn thời gian làm thủ tục qua cổng kiểm soát an ninh từ vài phút xuống chỉ còn vài giây', 'Bắt buộc khách phải dùng tiền mặt', 'Khóa tài khoản ngân hàng'], 1, 'CLO2'),

  // Vận dụng (10 câu)
  q('TOU101_Q106', 'Một khách sạn có 200 phòng, trong ngày có 160 phòng có khách ở. Tổng doanh thu tiền phòng trong ngày là 240.000.000 đồng. Giá bán phòng trung bình (ADR) và Công suất phòng (Occupancy Rate) trong ngày là:', 'HARD', ['ADR = 1.200.000đ; Occupancy = 90%', 'ADR = 1.500.000đ (240.000.000 / 160); Occupancy = 80% (160 / 200 * 100%)', 'ADR = 1.000.000đ; Occupancy = 75%', 'ADR = 1.800.000đ; Occupancy = 85%'], 1, 'CLO3'),
  q('TOU101_Q107', 'Với khách sạn trên, chỉ số doanh thu trên mỗi phòng sẵn có (RevPAR) trong ngày bằng bao nhiêu?', 'HARD', ['1.000.000 đồng', '1.200.000 đồng (RevPAR = 240.000.000 / 200 = 1.200.000đ, hoặc 1.500.000 * 0.8 = 1.200.000đ)', '1.500.000 đồng', '800.000 đồng'], 1, 'CLO3'),
  q('TOU101_Q108', 'Khi dẫn đoàn tham quan một ngôi chùa cổ linh thiêng tại Huế, HDV phát hiện một số khách trong đoàn mặc quần áo ngắn hở hang không phù hợp thuần phong mỹ tục. Cách xử lý văn hóa và khéo léo nhất của HDV là:', 'HARD', ['Mắng mỏ khách gay gắt trước đám đông', 'Nhẹ nhàng giải thích ý nghĩa tâm linh trang nghiêm của ngôi chùa, hỗ trợ cung cấp khăn quấn dài / áo choàng mượn tại cổng di tích trước khi đoàn bước vào chánh điện', 'Bỏ mặc cho khách vào tự do', 'Đuổi khách về khách sạn'], 1, 'CLO3'),
  q('TOU101_Q109', 'Một khách sạn 4 sao bị hiện tượng Overbooking (Đặt phòng vượt mức 5%) vào ngày lễ do tính toán tỷ lệ hủy phòng bị sai lệch. Khi khách đến check-in mà không còn phòng trống, giải pháp chuyên nghiệp của Giám đốc Lễ tân là:', 'HARD', ['Đuổi khách ra ngoài đường', 'Chân thành xin lỗi, nâng cấp chuyển khách sang khách sạn đối tác tương đương hoặc cao cấp hơn (5 sao) ở gần đó, thanh toán toàn bộ chi phí xe đưa đón và tặng voucher dịch vụ bồi thường', 'Bắt khách ngồi chờ đến sáng', 'Bảo khách tự đi tìm nhà nghỉ'], 1, 'CLO3'),
  q('TOU101_Q110', 'Trong quá trình thuyết minh về danh thắng Vịnh Hạ Long, một du khách nước ngoài hỏi HDV câu hỏi hóc búa về địa chất mà HDV chưa nắm rõ thông tin. Ứng xử chuyên nghiệp của HDV là:', 'HARD', ['Bịa đặt ra một câu chuyện thần bí hoang đường để lừa khách', 'Thành thật thừa nhận câu hỏi rất thú vị và chuyên sâu, xin phép ghi nhận lại câu hỏi để tra cứu tài liệu chuyên khảo xác thực và phản hồi lại cho khách vào buổi chiều', 'Tỏ thái độ tức giận với khách', 'Lờ đi như không nghe thấy'], 1, 'CLO3'),
  q('TOU101_Q111', 'Một điểm du lịch làng nghề gốm sứ truyền thống muốn áp dụng mô hình "Du lịch trải nghiệm sáng tạo" (Creative Tourism). Hành động đổi mới nào tạo sức hút lớn nhất?', 'HARD', ['Chỉ bày gốm trong tủ kính có bảo vệ', 'Thiết kế xưởng thực hành cho phép du khách được nghệ nhân hướng dẫn trực tiếp ngồi vào bàn xoay tự tay nhào nặn chiếc bát gốm của mình, tự vẽ hoa văn và nung mang về làm kỷ niệm', 'Bán đồ sứ nhập khẩu từ nước ngoài', 'Cấm du khách chạm tay vào đất sét'], 1, 'CLO3'),
  q('TOU101_Q112', 'Khi khách hàng đăng tải đánh giá tiêu cực 1 sao kèm hình ảnh chê bai thức ăn nguội lạnh trên nền tảng TripAdvisor của một nhà hàng du lịch, phản hồi chuyên nghiệp của bộ phận CSKH là:', 'HARD', ['Xóa bình luận và chửi bới khách', 'Gửi lời cảm ơn chân thành đã góp ý, nhận lỗi về sự thiếu sót trong quy trình phục vụ, giải thích biện pháp khắc phục cụ thể và mời khách quay lại trải nghiệm với lời xin lỗi chu đáo', 'Đe dọa kiện khách ra tòa', 'Giả vờ là nhà hàng khác'], 1, 'CLO3'),
  q('TOU101_Q113', 'Trong bối cảnh chuyển đổi số, việc số hóa 3D và ứng dụng công nghệ thực tế ảo VR (Virtual Reality) tại các bảo tàng và di tích lịch sử mang lại giá trị gì?', 'HARD', ['Làm cho bảo tàng vắng khách vĩnh viễn', 'Lưu trữ bảo tồn dữ liệu di sản kỹ thuật số vĩnh viễn, cho phép du khách trên toàn cầu tham quan từ xa và tạo ra trải nghiệm tương tác trực quan sống động trước khi đến thăm thực tế', 'Tăng tiền bán vé giấy', 'Thay thế hoàn toàn hiện vật gốc'], 1, 'CLO3'),
  q('TOU101_Q114', 'Một khách sạn triển khai chương trình "Khách sạn Xanh không rác thải nhựa". Các biện pháp thay thế thiết thực bao gồm:', 'HARD', ['Dùng thêm nhiều túi nilon', 'Thay thế chai nước nhựa dùng một lần bằng chai thủy tinh tái sử dụng, dùng ống hút giấy/cỏ bàng, sử dụng bình đựng dầu gội sữa tắm sứ gắn tường thay cho các tuýp nhựa mini một lần', 'Vứt rác nhựa xuống biển ban đêm', 'Cấm khách uống nước'], 1, 'CLO3'),
  q('TOU101_Q115', 'Để kiểm soát chất lượng giọng nói và sức bền thể lực của Hướng dẫn viên trong các chuyến dẫn tour dài ngày, lời khuyên khoa học về thanh nhạc là:', 'HARD', ['Hét thật to bằng thanh quản cổ họng', 'Kỹ thuật lấy hơi sâu từ cơ hoành (thở bụng), phát âm tròn vành rõ chữ, giữ ẩm cổ họng bằng nước ấm và sử dụng máy trợ giảng có micro cài tai để bảo vệ dây thanh đới', 'Uống nhiều nước đá lạnh', 'Hút thuốc lá liên tục'], 1, 'CLO3'),

  // Vận dụng cao (5 câu)
  q('TOU101_Q116', 'Khái niệm "Kinh tế Trải nghiệm" (The Experience Economy của Pine & Gilmore) nâng tầm giá trị dịch vụ du lịch qua 4 giai đoạn tiến hóa kinh tế nào?', 'EXPERT', ['Hàng hóa thô (Commodities) -> Sản phẩm chế tạo (Goods) -> Dịch vụ (Services) -> Trải nghiệm đáng nhớ gắn liền với sự chuyển hóa cá nhân (Experiences & Transformations)', 'Nông nghiệp -> Công nghiệp -> Công nghệ -> Tiền tệ', 'Mua rẻ -> Bán đắt -> Lãi cao -> Phá sản', 'Trực tiếp -> Gián tiếp -> Trung gian -> Cuối cùng'], 0, 'CLO4'),
  q('TOU101_Q117', 'Hệ sinh thái Quản trị Khách sạn ứng dụng Trí tuệ Nhân tạo (AI Revenue Management System - RMS) tự động hóa quyết định nào?', 'EXPERT', ['Tự động thay ga giường', 'Tự động phân tích hàng triệu dữ liệu chuyến bay, thời tiết, lịch sự kiện và giá đối thủ cạnh tranh để tự động điều chỉnh biểu giá phòng linh hoạt từng giây nhằm tối ưu hóa tổng doanh thu và công suất phòng', 'Tự động nấu ăn cho toàn khách sạn', 'Tự động đuổi khách không trả tiền'], 1, 'CLO4'),
  q('TOU101_Q118', 'Tiêu chuẩn Toàn cầu về Du lịch Bền vững của Hội đồng Du lịch Bền vững Toàn cầu (GSTC Criteria) đánh giá dựa trên 4 trụ cột cốt lõi nào?', 'EXPERT', ['Quy mô vốn, Số lượng nhân viên, Doanh số, Lợi nhuận', 'Quản lý bền vững hiệu quả; Lợi ích kinh tế xã hội cho cộng đồng địa phương; Bảo tồn di sản văn hóa; và Bảo tồn môi trường tự nhiên, giảm thiểu ô nhiễm', 'Chỉ số quảng cáo, Số lượt like facebook, View tiktok, Báo chí', 'Số lượng sao khách sạn'], 1, 'CLO4'),
  q('TOU101_Q119', 'Mô hình Quản trị Điểm đến Du lịch (DMO - Destination Management Organization) theo hướng Hợp tác Công - Tư (Public-Private Partnership - PPP) có vai trò gì?', 'EXPERT', ['Tư nhân hóa toàn bộ di sản thiên nhiên', 'Hợp nhất vai trò định hướng chính sách của chính quyền với năng lực tài chính, công nghệ và tính năng động của khối doanh nghiệp tư nhân nhằm quảng bá thương hiệu điểm đến và phát triển bền vững', 'Chỉ dùng để thu tiền vé tham quan', 'Thay thế toàn bộ các công ty lữ hành'], 1, 'CLO4'),
  q('TOU101_Q120', 'Khái niệm "Du lịch tái tạo" (Regenerative Tourism) vượt lên trên khái niệm Du lịch bền vững (Sustainable Tourism) truyền thống ở điểm mấu chốt nào?', 'EXPERT', ['Du lịch chỉ để chụp ảnh', 'Không chỉ dừng lại ở việc "không gây hại / giữ nguyên hiện trạng" (Do no harm), mà các hoạt động du lịch phải chủ động phục hồi, làm cho hệ sinh thái tự nhiên và cộng đồng địa phương trở nên tốt hơn, thịnh vượng và kiên cường hơn so với trước khi du lịch xuất hiện', 'Xây dựng thêm nhiều tòa nhà bê tông', 'Tăng gấp 5 lần số lượng khách đại chúng'], 1, 'CLO4')
];

module.exports = {
  course: {
    code: 'TOU101',
    name: 'Tổng Quan Du Lịch & Dịch Vụ Lữ Hành',
    faculty: 'Khoa Du Lịch & Khách Sạn',
    category_code: 'CAT-TOU101',
    credits: 3
  },
  root_1: root1,
  root_2: root2,
  root_3: root3,
  getAllQuestions: () => [...root1, ...root2, ...root3]
};
